### PR TITLE
[Feature][flink-connector-jdbc] support param placeholder replacing row index

### PR DESCRIPTION
**Pull request by kalencaya**
## Purpose of this pull request

support #1829 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by kalencaya** [comment]
#1829

**Review by CalvinKirs — COMMENTED** [review]
Could you add some ut validations to this PR?

**Comment by kalencaya** [comment]
> Could you add some ut validations to this PR?

yes, of course I do

**Comment by EricJoy2048** [comment]
This pr is closed because it has not responded for too long. If necessary, please reopen it.

**Pull request closed without merging**
