### PR TITLE
[Improve][Connector-V2] Improve mongodb connector

### PR DESCRIPTION
**Pull request by hailin0**
## Purpose of this pull request

Improve mongodb connector
* Fix schema projection
* Fix datatype conversion between MongoDB and SeaTunnel
* Support use `SimpleTextSchema` read & write

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
this is e2e-testcase
https://github.com/apache/incubator-seatunnel/pull/2778/files#diff-f3c93d4b225ae14c2df31976fc9d1f36375ff20367b3eb13c48c07866c823792R106

**Comment by hailin0** [comment]
@wuchunfu 

please help to review

**Comment by hailin0** [comment]
@TyrantLucifer @laglangyue @legendtkl @zhuangchong @hailin0 @ashulin @Hisoka-X @CalvinKirs @ic4y @lhyundeadsoul @wolfboys @2013650523 @531651225

I try @ everyone I know. please help to review

**Review by Hisoka-X — APPROVED** [review]

**Review by ashulin — APPROVED** [review]
LGTM

**Pull request merged**
