### PR TITLE
[Improve][Doc] Improve DingTalk doc

### PR DESCRIPTION
**Pull request by MRYOG**
Improve DingTalk doc 
include Chinese doc and right doc rule

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @zhilinli123 as well.

**Comment by Hisoka-X** [comment]
Please use `mvn spotless:apply` to format doc before commit.

**Comment by MRYOG** [comment]
> Please use `mvn spotless:apply` to format doc before commit.

Hello, I ran mvn spotless:apply locally and found a document that needs formatting. Can you help me check if the submission is now correct?

**Comment by Hisoka-X** [comment]
> > Please use `mvn spotless:apply` to format doc before commit.
> 
> Hello, I ran mvn spotless:apply locally and found a document that needs formatting. Can you help me check if the submission is now correct?

Thanks @MRYOG for update, waiting ci passed.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
