### PR TITLE
[BUG][Zeta] Multiple sink actions of the same type have the same name

### PR DESCRIPTION
**Pull request by Carl-Zhou-CN**
In config
```env {
  execution.parallelism = 1
  job.mode = "BATCH"
  checkpoint.interval = 5000
}

source {
  FakeSource {
    result_table_name = "fake1"
    parallelism = 1
    schema = {
      fields {
        name = "string"
        age = "string"
      }
    }
  }
}

transform {
  sql{
     source_table_name = fake1
     query = "select name,age,'2023' as time from fake1"
     result_table_name = sql1
  }

    sql{
       source_table_name = fake1
       query = "select name,age,'2024' as time from fake1"
       result_table_name = sql2
    }
}

sink {
 Hive {
     source_table_name = "sql1"
     table_name = "default.part_test"
     metastore_uri = "xxxxxx"
 }
  Hive {
     source_table_name = "sql2"
     table_name = "default.part_test"
     metastore_uri = "thrift://xxxxx"
 }
}
```
The action name of hive sink is identified as the same

image

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Could you add some test case for this?

**Comment by Carl-Zhou-CN** [comment]
> Could you add some test case for this?

ok

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X @hailin0 PTAL

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Thanks @Carl-Zhou-CN

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
