### PR TITLE
[Feature][Flink-SQL-connector] add flink sql connector elasticsearch 6&7 and docs

### PR DESCRIPTION
**Pull request by legendtkl**
## Purpose of this pull request

issue link https://github.com/apache/incubator-seatunnel/issues/1922

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by legendtkl** [comment]
Hi, @ruanwenjun , would you help review this PR?

Thanks.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by ruanwenjun** [comment]
@legendtkl I see the code at `Executor`, can the CustomClassLoader load the plugin jar? it seems you don't add the jar path into the classloader before you execute below code.
```java
Iterator<Factory> factories = ServiceLoader.load(Factory.class, CLASSLOADER).iterator();
```

**Comment by legendtkl** [comment]
> @legendtkl I see the code at `Executor`, can the CustomClassLoader load the plugin jar? it seems you don't add the jar path into the classloader before you execute below code.
> 
> ```java
> Iterator<Factory> factories = ServiceLoader.load(Factory.class, CLASSLOADER).iterator();
> ```

Hi, @ruanwenjun , Flink SQL connector jars will not be added to the JVM classpath by default. We will add it to the classpath when we parse the SQL and find the connector Factory not in Classloader.

This is what `Executor.loadConnector` method does.

**Comment by ruanwenjun** [comment]
> > @legendtkl I see the code at `Executor`, can the CustomClassLoader load the plugin jar? it seems you don't add the jar path into the classloader before you execute below code.
> > ```java
> > Iterator<Factory> factories = ServiceLoader.load(Factory.class, CLASSLOADER).iterator();
> > ```
> 
> Hi, @ruanwenjun , Flink SQL connector jars will not be added to the JVM classpath by default. We will add it to the classpath when we parse the SQL and find the connector Factory not in Classloader.
> 
> This is what `Executor.loadConnector` method does.

I understand. When the connector has not been loaded, you will find the connector jar and add to classoader. There is no problem.
```java
while (factories.hasNext()) {
    Factory factory = factories.next();

    /**
     * Handle for two cases:
     * 1. Flink built-in connectors.
     * 2. Connectors have been placed in classpath.
     */
    if (factory.factoryIdentifier().equals(connectorType)) {
        return;
    }
}
```

**Pull request merged**
