### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by adarsh-jha-dev**
### Purpose of this pull request

This pull request updates the Apache SeaTunnel README to improve clarity and readability. It includes a restructured layout, organized sections, and improved formatting. The content remains largely the same, but the changes aim to enhance the overall user experience and understanding of the project.

### Does this PR introduce _any_ user-facing change?
No, this pull request does not introduce any user-facing changes in terms of functionality. It focuses on improving the documentation and does not modify the behavior of the SeaTunnel software. It aims to make it easier for users to access information about the project.

### How was this patch tested?
This patch primarily involves documentation changes. Testing was performed manually by reviewing the document for accuracy, readability, and proper formatting. No new functionality or code changes were introduced in this pull request.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @adarsh-jha-dev ! Could you open github action on your fork repository? Please follow https://github.com/apache/seatunnel/pull/5662/checks?check_run_id=17850365639 as guide.

**Comment by adarsh-jha-dev** [comment]
> Thanks @adarsh-jha-dev ! Could you open github action on your fork repository? Please follow https://github.com/apache/seatunnel/pull/5662/checks?check_run_id=17850365639 as guide.

Done

**Comment by Hisoka-X** [comment]
> > Thanks @adarsh-jha-dev ! Could you open github action on your fork repository? Please follow https://github.com/apache/seatunnel/pull/5662/checks?check_run_id=17850365639 as guide.
> 
> Done

Please push some emtpy commit to trigger ci.

**Comment by adarsh-jha-dev** [comment]
> > > Thanks @adarsh-jha-dev ! Could you open github action on your fork repository? Please follow https://github.com/apache/seatunnel/pull/5662/checks?check_run_id=17850365639 as guide.
> > 
> > 
> > Done
> 
> Please push some emtpy commit to trigger ci.

Done, build in progress, thanks for your assistance.

**Comment by adarsh-jha-dev** [comment]
Build also done.

**Review by Hisoka-X — APPROVED** [review]
Overall LGTM, Thanks @adarsh-jha-dev !

**Comment by adarsh-jha-dev** [comment]
> Overall LGTM, Thanks @adarsh-jha-dev !

Grateful to hear that, will be pleased if merged successfully.

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
