### PR TITLE
[Improve] Skip downloading transitive dependency when install plugins

### PR DESCRIPTION
**Pull request by kevinjmh**
### Purpose of this pull request

Skip downloading transitive dependency when install plugins to improve user experience

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Fresh new install local test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

Before:
image

After:
image

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @kevinjmh ! Could you follow the guide to open github action on your fork repository? https://github.com/apache/seatunnel/pull/7374/checks?check_run_id=28636510415

**Comment by kevinjmh** [comment]
ok, it is opened now

**Comment by Hisoka-X** [comment]
Try push an emtpy commit to trigger it.

**Comment by Hisoka-X** [comment]
I noticed we're missing a test for the download script, would you be willing to add one in https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-e2e-common/src/test? Thanks.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
