### PR TITLE
[Bug][build] Fix build failed

### PR DESCRIPTION
**Pull request by xleoken**
## Purpose of this pull request

Met exception when build sub module.
```
cd seatunnel-apis/seatunnel-api-base
mvn clean package -DskipTests
```

```
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< org.apache.seatunnel:seatunnel-api-base >---------------
[INFO] Building seatunnel-api-base 2.1.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from aliyun: https://maven.aliyun.com/repository/public/org/apache/seatunnel/seatunnel/$%7Brevision%7D/seatunnel-$%7Brevision%7D.pom
Downloading from spring: https://maven.aliyun.com/repository/spring/org/apache/seatunnel/seatunnel/$%7Brevision%7D/seatunnel-$%7Brevision%7D.pom
Downloading from spring-plugin: https://maven.aliyun.com/repository/spring-plugin/org/apache/seatunnel/seatunnel/$%7Brevision%7D/seatunnel-$%7Brevision%7D.pom
Downloading from apache-snapshots: https://maven.aliyun.com/nexus/content/repositories/apache-snapshots/org/apache/seatunnel/seatunnel/$%7Brevision%7D/seatunnel-$%7Brevision%7D.pom
Downloading from mvn2: https://repo.maven.apache.org/maven2/org/apache/seatunnel/seatunnel/$%7Brevision%7D/seatunnel-$%7Brevision%7D.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by xleoken** [comment]
@ruanwenjun @CalvinKirs take a review when free, thanks.

**Comment by Hisoka-X** [comment]
Seem like SeaTunnel only can build on root directory, after you change this, if we use version which not release on maven repository, you also will build failed, because you dependency get from maven repository not local.

**Comment by Hisoka-X** [comment]
you can just add a properties in seatunnel-api-base/pom.xml named `revision`, and set value to `2.1.1-SNAPSHOT`. After you execute `mvn install`, I think the build will passed.

**Comment by xleoken** [comment]
hi @BenJFan 

> Seem like SeaTunnel only can build on root directory,

This is unfriendly for develoers, because we have many connectors.

> you can just add a properties in seatunnel-api-base/pom.xml named revision, and set value to 2.1.1-SNAPSHOT. After you execute mvn install, I think the build will passed.

It seems not a good practice, we need to add revision propertites to all sub modules

> After you change this, if we use version which not release on maven repository, you also will build failed, because you dependency get from maven repository not local

Right, we should build root project, then we can build sub module. But it failed when build sub module in dev branch.

**Comment by Hisoka-X** [comment]
> hi @BenJFan
> 
> > Seem like SeaTunnel only can build on root directory,
> 
> This is unfriendly for develoers, because we have many connectors.
> 
> > you can just add a properties in seatunnel-api-base/pom.xml named revision, and set value to 2.1.1-SNAPSHOT. After you execute mvn install, I think the build will passed.
> 
> It seems not a good practice, we need to add revision propertites to all sub modules
> 
> > After you change this, if we use version which not release on maven repository, you also will build failed, because you dependency get from maven repository not local
> 
> Right, we should build root project, then we can build sub module. But it failed when build sub module in dev branch.

Maybe we can create a assembly without connector, or just including fake and console？

**Comment by xleoken** [comment]
> Maybe we can create a assembly without connector, or just including fake and console？

In fact, we can not build any sub modules, like seatunnel-core-base, seatunnel-e2e, etc

**Comment by Hisoka-X** [comment]
> > Maybe we can create a assembly without connector, or just including fake and console？
> 
> In fact, we can not build any sub modules, like seatunnel-core-base, seatunnel-e2e, etc

I mean, we can build root project without connector, so that the build will be faster, save developer's time. I think you want only build sub project because build root project waste time, am I right?

**Comment by xleoken** [comment]
> > > Maybe we can create a assembly without connector, or just including fake and console？
> > 
> > 
> > In fact, we can not build any sub modules, like seatunnel-core-base, seatunnel-e2e, etc
> 
> I mean, we can build root project without connector, so that the build will be faster, save developer's time. I think you want only build sub project because build root project waste time, am I right?

When we need connectors, we will also met same failure 😭

**Comment by Hisoka-X** [comment]
> > > > Maybe we can create a assembly without connector, or just including fake and console？
> > > 
> > > 
> > > In fact, we can not build any sub modules, like seatunnel-core-base, seatunnel-e2e, etc
> > 
> > 
> > I mean, we can build root project without connector, so that the build will be faster, save developer's time. I think you want only build sub project because build root project waste time, am I right?
> 
> When we need connectors, we will also met same failure 😭



> > > > Maybe we can create a assembly without connector, or just including fake and console？
> > > 
> > > 
> > > In fact, we can not build any sub modules, like seatunnel-core-base, seatunnel-e2e, etc
> > 
> > 
> > I mean, we can build root project without connector, so that the build will be faster, save developer's time. I think you want only build sub project because build root project waste time, am I right?
> 
> When we need connectors, we will also met same failure 😭

In my view, perhaps we need new packge method to avoid this problem, but the way you submit in this PR can't pass.

**Comment by xleoken** [comment]
> In my view, perhaps we need new packge method to avoid this problem, but the way you submit in this PR can't pass.

it will make things more complex, and all other apache projects also do this, like spark、flink、hadoop

**Comment by Hisoka-X** [comment]
> > In my view, perhaps we need new packge method to avoid this problem, but the way you submit in this PR can't pass.
> 
> it will make things more complex, and all other apache projects also do this, like spark、flink、hadoop

SeaTunnel also do this way before 😂 #1672

**Comment by xleoken** [comment]
> > > In my view, perhaps we need new packge method to avoid this problem, but the way you submit in this PR can't pass.
> > 
> > 
> > it will make things more complex, and all other apache projects also do this, like spark、flink、hadoop
> 
> SeaTunnel also do this way before 😂 #1672

You're right. We need to revert it.

**Comment by ruanwenjun** [comment]
Good catch, we may need to find a better way to manage the version. The reason to use `${revision}` is hope that we can manage the project version in one way, when we want to change the project version, we can only change the parent pom or set by `-Drevision`.

This indeed unfriendly.

I find use `flatten-maven-plugin` can solve this problem.

**Comment by leo65535** [comment]
Tried `flatten-maven-plugin`, it will generate `.flattened-pom.xml` files.
image

**Comment by xleoken** [comment]
hi @ruanwenjun, the plugin worked in local env, but it will generate .flattened-pom.xml files, I had add it to .gitignore file.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by ruanwenjun** [comment]
@CalvinKirs @BenJFan Please take a look, this will affect the build process.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Comment by xleoken** [comment]
Thanks @BenJFan @ruanwenjun

**Pull request merged**
