### PR TITLE
[Improve] [doc] Using https instead of http for APL2

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This PR is using https instead of http for APL2

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/development/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
I find we also use the http link `http://www.apache.org/licenses/LICENSE-2.0.txt` in NOTICE, please replace these links in this PR.

**Comment by kezhenxu94** [comment]
@asdf2014 can you please merge all of these 👇 into one PR so that we can review and merge as quickly as possible? In my opinion most (if not all) of these are some chore cleanup or minor refactor, perhaps you can open one single PR with title like "Polish codes" or "clean up"

image

**Comment by asdf2014** [comment]
@ruanwenjun Nice catch :+1:

**Review by kezhenxu94 — CHANGES_REQUESTED** [review]
We have thousands of links that is http not https in this repo, why just modify one link in a PR, do you plan to open thousands of pull requests?

Also I don't think this is a problem, nearly all browsers automatically redirect from http to https.

**Pull request closed without merging**
