### PR TITLE
[Feature][robot]Add auto-translation robot

### PR DESCRIPTION
**Pull request by davidzollo**
There're many non-English issues in the issue list, this robot will auto translate the issue to English.

### CODE REVIEW

**Comment by Hisoka-X** [comment]
I'm not sure if we need this, it will make users more likely to submit issues in Chinese. This is what we don't want to see. cc @hailin0

**Comment by Hisoka-X** [comment]
I would rather have a script that can directly close Chinese issues

**Comment by hailin0** [comment]
> I would rather have a script that can directly close Chinese issues

+1
This may prompt users to submit questions in English

**Comment by davidzollo** [comment]
OK

**Pull request closed without merging**
