### PR TITLE
[Bug][KafkaSource]KafkaConsumer is not close.

### PR DESCRIPTION
**Pull request by lightzhao**
Fix the problem that KafkaConsumer of KafkaSource is not closed and the resource is not released.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by hailin0** [comment]
@ashulin

**Comment by lightzhao** [comment]
@hailin0 @ashulin please review, thanks.

**Comment by lightzhao** [comment]
@Hisoka-X @TyrantLucifer please review ，thanks.

**Review by Hisoka-X — DISMISSED** [review]

**Review by TaoZex — DISMISSED** [review]
+1

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
Please update https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/Error-Quick-Reference-Manual.md

**Comment by lightzhao** [comment]
> Please update https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/Error-Quick-Reference-Manual.md

done, thanks.

**Comment by lightzhao** [comment]
@TyrantLucifer please merge. thanks.

**Review by Hisoka-X — APPROVED** [review]

**Review by TaoZex — APPROVED** [review]
+1

**Comment by lightzhao** [comment]
@Hisoka-X please merge. thanks.

**Comment by Hisoka-X** [comment]
@TyrantLucifer PTAL

**Comment by lightzhao** [comment]
@TyrantLucifer PTAL

**Comment by lightzhao** [comment]
@TyrantLucifer PTAL, thanks.

**Comment by lightzhao** [comment]
@TyrantLucifer I have tested whether the consumer is safely closed after the kill flink task. Please help me review it to see if there are any problems.

**Comment by lightzhao** [comment]
@Hisoka-X @TyrantLucifer PTAL.

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
