### PR TITLE
[Improved][dist][connector-v2] Add `fake` and `console` connectors to binary package for demo

### PR DESCRIPTION
**Pull request by hailin0**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
image

**Review by TaoZex — DISMISSED** [review]

**Review by CalvinKirs — COMMENTED** [review]
update `https://github.com/apache/incubator-seatunnel/blob/dev/config/plugin_config`

**Review by ashulin — DISMISSED** [review]
LGTM

**Comment by hailin0** [comment]
> update `https://github.com/apache/incubator-seatunnel/blob/dev/config/plugin_config`

fixed @CalvinKirs

**Review by EricJoy2048 — DISMISSED** [review]
LGTM

**Review by ic4y — DISMISSED** [review]
+1

**Comment by CalvinKirs** [comment]
We'd better update the startup documentation for dev-brach binary packages.
This can be reflected in quick start.

**Comment by hailin0** [comment]
> We'd better update the startup documentation for dev-brach binary packages. This can be reflected in quick start.

The documentation is being changed on a separate branch, or I can merge into one commit

**Review by EricJoy2048 — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
