### PR TITLE
[Hotfix][Connector][Jdbc] Fix the problem of JdbcOutputFormat databas…

### PR DESCRIPTION
**Pull request by EchoLee5**
## Purpose of this pull request

When writing to the target table fails for some reason, for example, the target table does not exist.

The internal call sequence of JdbcOutputFormat is:
JdbcOutputFormat#flush(throws IOException) --> JdbcOutputFormat#close --> JdbcOutputFormat#flush(throws RuntimeException).

Will not call the close method of the database connection, when the restart strategy is fixeddelay, maxNumberRestartAttempts is Integer.MAX, this will cause the number of database connections to continue to rise and reach the limit.

`2022-12-07 10:49:32,050 ERROR org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat [] - JDBC executeBatch error, retry times = 3
java.sql.BatchUpdateException: ORA-00942: table or view does not exist
Caused by: java.sql.SQLException: Listener refused the connection with the following error:
ORA-12519, TNS:no appropriate service handler found `

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by EchoLee5** [comment]
cc @rewerma Please give me a review, thank you

**Comment by Hisoka-X** [comment]
@ic4y PTAL

**Review by ic4y — APPROVED** [review]

**Comment by ic4y** [comment]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Comment by EricJoy2048** [comment]
LGTM， Let's wait the CI complete.

**Comment by EchoLee5** [comment]
> LGTM， Let's wait the CI complete.

Thanks.

**Comment by EchoLee5** [comment]
> LGTM

Thanks.

**Comment by EricJoy2048** [comment]
Retry CI.

**Comment by EricJoy2048** [comment]
Please rebase the dev branch, this will resolve the CI problem.

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
CI error is not related to this PR. Thanks for your contribute!

**Pull request merged**
