### PR TITLE
[Fix] Fix flaky test `OptionUtilTest.test`

### PR DESCRIPTION
**Pull request by ThugJudy**
### Purpose of this pull request

 The test case [org.apache.seatunnel.api.configuration.util.OptionUtilTest.test](https://github.com/ThugJudy/seatunnel/blob/42344d1a1a3f05f64880a6e989b73de5a5be5723/seatunnel-api/src/test/java/org/apache/seatunnel/api/configuration/util/OptionUtilTest.java#L32) fails due to the non-deterministic behavior of the function 
```
clazz.getDeclaredFields 
```
https://github.com/ThugJudy/seatunnel/blob/b8c313045ea3301f3fa08bc46a9014a4ab9ac66f/seatunnel-api/src/main/java/org/apache/seatunnel/api/configuration/util/OptionUtil.java#L72 which does not guarantee the ordering of elements in the class object.

Due to this, the arrayList of options created does not have a definite order in every run.

I found and confirmed the flaky behavior using an open-source research tool [NonDex](https://github.com/TestingResearchIllinois/NonDex), which shuffles implementations of nondeterminism operations.

### Reproduce
The following command can be used to reproduce assertion failures and verify the fix:
```
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -pl Seatunnel-api -Dtest='org.apache.seatunnel.api.configuration.util.OptionUtilTest#test'
```
### Fix

Sorting the options list based on key ensures that the order of the elements is constant during the test run 

https://github.com/ThugJudy/seatunnel/blob/b8c313045ea3301f3fa08bc46a9014a4ab9ac66f/seatunnel-api/src/test/java/org/apache/seatunnel/api/configuration/util/OptionUtilTest.java#L34

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks for create this PR @ThugJudy . Could you open CI on your fork repository? Please follow the guide https://github.com/apache/seatunnel/pull/5894/checks?check_run_id=18912326036. Thanks.

**Comment by ThugJudy** [comment]
> Thanks for create this PR @ThugJudy . Could you open CI on your fork repository? Please follow the guide https://github.com/apache/seatunnel/pull/5894/checks?check_run_id=18912326036. Thanks.

I opened CI on my forked repo.

**Comment by Hisoka-X** [comment]
The UT not passed. Could you retry failed UT?

**Comment by ThugJudy** [comment]
> The UT not passed. Could you retry failed UT?

I re-ran it and it passed now. Please check.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
