### PR TITLE
[Refactor] [core] Remove the uselss return value from outputBatch of FlinkBatchSink

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This PR removed the useless return value from outputBatch of FlinkBatchSink

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by davidzollo** [comment]
image

please solve conflicts first

**Comment by asdf2014** [comment]
Hi @dailidong, thanks for your comment. The conflicts have been solved, please take a look.

**Comment by yx91490** [comment]
these change may cause api incompatible, what's the benefits of these change?

**Comment by kezhenxu94** [comment]
@asdf2014 please open discussion first, before introducing breaking changes

**Pull request closed without merging**
