### PR TITLE
[Bug][Connector-v2][SeaTunnelSchema]Fix row datatype bug.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
Question:
When the row data type is set in the schema, because the data type is converted to uppercase, the value cannot be obtained and null appears. As shown below, the settings are all lowercase, but they are converted to uppercase and null appears.
schema:
image
Console result:
image

The screenshot after the repair is as follows. The field name and data can be obtained.
image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liugddx** [comment]
can we be case insensitive？ For example, turn to uppercase when setting, and use uppercase when fetching data.

**Comment by lightzhao** [comment]
> can we be case insensitive？ For example, turn to uppercase when setting, and use uppercase when fetching data.

The fix is to be insensitive to case and keep the original in the schema.

**Comment by lightzhao** [comment]
@Hisoka-X @TyrantLucifer @liugddx PTAL.

**Comment by TyrantLucifer** [comment]
Sorry, this pr is duplicated with #4098 , I will close it. Thank you for your contribution.

**Pull request closed without merging**
