### PR TITLE
[Fix][Connector-starrocks] Fix drop column bug for starrocks

### PR DESCRIPTION
**Pull request by dufeng1010**
### Purpose of this pull request
there is a bug about drop column for starrocks. tablePath.getTableName() method doesn't have database name. it will report exception: no database select. so it will be replaced by tablePath.getFullName().

### Does this PR introduce _any_ user-facing change?
`No`

### CODE REVIEW

**Comment by dufeng1010** [comment]
@hailin0 @dailai 
PTAL

**Comment by dailai** [comment]
Please open ci according to https://github.com/apache/seatunnel/pull/8216/checks?check_run_id=33955997464

**Comment by dufeng1010** [comment]
> Please open ci according to https://github.com/apache/seatunnel/pull/8216/checks?check_run_id=33955997464

i enable it

**Review by dailai — DISMISSED** [review]

**Review by Hisoka-X — COMMENTED** [review]
Could you add a test case in https://github.com/apache/seatunnel/blob/06df51bcbbb3294f40ebb5607c70bc031c5175f8/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-starrocks-e2e/src/test/java/org/apache/seatunnel/e2e/connector/starrocks/StarRocksIT.java#L356 ?

**Comment by dufeng1010** [comment]
> Could you add a test case in
> 
> https://github.com/apache/seatunnel/blob/06df51bcbbb3294f40ebb5607c70bc031c5175f8/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-starrocks-e2e/src/test/java/org/apache/seatunnel/e2e/connector/starrocks/StarRocksIT.java#L356
> ?

ok, i will add a test case

**Comment by dufeng1010** [comment]
@dailai @Hisoka-X i have added test case

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Thanks @dufeng1010 !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
