### PR TITLE
[Improvement][Common].gitignore file adds log keyword to ignore.

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of this pull request

.gitignore file adds log keyword to ignore.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Under what circumstances will these files appear? I haven't encountered this situation so far.

**Comment by zhuangchong** [comment]
> Under what circumstances will these files appear? I haven't encountered this situation so far.

The log file will be generated in the seatunnel-server module.

**Comment by Hisoka-X** [comment]
> > Under what circumstances will these files appear? I haven't encountered this situation so far.
> 
> The log file will be generated in the seatunnel-server module.

Got it

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
