### PR TITLE
[bug][seatunnel-api-flink] - fix tableexits not contain TemporaryTabl…

### LINKED ISSUE #1498: [Bug] [seatunnel-api-flink] TableUtil.tableExists cannot check all tables and only Catalogs.tables exclude TemporaryTable
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when i try to read kafka data and print to consule。 it happen an error.

 org.apache.flink.table.api.ValidationException: Temporary table '`default_catalog`.`default_database`.`test`' already exists

in the kafkaTableStream ,getData method use createTemporaryTable to create a temporarytable by the config field result_table_name。
image
but in FlinkStreamExecution.start method。it also   registerResultTable(source, dataStream), TableUtil.tableExists only check the catalogs tables but exclude TemporaryTable. so it happen an error int the last pic.

image

image

image

i suggest use tableEnvironment.listTables() to check all the tables that has been created. include TemporaryTable.

### SeaTunnel Version

2.0.5 latest

### SeaTunnel Config

```conf
env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://localhost:9000/checkpoint"
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
    KafkaTableStream {
          result_table_name = test
          topics = test
          consumer.group.id = "seatunnel#2"
          consumer.bootstrap.servers = "127.0.0.1:9092"
          schema = "{\"uid\":111,\"event_name\":\"aaaa\"}"
          format.type = json
          format.field-delimiter = ","
          format.allow-comments = "true"
          format.ignore-parse-errors = "true"
    }

  # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/source-plugins/Fake
}

transform {


  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/transform-plugins/Sql
}

sink {
  ConsoleSink {}

  # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/flink/configuration/sink-plugins/Console
}
```

### Running Command

```shell
IDEA run LocalFlinkExample.java and change the configflie to kafka_to_console.cnf。
just like SeaTunnel Config above
```

### Error Exception

```log
org.apache.flink.table.api.ValidationException: Temporary table '`default_catalog`.`default_database`.`test`' already exists
```

### Flink or Spark Version

flink 1.13

### Java or Scala Version

jdk8

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tobezhou33**
…e #1498

## Purpose of this pull request

close #1498 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by tobezhou33 — COMMENTED** [review]
fix tableexits not contain TemporaryTables

**Comment by tobezhou33** [comment]
> LGTM

can you help me review the code and if ok approve that

**Comment by Hisoka-X** [comment]
@CalvinKirs LGTM

**Review by CalvinKirs — APPROVED** [review]
Looking forward your next contribution:)

**Pull request merged**
