### PR TITLE
[BugFix] [InfluxDBSource] Resolve invalid SQL in initColumnsIndex method caused by direct QUERY_LIMIT appendage with 'tz' function.

### PR DESCRIPTION
**Pull request by zhengyuan-cn**
recommit RP for [Bug] connector-influxdb module InfluxDBSource class's initColumnsIndex method, sql invalide when sql contains tz function cause by direct append QUERY_LIMIT #4231

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by ic4y** [comment]
@Hisoka-X Can you help figure out why there's no CI/CD?
image

**Comment by ic4y** [comment]
> @Hisoka-X Can you help figure out why there's no CI/CD? image

It's alright now, just close and reopen the PR.

**Comment by ic4y** [comment]
@zhengyuan-cn Please use `mvn spotless:apply` to format the code.

**Comment by zhengyuan-cn** [comment]
> @zhengyuan-cn Please use `mvn spotless:apply` to format the code.

OK, formated

**Comment by hailin0** [comment]
@zhengyuan-cn 

image

**Comment by zhengyuan-cn** [comment]
@Hisoka-X @ic4y @hailin0  all checks have passed,  please review code.

**Review by Hisoka-X — APPROVED** [review]

**Comment by zhengyuan-cn** [comment]
sorry , I accidentally clicked on the review request

**Comment by zhengyuan-cn** [comment]
@Hisoka-X I accidentally clicked on the review request

**Comment by Hisoka-X** [comment]
cc @hailin0

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
