### PR TITLE
[Improvement][Config] Print config in origin order

### LINKED ISSUE #1473: [Improvement][Config] Print config in origin order
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When I execute a job in seatunnel, it will print config in log, this is helpful, but it will change the order of element in config.
For example, config is look like below:
```
env {
  execution.parallelism = 1
}
source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}
transform {
    sql {
      sql = "select name,age from fake"
    }
}
sink {
  ConsoleSink {}
}
```
The print message will be: 
```
env {
  execution.parallelism = 1
}
sink {
  ConsoleSink {}
}
source {
    FakeSourceStream {
      result_table_name = "fake"
      field_name = "name,age"
    }
}
transform {
    sql {
      sql = "select name,age from fake"
    }
}
```
This sometimes make me confused. I find this is caused by when `SimpleConfigObject` execute render method, it will sort the key. See `SimpleConfigObject#render(StringBuilder sb, int indent, boolean atRoot, ConfigRenderOptions options)`
```
Arrays.sort(keys, new SimpleConfigObject.RenderComparator());
```

I want to rewrite this method, this need to copy `SimpleConfigObject` into `seatunnel-config-shade` module.

After test, this can work.

I want to ask if it's necessary to do this, I don't know if other guys think like me.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of this pull request
close #1473 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
you need to add reference to this :https://github.com/apache/incubator-seatunnel/blob/159eb8423c99f21f951abe1a37753bafa206c4dc/LICENSE#L216

**Comment by ruanwenjun** [comment]
> you need to add reference to this :
> 
> https://github.com/apache/incubator-seatunnel/blob/159eb8423c99f21f951abe1a37753bafa206c4dc/LICENSE#L216

Thanks for your reminder, I added this announces, please help to take a look.

**Review by CalvinKirs — APPROVED** [review]
LGTM @BenJFan PTAL,thx

**Comment by Hisoka-X** [comment]
I find many code improve in this PR, It's great to do code improve, If not much we can just use one PR . If code improve change too much, I suggest split it into two PR next time. It's good for code review and PR check. Thanks

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
@CalvinKirs LGTM

**Comment by CalvinKirs** [comment]
> I find many code improve in this PR, It's great to do code improve, If not much we can just use one PR . If code improve change too much, I suggest split it into two PR next time. It's good for code review and PR check. Thanks

thanks

**Pull request merged**
