### PR TITLE
[feature][cdc][postgres] add PostgreSQL CDC

### LINKED ISSUE #3868: [Feature][CDC][Postgres] Support PostgreSQL CDC
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

add PostgreSQL CDC

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ashulin**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by ediconss** [comment]
这个可以现在使用吗，支持同步DDL吗

**Comment by ashulin** [comment]
> 这个可以现在使用吗，支持同步DDL吗

@ediconss 
Currently, DDL synchronization is not supported.
PostgreSQL CDC is still in `beta` status and needs more testing. Feedback on your test results is welcome.

**Review by EricJoy2048 — COMMENTED** [review]
Please add release note to `/release-note.md`

**Review by ic4y — DISMISSED** [review]

**Review by EricJoy2048 — COMMENTED** [review]
Please add OptionRule for this connector.

**Comment by ashulin** [comment]
@ic4y @EricJoy2048 PTAL agen.

**Comment by hailin0** [comment]
check ci error

**Comment by hailin0** [comment]
@ashulin  add e2e module 

reference
https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-cdc-sqlserver-e2e

**Comment by jobmission** [comment]
@hailin0 Hi，  How's it going ？

**Comment by EricJoy2048** [comment]
@hailin0

**Comment by jobmission** [comment]
@ashulin  need this feature

**Comment by chensdraw** [comment]
need postgresql cdc

**Comment by joaopedro02** [comment]
Hi ! do you know how this is going and if  i can help some way ? i really need this feature

**Comment by jobmission** [comment]
Hi, Do we have news about this? :(👍

**Pull request closed without merging**
