### PR TITLE
[Bugfix][Zeta] Fix the checkpoint be blocked with long time

### PR DESCRIPTION
**Pull request by happyboy1024**
### Purpose of this pull request
Fix the checkpoint be blocked with long time. #5694 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]
Thanks @happyboy1024 !

**Comment by Hisoka-X** [comment]
Could you retry the failed CI?

**Comment by happyboy1024** [comment]
> Could you retry the failed CI?
PTAL, I have retried the failed CI.

**Comment by Hisoka-X** [comment]
You missed these.
image

**Comment by happyboy1024** [comment]
> Could you retry the failed CI?



> You missed these. image

Sorry, I'll try again right away

**Comment by Hisoka-X** [comment]
cc @hailin0

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
