### PR TITLE
[Bugfix][RestApi] Fix hazelcast/rest/maps/submit-job return an wrong jobId

### LINKED ISSUE #7146: [Bug] [Module Name] Rest API：hazelcast/rest/maps/submit-job return an wrong jobId
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I send the post api as following parameter format，got the result：
{
  "jobId": 862976196311253000,
  "jobName": "event_test"
}

but I use terminal command $SEATUNNEL_HOME/bin/seatunnel.sh -l got another jobId：862969647010611201 ，and I confirmed the 862969647010611201 is correct because I can stop it by stop job rest api。

I restart the cluster master Server serveral times got the same error ,the bug seems like [Issue 5421](https://github.com/apache/seatunnel/issues/5241), but it closed for it still occur,so I n

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
seatunnel:
  engine:
    history-job-expire-minutes: 1440
    backup-count: 1
    queue-type: blockingqueue
    print-execution-info-interval: 60
    print-job-metrics-info-interval: 60
    slot-service:
      dynamic-slot: true
    event-report-http:
      url: "http://xx.xx.xx.xx:1024/event/report"
      headers:
        Content-Type: application/json
    checkpoint:
      interval: 10000
      timeout: 60000
      storage:
        type: hdfs
        max-retained: 3
        plugin-config:
          storage.type: hdfs
          fs.defaultFS: file:///data/seatunnel/checkpoint_snapshot/
```

### Running Command

```shell
POST /hazelcast/rest/maps/submit-job HTTP/1.1
Host: xx.xx.xx.xx:5801

{
    "env": {
        "job.mode": "batch",
        "job.name": "event_test"
    },
    "source": [
        {
            "plugin_name": "FakeSource",
            "result_table_name": "fake",
            "row.num": 100,
            "schema": {
                "fields": {
                    "name": "string",
                    "age": "int",
                    "card": "int"
                }
            }
        }
    ],
    "transform": [
    ],
    "sink": [
        {
            "plugin_name": "Console",
            "source_table_name": ["fake"]
        }
    ]
}
```

### Error Exception

```log
the rest api return information was different from the command monitor metrics。
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

java v1.8

### Screenshots

image

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
### Purpose of this pull request

close #7146

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Please re-trigger ci

**Comment by Hisoka-X** [comment]
Do not close/reopen PR. It can not retirgger ci.

**Comment by Hisoka-X** [comment]
CI https://github.com/liugddx/seatunnel/actions/runs/9869442304/job/27305697055

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Comment by hailin0** [comment]
Sorry, I forgot to change the commit title when click merged...

**Pull request merged**
