### PR TITLE
[hotfix][Zeta]:the HdfsStorage can not delete checkpoint file #5046

### PR DESCRIPTION
**Pull request by wu-a-ge**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by davidzollo** [comment]
Hi, a good beginning for you to start the contribution. you can use the following method to join the PR with its issue.
this PR closes #5046

**Review by davidzollo — APPROVED** [review]
+1
LGTM

**Review by Carl-Zhou-CN — APPROVED** [review]
+1

**Review by EricJoy2048 — APPROVED** [review]

**Comment by EricJoy2048** [comment]
Let's wait for CI to complete

**Pull request merged**
