### PR TITLE
[Feature][Connector-V2][Doris]Add Doris Source & Sink connector

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request

subtask of https://github.com/apache/incubator-seatunnel/issues/3018
Add Doris Source & Sink connector by JDBC

**Tip：Doris official and Docker hub did not have available docker image for e2e test, so I built Doris image based on Doris 1.1.1 version.**

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by TaoZex** [comment]
@EricJoy2048 @TyrantLucifer @hailin0 @531651225 PTAL

**Review by EricJoy2048 — DISMISSED** [review]

**Review by 531651225 — DISMISSED** [review]
+1

**Comment by morningman** [comment]
We are working on build official Doris runtime image, expected to be released with v1.2.0 soon.
https://doris.apache.org/zh-CN/docs/dev/install/construct-docker/construct-docker-image/

**Comment by TaoZex** [comment]
> v1.2.0

Thank you for your guidance and I am looking forward to v1.2.0.

**Comment by TaoZex** [comment]
> We are working on build official Doris runtime image, expected to be released with v1.2.0 soon. https://doris.apache.org/zh-CN/docs/dev/install/construct-docker/construct-docker-image/

Thank you for your guidance and I am looking forward to v1.2.0.

**Review by EricJoy2048 — APPROVED** [review]

**Comment by TaoZex** [comment]
2000e737566dfd3af457ce73de16e0a

**Review by Hisoka-X — APPROVED** [review]

**Comment by CalvinKirs** [comment]
MySql's IT has been overridden. There is no need to do any IT for any other MySQL protocol, it doesn't make any sense to us.

**Comment by TaoZex** [comment]
> MySql's IT has been overridden. There is no need to do any IT for any other MySQL protocol, it doesn't make any sense to us.

Thanks for your suggestion.

**Comment by gitfortian** [comment]
jdbc on doris read or write,espacilly write operation may cause a version problem,this is not recommond for product env

**Comment by gitfortian** [comment]
jdbc on doris read or write,espacilly write operation may cause a version problem,this is not recommond for product env

**Comment by 531651225** [comment]
> jdbc on doris read or write,espacilly write operation may cause a version problem,this is not recommond for product env

Thank you for your suggestion. The community will optimize this part later and add two connectors
- doris thrift source connector that can connect to be directly to read data concurrently
- doris stream load sink connector

**Pull request merged**
