### PR TITLE
[bug][jdbc][oracle]Fix the Oracle number type mapping problem

### PR DESCRIPTION
**Pull request by zhilinli123**
https://github.com/apache/seatunnel/issues/5204

### CODE REVIEW

**Comment by ic4y** [comment]
Waiting for CI/CD.

**Comment by zhilinli123** [comment]
image
Lack of space again!

**Comment by zhilinli123** [comment]
CI RUN @ic4y @liugddx

**Review by ic4y — APPROVED** [review]

**Review by liugddx — APPROVED** [review]
+1

**Pull request merged**
