### PR TITLE
[Improve][Connector-V2][MongoDB] A BsonInt32 will be convert to a long type

### PR DESCRIPTION
**Pull request by loustler**
### Purpose of this pull request

`BsonInt32`  can be changed to a long type by itself, so we need to support it.

https://github.com/mongodb/mongo-java-driver/blob/525c465df46f791684fccef0a1ba49f72cbba026/bson/src/main/org/bson/BsonInt32.java#L63-L66

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
Package the connector-mongo-2.3.7-2.12.15.jar, place it in a docker image, and complete the MongoDB reading test

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @loustler

**Review by wuchunfu — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Hi @loustler , I thinked about it again, is it possible to add a UT to cover the newly added logic?

**Comment by loustler** [comment]
> Hi @loustler , I thinked about it again, is it possible to add a UT to cover the newly added logic?

Hi @Hisoka-X 

What does a UT means? What a UT stand for?

You mean Unit Test? If it correct, how about a new e2e test case for it?

**Comment by Hisoka-X** [comment]
> > Hi @loustler , I thinked about it again, is it possible to add a UT to cover the newly added logic?
> 
> Hi @Hisoka-X
> 
> What does a UT means? What a UT stand for?
> 
> You mean Unit Test? If it correct, how about a new e2e test case for it?

Sorry. You are right, unit test. But I think add a e2e test case for this small feature is too heavy. We can add some unit test in https://github.com/apache/seatunnel/tree/e31c9c2a9a0804fd24f3ad16ab28fa4fd7ecc2bb/seatunnel-connectors-v2/connector-mongodb/src/test/java/org/apache/seatunnel/connectors/seatunnel/mongodb .
Just like other connectors did. Please refer  https://github.com/apache/seatunnel/blob/e31c9c2a9a0804fd24f3ad16ab28fa4fd7ecc2bb/seatunnel-connectors-v2/connector-elasticsearch/src/test/java/org/apache/seatunnel/connectors/seatunnel/elasticsearch/serialize/ElasticsearchRowSerializerTest.java#L40
or 
https://github.com/apache/seatunnel/blob/e31c9c2a9a0804fd24f3ad16ab28fa4fd7ecc2bb/seatunnel-connectors-v2/connector-paimon/src/test/java/org/apache/seatunnel/connectors/seatunnel/paimon/utils/RowConverterTest.java#L65

**Comment by loustler** [comment]
You're right. It can be too heavy for this case.

I'll added a unit test for it with another PR

**Comment by loustler** [comment]
@Hisoka-X 
I just added it in #7579

**Pull request merged**
