### PR TITLE
[Docs][Connector][Source][jdbc]Change the line boundary store value type to BigDecimal

### PR DESCRIPTION
**Pull request by zhilinli123**
pre_pr:https://github.com/apache/seatunnel/pull/4634

### CODE REVIEW

**Review by TaoZex — APPROVED** [review]
LGTM

**Comment by zhilinli123** [comment]
PTAL: @hailin0 @EricJoy2048 @Hisoka-X

**Comment by ic4y** [comment]
We also need to modify the documentation for databases like postgres and oracle that use the JDBC connector.

**Review by liugddx — DISMISSED** [review]
+1

**Comment by liugddx** [comment]
> +1



> We also need to modify the documentation for databases like postgres and oracle that use the JDBC connector.

Deal with this

**Comment by zhilinli123** [comment]
> +1

done @ic4y @liugddx 
run CI thks

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
