### PR TITLE
[Improve][Connector-V2][iceberg] Refactor iceberg connector e2e test cases

### LINKED ISSUE #3671: [Improve][Connector-V2][IceBerg] Refactor IceBerg connector e2e test cases
sub-task of  #3601

### PR DESCRIPTION
**Pull request by Carl-Zhou-CN**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

close #3671

### CODE REVIEW

**Comment by hailin0** [comment]
please fix ci error

**Comment by Carl-Zhou-CN** [comment]
@TyrantLucifer @hailin0 @Hisoka-X  Please help review

**Comment by Carl-Zhou-CN** [comment]
> please fix ci error

done

**Review by Hisoka-X — COMMENTED** [review]
LGTM

**Review by TyrantLucifer — APPROVED** [review]
+1，thanks for your contribution!

**Comment by TyrantLucifer** [comment]
cc @hailin0 @Hisoka-X

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
