### PR TITLE
[Bug][Transform][Spark] Remove unnecessary row conversion

### LINKED ISSUE #4334: [Bug] [Transform][Spark] dataType convert is error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

image
dataframe row
image
internal Row 

image

as the code above,
`dataframe row  -> internal row -> st-row -> transform map->   transform output st-row -> internal row -> date type convert -> dataframe row `

actually，dataframe row (DataSet<Row>) is different form internalRow，the trait con't convert，internalRow is Binary storage row，dataframeRow is a row base on the scala(java) dataType like st-row
we can implement the convert line: `dataframe row -> st-row -> transform map->  transform output st-row -> dataframe row` 

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
nothing
```

### Running Command

```shell
nothing,in example
```

### Error Exception

```log
convert array and map will exception
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

close #4334

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by laglangyue** [comment]
all of the pr，please see the issue #4334.

**Comment by laglangyue** [comment]
@TyrantLucifer I think this PR should be included in 2.3.1

**Comment by laglangyue** [comment]
@hailin0 Pleasse CR

**Comment by TyrantLucifer** [comment]
cc @rewerma PTAL

**Comment by TyrantLucifer** [comment]
@Hisoka-X PTAL

**Review by Hisoka-X — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
