### PR TITLE
[Feature][Transform2] Add UDF SPI and a example implement for SQL Transform plugin

### PR DESCRIPTION
**Pull request by rewerma**
## Purpose of this pull request

Add UDF SPI and a example implement for SQL Transform plugin

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by TyrantLucifer — DISMISSED** [review]
LGTM, cc @EricJoy2048 @hailin0

**Comment by EricJoy2048** [comment]
That's great. This is a very important feature for SeaTunnel. Thank you for your contribution.

**Review by EricJoy2048 — COMMENTED** [review]
LGTM, Let's wait for the CI complete.

**Review by hailin0 — COMMENTED** [review]
good

**Comment by rewerma** [comment]
> Please add e2e testcase

It's already added in the e2e test config: func_string.conf, `des_decrypt('1234567890', des_encrypt('1234567890', name))`

**Review by TyrantLucifer — APPROVED** [review]
cc @EricJoy2048 @hailin0

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
