### PR TITLE
[Test][Plugin]Add kafka plugins test

### PR DESCRIPTION
**Pull request by wuzhenhua01**
## Purpose of this pull request
Add kafka plugins test https://github.com/apache/incubator-seatunnel/issues/1326

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
Thanks for your path, we have an e2e module, please add IT in this module. And recommand use kafka container defined in testcontainer to create the kafka.

**Comment by CalvinKirs** [comment]
> Thanks for your path, we have an e2e module, please add IT in this module. And recommand use kafka container defined in testcontainer to create the kafka.

Hi, did you can add some docs about e2e, for new contributors, they maybe don't know this.

**Comment by ruanwenjun** [comment]
> > Thanks for your path, we have an e2e module, please add IT in this module. And recommand use kafka container defined in testcontainer to create the kafka.
> 
> Hi, did you can add some docs about e2e, for new contributors, they maybe don't know this.

Here is a brief [introduction](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/contribute-plugin.md#add-e2e-tests-for-your-plugin)

**Comment by wuzhenhua01** [comment]
thx

**Comment by EricJoy2048** [comment]
This pr is closed because it has not responded for too long. If necessary, please reopen it

**Pull request closed without merging**
