### PR TITLE
[Improve][Config] Remove useless config path condition

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
Remove useless config path condition

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by simon824** [comment]
PTAL @leo65535 @wuchunfu thanks.

**Comment by simon824** [comment]
Hi, @wuchunfu ,please take a look at this pr, it's a minor improvement , #1494 will modify the same file `ConfigParser` may cause conflict. Can we merge this pr first?

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by wuchunfu** [comment]
Well done

**Pull request merged**
