### PR TITLE
[Hotfix][ci] Sort dependencies to pass the ci in known-dependencies.txt

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This PR sorted dependencies in known-dependencies.txt to pass the ci

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by davidzollo — APPROVED** [review]
LGTM

**Comment by yx91490** [comment]
It seems no issue related to this pr, can you attach the error log?

**Comment by asdf2014** [comment]
@yx91490 FYI, https://github.com/apache/incubator-seatunnel/runs/5557503348?check_suite_focus=true

**Comment by kezhenxu94** [comment]
@asdf2014 please.... this is not a problem of sorting... did you check the detail or just want a commit only? Did you try in the original PR that this would fix the problem? Did you see the comment 👇 that I've intentionally wrote 

> 2. Unify the `sort` behaviour: here we'll sort them again in case that the behaviour of `sort`
> command in target OS is different from what we used to sort the file `known-dependencies.txt`, i.e. "sort the two file
> using the same command (and default arguments)"

https://github.com/apache/incubator-seatunnel/blob/220c0a61840c870e66891a8c78b3c0ed072c6e80/tools/dependencies/checkLicense.sh#L35-L39

**Pull request merged**
