### PR TITLE
[Feature][connector][kafka] Add timestamp for kafka sink record

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request

Without using timestamp, kafka automatically fills in the sent time：

c4a5da5d868ad2e0bc35d6c9787150c

Use timestamp：

354bf791772056a5b3356ace9d80ace

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
In a real production scenario, it would not have all records with the same timestamp. Hey guys, what do you think about it? cc @EricJoy2048 @CalvinKirs @Hisoka-X @hailin0 @ashulin

**Comment by TaoZex** [comment]
> In a real production scenario, it would not have all records with the same timestamp. Hey guys, what do you think about it? cc @EricJoy2048 @CalvinKirs @Hisoka-X @hailin0 @ashulin

How about support for parsing the value of a column of SeatunnelRow as timestamp? It is common to use timestamp to distinguish between event time and processing time.

**Comment by TyrantLucifer** [comment]
> > In a real production scenario, it would not have all records with the same timestamp. Hey guys, what do you think about it? cc @EricJoy2048 @CalvinKirs @Hisoka-X @hailin0 @ashulin
> 
> How about support for parsing the value of a column of SeatunnelRow as timestamp? It is common to use timestamp to distinguish between event time and processing time.

In my experience, there is no situation where timestamp is specified manually, because the business value of timestamp is different between producer record and data like the time semantics of flink. One is the data generate time, another is the event happen time.

**Comment by Hisoka-X** [comment]
Timestamp just a normal field in SeaTunnel, not any speical at now.

> > In a real production scenario, it would not have all records with the same timestamp. Hey guys, what do you think about it? cc @EricJoy2048 @CalvinKirs @Hisoka-X @hailin0 @ashulin
> 
> How about support for parsing the value of a column of SeatunnelRow as timestamp? It is common to use timestamp to distinguish between event time and processing time.

**Pull request closed without merging**
