### PR TITLE
[Core][Spark] remove duplicate properties,and add OriginalParameters

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

When I submit a task to Spark on YARN with Kerberos, I find some duplicate configuration items. Also, the --queue, --principal, and --keytab properties do not work. Referring to the implementation of Flink, add the original parameter to the Spark command.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by laglangyue** [comment]
@TyrantLucifer @liugddx @hailin0 PTAL

**Review by liugddx — DISMISSED** [review]
+1

**Comment by TyrantLucifer** [comment]
> @TyrantLucifer @liugddx @hailin0 PTAL

I need time to test it in my local env, I remember the redundant parameters is necessary.

**Comment by EricJoy2048** [comment]
> > @TyrantLucifer @liugddx @hailin0 PTAL
> 
> I need time to test it in my local env, I remember the redundant parameters is necessary

@VolodymyrDuke  PTAL.

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
Please  merge dev branch into your branch and trigger CI/CD. BTW, remove master/deploy-mode/name config from command class it's not right, because it has two-layer analysis.

**Comment by laglangyue** [comment]
> Please merge dev branch into your branch and trigger CI/CD. BTW, remove master/deploy-mode/name config from command class it's not right, because it has two-layer analysis.

done,Should some comments be added for this duplicate properties? Could you provide any suggestions?

**Pull request closed without merging**
