### PR TITLE
[Core]ConnectorV2 no longer provides binary packages

### PR DESCRIPTION
**Pull request by EricJoy2048**

### CODE REVIEW

**Comment by Hisoka-X** [comment]
I think we should discuss this in dev mail. So that other developer can know why we do this.

**Comment by EricJoy2048** [comment]
> I think we should discuss this in dev mail. So that other developer can know why we do this.

Yes, I will do it.

**Comment by EricJoy2048** [comment]
The email list :https://lists.apache.org/thread/t1jggqc93ydzjp9cxc8bp8dox30n8z9o

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
