### PR TITLE
[api-draft][Optimize] Optimize module name

### PR DESCRIPTION
**Pull request by EricJoy2048**
image

Module name is too long.

### CODE REVIEW

**Comment by Hisoka-X** [comment]
How about change `seatunnel-connectors-flink`,`seatunnel-connectors-spark`,`seatunnel-connectors-seatunnel` to `flink`,`spark`,`seatunnel`? Because they are `seatunnel-connectors`'s sub module. @ruanwenjun @CalvinKirs

**Comment by CalvinKirs** [comment]
> How about change `seatunnel-connectors-flink`,`seatunnel-connectors-spark`,`seatunnel-connectors-seatunnel` to `flink`,`spark`,`seatunnel`? Because they are `seatunnel-connectors`'s sub module. @ruanwenjun @CalvinKirs

How about we separate out the `seatunnel-connector`? In our later planning, it seems that the separate connector support of `flink` or `spark` will be gradually abandoned.

**Comment by EricJoy2048** [comment]
> > How about change `seatunnel-connectors-flink`,`seatunnel-connectors-spark`,`seatunnel-connectors-seatunnel` to `flink`,`spark`,`seatunnel`? Because they are `seatunnel-connectors`'s sub module. @ruanwenjun @CalvinKirs
> 
> How about we separate out the `seatunnel-connector`? In our later planning, it seems that the separate connector support of `flink` or `spark` will be gradually abandoned.

Do you mean we move flink-connector, spark-connector, seatunnel-connector to the first level module?

**Comment by ashulin** [comment]
Are we only changing `seatunnel-connector` to the first level module?

**Comment by CalvinKirs** [comment]
> Are we only changing `seatunnel-connector` to the first level module?

Just split the new connector into a first-level module. (because it has nothing to do with the engine)

**Comment by EricJoy2048** [comment]
> > Are we only changing `seatunnel-connector` to the first level module?
> 
> Just split the new connector into a first-level module. (because it has nothing to do with the engine)

Ok, what's the name of the first-level module? How about `seatunnel-connectors-v2`?

**Comment by EricJoy2048** [comment]
Another question, what is the module name `seatunnel-connector-seatunnel-clickhouse` will be update to?
What about `connector-clickhouse` ?

**Comment by Hisoka-X** [comment]
> Another question, what is the module name `seatunnel-connector-seatunnel-clickhouse` will be update to? What about `connector-clickhouse` ?

how about `clickhouse-connector`?

**Comment by CalvinKirs** [comment]
> > Another question, what is the module name `seatunnel-connector-seatunnel-clickhouse` will be update to? What about `connector-clickhouse` ?
> 
> how about `clickhouse-connector`?

+1

**Comment by EricJoy2048** [comment]
link https://github.com/apache/incubator-seatunnel/issues/1946

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
