### PR TITLE
[Bug][Spark] Update jackson version to fix LocalSparkExample can't run problem

### LINKED ISSUE #1723: [Bug] [Spark] LocalSparkExample can't run because Jackson version are not uniform
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Can't run LocalSparkExample.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:200)
	at org.apache.spark.metrics.MetricsSystem$$anonfun$registerSinks$1.apply(MetricsSystem.scala:194)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
	at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
	at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
	at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
	at org.apache.spark.metrics.MetricsSystem.registerSinks(MetricsSystem.scala:194)
	at org.apache.spark.metrics.MetricsSystem.start(MetricsSystem.scala:102)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:514)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:91)
	at org.apache.seatunnel.spark.SparkEnvironment.prepare(SparkEnvironment.java:38)
	at org.apache.seatunnel.config.EnvironmentFactory.getEnvironment(EnvironmentFactory.java:61)
	at org.apache.seatunnel.config.ExecutionContext.<init>(ExecutionContext.java:49)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:44)
	at org.apache.seatunnel.command.spark.SparkTaskExecuteCommand.execute(SparkTaskExecuteCommand.java:36)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:48)
	at org.apache.seatunnel.example.spark.LocalSparkExample.main(LocalSparkExample.java:35)
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/util/JacksonFeature
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:655)
	at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	at org.apache.spark.metrics.sink.MetricsServlet.<init>(MetricsServlet.scala:48)
	... 27 more
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.util.JacksonFeature
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 30 more
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
close #1723 
## Purpose of this pull request
Update jackson version to 2.12.6 to fix LocalSparkExample can't run problem

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Good job, you need to change the license of `jackson:2.12.6.1`,`jackson:2.11.0` to `jackson-databind:2.12.6` both in `LICENSE` and `known-dependencies.txt`.

**Comment by ruanwenjun** [comment]
> Good job, you need to change the license of `jackson:2.12.6.1`,`jackson:2.11.0` to `jackson-databind:2.12.6` both in `LICENSE` and `known-dependencies.txt`.

**Comment by ruanwenjun** [comment]
A small tips, when you submit a pr to fix an issue, you can add `close #issueNumber` in the PR description, this can help to link the PR with the target issue, and close the target issue automatic after the PR merged.

**Comment by Hisoka-X** [comment]
> A small tips, when you submit a pr to fix an issue, you can add `close #issueNumber` in the PR description, this can help to link the PR with the target issue, and close the target issue automatic after the PR merged.

Thanks, I forget it.

**Comment by ruanwenjun** [comment]
@BenJFan Don't forget to update `seatunnel-dist/release-docs/LICENSE`

**Review by ruanwenjun — APPROVED** [review]

**Comment by lawulu** [comment]
```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.12.6
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
	at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)

```

There is a new error when I run the LocalSparkExample with File source

I think the ```jackson-module-scala_2.11``` should be updated too

**Comment by Hisoka-X** [comment]
> ```
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.12.6
> 	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
> 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
> 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
> 	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
> 	at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
> ```
> 
> There is a new error when I run the LocalSparkExample with File source
> 
> I think the `jackson-module-scala_2.11` should be updated too

Thinks for provide this message, I will fix it.

**Comment by Hisoka-X** [comment]
> ```
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.12.6
> 	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
> 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
> 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:835)
> 	at org.apache.spark.rdd.RDDOperationScope$.<init>(RDDOperationScope.scala:82)
> 	at org.apache.spark.rdd.RDDOperationScope$.<clinit>(RDDOperationScope.scala)
> ```
> 
> There is a new error when I run the LocalSparkExample with File source
> 
> I think the `jackson-module-scala_2.11` should be updated too

Thinks for provide this message, I will fix it.

**Pull request merged**
