### PR TITLE
[API-DRAFT] [MERGE] Merge api-draft to dev branch

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Merge api-draft to dev branch. Let SeaTunnel new API come to main branch

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi guys, I will merge `api-draft` to `dev` branch, So I create this PR. I resolved some conflict when merge dev to api-draft. The next step is make sure that there are no mistake created when I resolved conflict. Please check that your commit part in `dev` and `api-draft` have already complete and correct merged. If so, I will merge this PR to dev, then we can work on `dev` with new seatunnel api. Thanks!

**Review by ruanwenjun — APPROVED** [review]
LGTM. I find we have moved the new connector to seatunnel-connectors-v2, this is great, so it's better to change all the `new-connector` to `connector-v2`. I find in e2e, the module name is still `new-connector`, we can continue to optimize this after this PR merged.

**Comment by ruanwenjun** [comment]
And there are so many sonor bugs, we may need to solve this.

**Comment by Hisoka-X** [comment]
> And there are so many sonor bugs, we may need to solve this.

Yes, we need solve bug and remove many duplicate code

**Comment by EricJoy2048** [comment]
LGTM, `Hive Sink` Connector is a temporary implementation. I will rewrite this connector after this pr merged.

**Review by CalvinKirs — APPROVED** [review]

**Comment by EricJoy2048** [comment]
> LGTM. I find we have moved the new connector to seatunnel-connectors-v2, this is great, so it's better to change all the `new-connector` to `connector-v2`. I find in e2e, the module name is still `new-connector`, we can continue to optimize this after this PR merged.

Yes, We should unify the names of each module of the new connector. consist of update update `seatunnel-flink-new-connector-e2e` to `seatunnel-flink-v2-e2e` , update `seatunnel-spark-new-connector-e2e` to `seatunnel-spark-v2-e2e`, update `docs/en/new-connector` to `docs/en/connector-v2`.

I will submit a pr to fix this after this pr merged.

**Pull request merged**
