### PR TITLE
[Feature]Rename seatunnel-engine module

### PR DESCRIPTION
**Pull request by kanha-gupta**
issue https://github.com/apache/incubator-seatunnel/issues/3857
previous pr: https://github.com/apache/incubator-seatunnel/pull/4064
## Contribution Checklist

 Renamed Seatunnel engine module to Seatunnel zeta

Module,directory & packages are renamed successfully, Build was successful too.
Tools used: IntelliJ
environment used: Gitpod

Screenshot (157)

Screenshot (156)

## Check list

* [yes ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by kanha-gupta** [comment]
@EricJoy2048 @CalvinKirs Hey ! 
I've completed the task, please review it :)
(Previous PR had to be closed due to different branch checkout)

**Review by ashulin — COMMENTED** [review]
@hailin0 @CalvinKirs @Hisoka-X @ic4y PTAL

**Comment by Hisoka-X** [comment]
Hi, Please resolve conflict after #3939 merged. Because we use spotless now. Thanks

**Comment by hailin0** [comment]
Will you continue to complete this PR?

**Pull request closed without merging**
