### PR TITLE
[improve][connector-v2][sqlserver-cdc]Unified sqlserver TypeUtils type conversion mode

### PR DESCRIPTION
**Pull request by zhilinli123**
…e conversion mode

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Please add some comment.
image

**Comment by zhilinli123** [comment]
image
```
CREATE TABLE full_types (
    id int NOT NULL,
    val_char char(3),
    val_varchar varchar(1000),
    val_text text,
    val_nchar nchar(3),
    val_nvarchar nvarchar(1000),
    val_ntext ntext,
    val_decimal decimal(6,3),
    val_numeric numeric,
    val_float float,
    val_real real,
    val_smallmoney smallmoney,
    val_money money,
    val_bit bit,
    val_tinyint tinyint,
    val_smallint smallint,
    val_int int,
    val_bigint bigint,
    val_date date,
    val_time time,
    val_datetime2 datetime2,
    val_datetime datetime,
    val_smalldatetime smalldatetime,
    val_xml xml
    PRIMARY KEY (id)
);
INSERT INTO full_types VALUES (0,
                               'cč0', 'vcč', 'tč', N'cč', N'vcč', N'tč',
                               1.123, 2, 3.323, 4.323, 5.323, 6.323,
                               1, 22, 333, 4444, 55555,
                               '2018-07-13', '10:23:45', '2018-07-13 11:23:45.34', '2018-07-13 13:23:45.78', '2018-07-13 14:23:45',
                               '<a>b</a>');

``` 1.But from the source code, the flot type is directly converted to SeaTunnel flot type, if not Debug debugging program is difficult to find this problem
2.For some **types** that are not often seen, it is impossible to satisfy, so it is necessary to find the corresponding allusions through string matching   
 Of course, this is my personal opinion, welcome the proposal

**Comment by CheneyYin** [comment]
@zhilinli123 The [datatype mapping](https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#sqlserver-data-types) of debezium does not completely follow SqlServer's original definition.

**Comment by CheneyYin** [comment]
@zhilinli123 please add `datetimeoffset` type into test case.

**Comment by zhilinli123** [comment]
> @zhilinli123 please add `datetimeoffset` type into test case.

The dev fraction has been added. ci has checked

**Comment by Hisoka-X** [comment]
cc @hailin0

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
