### PR TITLE
[Improve][Connector-v2][JdbcSink]Fix max_retries default value.

### PR DESCRIPTION
**Pull request by lightzhao**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Merge dev branch in your branch and try againe. Every pull reqeust before merged should pass all CI/CD.

**Comment by lightzhao** [comment]
> Merge dev branch in your branch and try againe. Every pull reqeust before merged should pass all CI/CD.

Before submitted the pr, I already pulled the branch created by the latest code.

**Comment by lightzhao** [comment]
@TyrantLucifer @Hisoka-X @ic4y @ashulin PTAL.

**Comment by ic4y** [comment]
If the JDBC sink is IS_EXACTLY_ONCE, max_retries=0 is required, so the default value is 0. 
https://github.com/apache/incubator-seatunnel/blob/40699b660cfecb5cffb2da0a94dc1bbd29a19579/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcExactlyOnceSinkWriter.java#L77-L87

You need to think about this.

**Comment by lightzhao** [comment]
> If the JDBC sink is IS_EXACTLY_ONCE, max_retries=0 is required, so the default value is 0.
> 
> https://github.com/apache/incubator-seatunnel/blob/40699b660cfecb5cffb2da0a94dc1bbd29a19579/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcExactlyOnceSinkWriter.java#L77-L87
> 
> You need to think about this.

The default value in the document is 3,  the document is wrong, and the document needs to be modified.
image

**Comment by ic4y** [comment]
> 

@lightzhao You are right, you can submit another pr to fix it

**Comment by lightzhao** [comment]
> > 
> 
> @lightzhao You are right, you can submit another pr to fix it

ok

**Pull request closed without merging**
