### PR TITLE
[Improve][Core/Spark-Starter] Push transform operation from Spark Driver to Executors

### PR DESCRIPTION
**Pull request by CheneyYin**
## Purpose of this pull request

Detail in #4502 
## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by CheneyYin** [comment]
In check of  [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer

**Comment by TyrantLucifer** [comment]
> In check of [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer

This is mainly due to the instability of Github Actions. Don't worry, I will restart it.

**Comment by CheneyYin** [comment]
> > In check of [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer
> 
> This is mainly due to the instability of Github Actions. Don't worry, I will restart it.

Fail to start kafka container.
```shell
2023-04-06T13:52:21.8812864Z 2023-04-06 13:52:21,879 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pulling image layers:  0 pending, 11 downloaded, 11 extracted, (370 MB/370 MB)
2023-04-06T13:52:21.9010677Z 2023-04-06 13:52:21,899 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pull complete. 11 layers, pulled in 30s (downloaded 370 MB at 12 MB/s)
2023-04-06T13:52:21.9065150Z 2023-04-06 13:52:21,904 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Creating container for image: confluentinc/cp-kafka:6.2.1
2023-04-06T13:52:21.9432335Z 2023-04-06 13:52:21,941 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Container confluentinc/cp-kafka:6.2.1 is starting: 3fe756007a7cb122266d3eb520188dfb70a11f37475c0a263ee2b13254693db0
2023-04-06T13:52:21.9689236Z 2023-04-06 13:52:21,950 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink@172.18.0.3:33595] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
2023-04-06T13:52:21.9777381Z 2023-04-06 13:52:21,977 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink-metrics@172.18.0.3:37005] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
2023-04-06T13:52:22.0325355Z 2023-04-06 13:52:22,008 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - Could not start container
2023-04-06T13:52:22.0437471Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint nifty_archimedes (d397bb5d59a08edf0e2447ae10efc285ed674f828a7a24546d2420f889ef377b): Bind for 0.0.0.0:9093 failed: port is already allocated"}
2023-04-06T13:52:22.0442415Z 
2023-04-06T13:52:22.0443549Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0445012Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0448626Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0452628Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0595122Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0596669Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0597720Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0598648Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0599460Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0600215Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
2023-04-06T13:52:22.0600976Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0601730Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T13:52:22.0602277Z 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_362]
2023-04-06T13:52:22.0602782Z 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_362]
2023-04-06T13:52:22.0603278Z 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_362]
2023-04-06T13:52:22.0603875Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
2023-04-06T13:52:22.0604396Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
2023-04-06T13:52:22.0604840Z 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
2023-04-06T13:52:22.0605440Z 2023-04-06 13:52:22,028 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - There are no stdout/stderr logs available for the failed container
2023-04-06T13:52:22.3078415Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.298 s <<< FAILURE! - in org.apache.seatunnel.e2e.connector.kafka.KafkaIT
```

**Comment by CheneyYin** [comment]
> > > In check of [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer
> > 
> > 
> > This is mainly due to the instability of Github Actions. Don't worry, I will restart it.
> 
> Fail to start kafka container.
> 
> ```shell
> 2023-04-06T13:52:21.8812864Z 2023-04-06 13:52:21,879 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pulling image layers:  0 pending, 11 downloaded, 11 extracted, (370 MB/370 MB)
> 2023-04-06T13:52:21.9010677Z 2023-04-06 13:52:21,899 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pull complete. 11 layers, pulled in 30s (downloaded 370 MB at 12 MB/s)
> 2023-04-06T13:52:21.9065150Z 2023-04-06 13:52:21,904 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Creating container for image: confluentinc/cp-kafka:6.2.1
> 2023-04-06T13:52:21.9432335Z 2023-04-06 13:52:21,941 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Container confluentinc/cp-kafka:6.2.1 is starting: 3fe756007a7cb122266d3eb520188dfb70a11f37475c0a263ee2b13254693db0
> 2023-04-06T13:52:21.9689236Z 2023-04-06 13:52:21,950 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink@172.18.0.3:33595] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> 2023-04-06T13:52:21.9777381Z 2023-04-06 13:52:21,977 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink-metrics@172.18.0.3:37005] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> 2023-04-06T13:52:22.0325355Z 2023-04-06 13:52:22,008 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - Could not start container
> 2023-04-06T13:52:22.0437471Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint nifty_archimedes (d397bb5d59a08edf0e2447ae10efc285ed674f828a7a24546d2420f889ef377b): Bind for 0.0.0.0:9093 failed: port is already allocated"}
> 2023-04-06T13:52:22.0442415Z 
> 2023-04-06T13:52:22.0443549Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0445012Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0448626Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0452628Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0595122Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0596669Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0597720Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0598648Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0599460Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0600215Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
> 2023-04-06T13:52:22.0600976Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0601730Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.17.6.jar:1.17.6]
> 2023-04-06T13:52:22.0602277Z 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_362]
> 2023-04-06T13:52:22.0602782Z 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_362]
> 2023-04-06T13:52:22.0603278Z 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_362]
> 2023-04-06T13:52:22.0603875Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
> 2023-04-06T13:52:22.0604396Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
> 2023-04-06T13:52:22.0604840Z 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
> 2023-04-06T13:52:22.0605440Z 2023-04-06 13:52:22,028 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - There are no stdout/stderr logs available for the failed container
> 2023-04-06T13:52:22.3078415Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.298 s <<< FAILURE! - in org.apache.seatunnel.e2e.connector.kafka.KafkaIT
> ```

Fail to start Kafka container again. Please restart it at your leisure. Thanks. @TyrantLucifer

**Comment by TyrantLucifer** [comment]
> > > > In check of [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer
> > > 
> > > 
> > > This is mainly due to the instability of Github Actions. Don't worry, I will restart it.
> > 
> > 
> > Fail to start kafka container.
> > ```shell
> > 2023-04-06T13:52:21.8812864Z 2023-04-06 13:52:21,879 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pulling image layers:  0 pending, 11 downloaded, 11 extracted, (370 MB/370 MB)
> > 2023-04-06T13:52:21.9010677Z 2023-04-06 13:52:21,899 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pull complete. 11 layers, pulled in 30s (downloaded 370 MB at 12 MB/s)
> > 2023-04-06T13:52:21.9065150Z 2023-04-06 13:52:21,904 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Creating container for image: confluentinc/cp-kafka:6.2.1
> > 2023-04-06T13:52:21.9432335Z 2023-04-06 13:52:21,941 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Container confluentinc/cp-kafka:6.2.1 is starting: 3fe756007a7cb122266d3eb520188dfb70a11f37475c0a263ee2b13254693db0
> > 2023-04-06T13:52:21.9689236Z 2023-04-06 13:52:21,950 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink@172.18.0.3:33595] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> > 2023-04-06T13:52:21.9777381Z 2023-04-06 13:52:21,977 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink-metrics@172.18.0.3:37005] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> > 2023-04-06T13:52:22.0325355Z 2023-04-06 13:52:22,008 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - Could not start container
> > 2023-04-06T13:52:22.0437471Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint nifty_archimedes (d397bb5d59a08edf0e2447ae10efc285ed674f828a7a24546d2420f889ef377b): Bind for 0.0.0.0:9093 failed: port is already allocated"}
> > 2023-04-06T13:52:22.0442415Z 
> > 2023-04-06T13:52:22.0443549Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0445012Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0448626Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0452628Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0595122Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0596669Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0597720Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0598648Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0599460Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0600215Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
> > 2023-04-06T13:52:22.0600976Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0601730Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.17.6.jar:1.17.6]
> > 2023-04-06T13:52:22.0602277Z 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0602782Z 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0603278Z 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0603875Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0604396Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0604840Z 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
> > 2023-04-06T13:52:22.0605440Z 2023-04-06 13:52:22,028 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - There are no stdout/stderr logs available for the failed container
> > 2023-04-06T13:52:22.3078415Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.298 s <<< FAILURE! - in org.apache.seatunnel.e2e.connector.kafka.KafkaIT
> > ```
> 
> Fail to start Kafka container again. Please restart it at your leisure. Thanks. @TyrantLucifer

image

It seems like the changes involve port usage. Did this code modification involve any ports?

**Comment by TyrantLucifer** [comment]
> > > > > In check of [ed0d13b](https://github.com/apache/incubator-seatunnel/pull/4503/commits/ed0d13b63c076af705ee7b4edde2f2d1ca8c4a54), why did fail to run `actions/checkout@v2` in `all-connectors-it-4` ? In the other case, `actions/checkout@v2` run successfully. @TyrantLucifer
> > > > 
> > > > 
> > > > This is mainly due to the instability of Github Actions. Don't worry, I will restart it.
> > > 
> > > 
> > > Fail to start kafka container.
> > > ```shell
> > > 2023-04-06T13:52:21.8812864Z 2023-04-06 13:52:21,879 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pulling image layers:  0 pending, 11 downloaded, 11 extracted, (370 MB/370 MB)
> > > 2023-04-06T13:52:21.9010677Z 2023-04-06 13:52:21,899 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Pull complete. 11 layers, pulled in 30s (downloaded 370 MB at 12 MB/s)
> > > 2023-04-06T13:52:21.9065150Z 2023-04-06 13:52:21,904 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Creating container for image: confluentinc/cp-kafka:6.2.1
> > > 2023-04-06T13:52:21.9432335Z 2023-04-06 13:52:21,941 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Container confluentinc/cp-kafka:6.2.1 is starting: 3fe756007a7cb122266d3eb520188dfb70a11f37475c0a263ee2b13254693db0
> > > 2023-04-06T13:52:21.9689236Z 2023-04-06 13:52:21,950 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink@172.18.0.3:33595] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> > > 2023-04-06T13:52:21.9777381Z 2023-04-06 13:52:21,977 INFO  🐳 [tyrantlucifer/flink:1.13.6-scala_2.11_hadoop27:jobmanager] - STDOUT: 2023-04-06 13:52:21,930 WARN  akka.remote.ReliableDeliverySupervisor                       [] - Association with remote system [akka.tcp://flink-metrics@172.18.0.3:37005] has failed, address is now gated for [50] ms. Reason: [Disassociated] 
> > > 2023-04-06T13:52:22.0325355Z 2023-04-06 13:52:22,008 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - Could not start container
> > > 2023-04-06T13:52:22.0437471Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint nifty_archimedes (d397bb5d59a08edf0e2447ae10efc285ed674f828a7a24546d2420f889ef377b): Bind for 0.0.0.0:9093 failed: port is already allocated"}
> > > 2023-04-06T13:52:22.0442415Z 
> > > 2023-04-06T13:52:22.0443549Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0445012Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0448626Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0452628Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0595122Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0596669Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0597720Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0598648Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0599460Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0600215Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
> > > 2023-04-06T13:52:22.0600976Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0601730Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.17.6.jar:1.17.6]
> > > 2023-04-06T13:52:22.0602277Z 	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:719) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0602782Z 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:701) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0603278Z 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0603875Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0604396Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0604840Z 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
> > > 2023-04-06T13:52:22.0605440Z 2023-04-06 13:52:22,028 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - There are no stdout/stderr logs available for the failed container
> > > 2023-04-06T13:52:22.3078415Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 31.298 s <<< FAILURE! - in org.apache.seatunnel.e2e.connector.kafka.KafkaIT
> > > ```
> > 
> > 
> > Fail to start Kafka container again. Please restart it at your leisure. Thanks. @TyrantLucifer
> 
> image
> 
> It seems like the changes involve port usage. Did this code modification involve any ports?

#4520 maybe fix this problem, I will try merge the newest dev branch into your branch.

**Review by TyrantLucifer — APPROVED** [review]

**Comment by TyrantLucifer** [comment]
LGTM, thank you for your contribution.

**Review by hailin0 — APPROVED** [review]

**Comment by CheneyYin** [comment]
> LGTM, thank you for your contribution.

Thanks for your encouragement

**Comment by TyrantLucifer** [comment]
> > LGTM, thank you for your contribution.
> 
> Thanks for your encouragement

Could you please add my WeChat **tyrantlucifer** and I invite you into developer group？

**Comment by CheneyYin** [comment]
> > > LGTM, thank you for your contribution.
> > 
> > 
> > Thanks for your encouragement
> 
> Could you please add my WeChat **tyrantlucifer** and I invite you into developer group？

How to get your WeChat?

**Comment by CheneyYin** [comment]
> > > LGTM, thank you for your contribution.
> > 
> > 
> > Thanks for your encouragement
> 
> Could you please add my WeChat **tyrantlucifer** and I invite you into developer group？

I searched one user *Lonely Patient* about tyrantlucifer on wechat. Is *Lonely Patient* you?

**Comment by TyrantLucifer** [comment]
> > > > LGTM, thank you for your contribution.
> > > 
> > > 
> > > Thanks for your encouragement
> > 
> > 
> > Could you please add my WeChat **tyrantlucifer** and I invite you into developer group？
> 
> I searched one user _Lonely Patient_ about tyrantlucifer on wechat. Is _Lonely Patient_ you?

yup, it's me.

**Pull request merged**
