### PR TITLE
[Feature] [ci] Increase the building time of ci action

### PR DESCRIPTION
**Pull request by xleoken**
## Purpose of this pull request

We use `30min` as the timeout of the building, it seems not enough for building.

image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by xleoken** [comment]
cc @CalvinKirs

**Review by CalvinKirs — COMMENTED** [review]
Usually it should be done in 30 minutes.

**Comment by xleoken** [comment]
> Usually it should be done in 30 minutes.

Actions always been canceled recently, we can wait and see if this happens to anyone else.

**Comment by xleoken** [comment]
@CalvinKirs, seems the network of the github action is unstable.

image

_Originally posted by @leo65535 in https://github.com/apache/incubator-seatunnel/issues/1205#issuecomment-1032290488_

**Comment by asdf2014** [comment]
Hi @leo65535, thanks for your contribution. Under normal situation, our CI jobs should be completed in about 10 minutes. If it can't be completed in half an hour, it will still fail eventually. But by default it takes 10 hours, due to the Job of Github Action actually has a default timeout parameter, which is 10 hours. We changed the timeout to half an hour, which can release resources in time.

So if we want to fundamentally solve this problem, we can split the big Job into multiple small Jobs based on the module to run in parallel, and add a re-run mechanism to avoid rerunning all of them after one failure. What do you think 😄

**Comment by xleoken** [comment]
> Hi @leo65535, thanks for your contribution. Under normal situation, our CI jobs should be completed in about 10 minutes. If it can't be completed in half an hour, it will still fail eventually. But by default it takes 10 hours, due to the Job of Github Action actually has a default timeout parameter, which is 10 hours. We changed the timeout to half an hour, which can release resources in time.
> 
> So if we want to fundamentally solve this problem, we can split the big Job into multiple small Jobs based on the module to run in parallel, and add a re-run mechanism to avoid rerunning all of them after one failure. What do you think 😄

Thanks @CalvinKirs @asdf2014, we can add a re-run mechanism firstly.

**Comment by xleoken** [comment]
Seems the actions are unstable recently.

image

**Comment by CalvinKirs** [comment]
I will close it. At the same time, for me, the rerun mechanism is an issue that needs to be discussed, how to rerun, and under what circumstances it is necessary to rerun. This involves the issue of resources.

**Comment by xleoken** [comment]
> I will close it. At the same time, for me, the rerun mechanism is an issue that needs to be discussed, how to rerun, and under what circumstances it is necessary to rerun. This involves the issue of resources.

Make sense. 💯

**Pull request closed without merging**
