### PR TITLE
[Feature][docs]  Add development FAQ document.

### PR DESCRIPTION
**Pull request by mosence**
Add document development/FAQ.md to help more developer build own dev environment.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by wuchunfu** [comment]
@mosence The [faq](https://github.com/apache/incubator-seatunnel-website/blob/main/faq/faq.md) file already exists, I think you can add the content here, thanks

**Comment by mosence** [comment]
@wuchunfu 
Does the FAQ need to distinguish between users and developers?
I see a lot of development environment problems.

In [https://seatunnel.apache.org/docs/developement/NewLicenseGuide](https://seatunnel.apache.org/docs/developement/NewLicenseGuide)

Only license related guidelines, I'd bean sure I cannot found how I build my local develop environment.

**Comment by CalvinKirs** [comment]
> @wuchunfu Does the FAQ need to distinguish between users and developers? I see a lot of development environment problems.
> 
> In https://seatunnel.apache.org/docs/developement/NewLicenseGuide
> 
> Only license related guidelines, I'd bean sure I cannot found how I build my local develop environment.

A better way is to move the website's FAQ here.

**Comment by wuchunfu** [comment]
> > @wuchunfu Does the FAQ need to distinguish between users and developers? I see a lot of development environment problems.
> > In https://seatunnel.apache.org/docs/developement/NewLicenseGuide
> > Only license related guidelines, I'd bean sure I cannot found how I build my local develop environment.
> 
> A better way is to move the website's FAQ here.

Thanks for the reminder, I'll finish this later

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
Well done, and looking forward to your next contribution.

**Pull request merged**
