### PR TITLE
[Improve][e2e] Unified e2e IT for DaMengDB

### PR DESCRIPTION
**Pull request by ashulin**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by liugddx — CHANGES_REQUESTED** [review]
Assertions.assertEquals(0, extraCommands.getExitCode(), extraCommands.getStderr());

**Comment by hailin0** [comment]
remove JdbcDmdbIT from flink e2e?

https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-flink-connector-v2-e2e/connector-jdbc-flink-e2e/src/test/java/org/apache/seatunnel/e2e/flink/v2/jdbc/JdbcDmdbIT.java



error link:https://github.com/apache/incubator-seatunnel/actions/runs/3149010813/jobs/5120196613#step:4:23007

**Comment by liugddx** [comment]
> remove JdbcDmdbIT from flink e2e?
> 
> https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-flink-connector-v2-e2e/connector-jdbc-flink-e2e/src/test/java/org/apache/seatunnel/e2e/flink/v2/jdbc/JdbcDmdbIT.java
> 
> error link:https://github.com/apache/incubator-seatunnel/actions/runs/3149010813/jobs/5120196613#step:4:23007

how to fix the @slf4j error. move e2e or change the code?

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Comment by Hisoka-X** [comment]
> > remove JdbcDmdbIT from flink e2e?
> > https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-e2e/seatunnel-flink-connector-v2-e2e/connector-jdbc-flink-e2e/src/test/java/org/apache/seatunnel/e2e/flink/v2/jdbc/JdbcDmdbIT.java
> > error link:https://github.com/apache/incubator-seatunnel/actions/runs/3149010813/jobs/5120196613#step:4:23007
> 
> how to fix the @slf4j error. move e2e or change the code?

Slf4j work fine. After remove `JdbcDmdbIT::executeExtraCommands`.

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
