### PR TITLE
[Test][Spark] Make sure the value in spark not be reused.

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
We should make sure Spark InternalRow value not be reused after invoke `SeaTunnelSinkWriter::write` method. This is a bug long time ago (seem like already be fixed in dev branch). Please refer #5091 . I removed clone row in jdbc sink in https://github.com/apache/seatunnel/pull/5620/files#diff-7038c93a00208c28985861ea0b2ea931d05c2b1eb3b4acd8291b92cf59ce0707L80. So I think we should add test case to avoid regression about reused InternalRow in Spark.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add new test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @ic4y

**Review by ruanwenjun — COMMENTED** [review]
Please update https://github.com/apache/seatunnel/tree/dev/seatunnel-dist/release-docs.

By the way, why we need to upgrade the dependency version in this PR.

**Comment by Hisoka-X** [comment]
> Please update https://github.com/apache/seatunnel/tree/dev/seatunnel-dist/release-docs.

Done

> By the way, why we need to upgrade the dependency version in this PR.

Our spark/flink dependency scala version not same. It should be 2.12. Also update common-lang3 and jackson version so that the test case can be execute. (Too old version cause Spark app can not start)

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
