### PR TITLE
[Improve][[Jdbc]sink sql support custom field.(#6515)

### PR DESCRIPTION
**Pull request by rtyuy**
### Purpose of this pull request

[Improve][[Jdbc]sink sql support custom field.(#6515)

When the sink columns do not contain all source columns, you can use a named parameter like this:
```sql
 query = "INSERT INTO INVER_WORK_ORDER2 (col1,col2,  col3,col4) VALUES(:WORK_ORDER_ID,:WORK_ORDER_NAME,  :CREATE_STAFF_ID,:CREATE_STAFF_NAME)"
```
 Make sure that all named parameters exist in the source column.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks  @rtyuy ! Please add test case. Also please open ci on your fork repository. 
image

**Comment by rtyuy** [comment]
> Thanks @rtyuy ! Please add test case. Also please open ci on your fork repository. image

add test

**Comment by Hisoka-X** [comment]
Thanks @rtyuy for update! Could you add this feature into the jdbc doc? https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/sink/Jdbc.md

**Comment by Hisoka-X** [comment]
cc @EricJoy2048 @hailin0

**Comment by hailin0** [comment]
@rtyuy 

cc @Hisoka-X 

Why not use transform to filter fields?

**Comment by hailin0** [comment]
> Thanks @rtyuy for update! Could you add this feature into the jdbc doc? https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/sink/Jdbc.md

cc @rtyuy

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
