### PR TITLE
[Improve] Use the correct code tag for Java doc

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This patch uses the correct code tag for Java doc instead of `<code/>`

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by CalvinKirs** [comment]
hi, can you check it uniformly?

**Comment by asdf2014** [comment]
Hi @CalvinKirs, yep, I've confirmed, this is all

**Review by xleoken — APPROVED** [review]
LGTM, btw, we can leave these minor changes to the new guys, also cc @CalvinKirs

**Comment by asdf2014** [comment]
Hi @leo65535 , thanks for your comment, I believe the https://github.com/apache/incubator-seatunnel/issues/785 is enough to keep newer busy, right 😅

**Pull request merged**
