### PR TITLE
[Improve][Clickhouse-V2] Clickhouse Support Geo type

### PR DESCRIPTION
**Pull request by FWLamb**
## Purpose of this pull request
Clickhouse Sink Support write Geo type https://github.com/apache/incubator-seatunnel/issues/3101
Clickhouse Source also  Support Geo type.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by FWLamb** [comment]
Maybe we need to change the version of _**clickhouse-jdbc**_ in the future. https://github.com/ClickHouse/clickhouse-jdbc/issues/1112

**Comment by Hisoka-X** [comment]
Please use e2e to test these type.

**Comment by FWLamb** [comment]
Point and Ring data types passed the e2e test. Polygon and MultiPolygon cannot be used temporarily because of a bug in clickhouse jdbc. Please track https://github.com/ClickHouse/clickhouse-jdbc/issues/1112

**Comment by Hisoka-X** [comment]
Like this https://github.com/apache/incubator-seatunnel/pull/3047/files#diff-74e1e7a8b81b6f0f364b14de8bf7f0957bcea7d13f1ce23c61be650844fc2ecd , you should turn on clickhouse e2e test.

**Comment by FWLamb** [comment]
@Hisoka-X PTAL

**Review by Hisoka-X — DISMISSED** [review]
LGTM

**Review by EricJoy2048 — COMMENTED** [review]
Please add the improve to Clickhouse Connector doc and add the `changed log` reference https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Redis.md#next-version

**Comment by FWLamb** [comment]
> Please add the improve to Clickhouse Connector doc and add the `changed log` reference https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/source/Redis.md#next-version

all right

**Comment by FWLamb** [comment]
https://github.com/apache/incubator-seatunnel/pull/3067
https://github.com/apache/incubator-seatunnel/pull/3047
@EricJoy2048 Do the above two PRs also need to be added?

**Comment by Hisoka-X** [comment]
> #3067 #3047 @EricJoy2048 Do the above two PRs also need to be added?

Yes, add it together.

**Comment by FWLamb** [comment]
> > #3067 #3047 @EricJoy2048 Do the above two PRs also need to be added?
> 
> Yes, add it together.

all right

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
