### PR TITLE
[Bug] [Connector] Clickhouse sink can not work correctly when use multiple hosts

### PR DESCRIPTION
**Pull request by xpleaf**
## Purpose of this pull request

close (#1808)

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Please update the doc, and update this logic in Flink clickhouse connector :).

**Comment by xpleaf** [comment]
> Please update the doc, and update this logic in Flink clickhouse connector :).

ok, how about I submit the next issue to add the multiple hosts support in Flink Engine ClickHouse sink if possible? As in the previous version, **the existing doc**([version 2.1.0](https://seatunnel.apache.org/docs/2.1.0/spark/configuration/sink-plugins/Clickhouse#host-string), [version 2.1.1](https://seatunnel.apache.org/docs/2.1.1/connector/sink/Clickhouse#host-string) ) had mentitioned Spark Engine ClickHouse sink supports multiple hosts config, and this commit just fix the existing bug when use this multiple host config.

**Comment by ruanwenjun** [comment]
> > Please update the doc, and update this logic in Flink clickhouse connector :).
> 
> ok, how about I submit the next issue to add the multiple hosts support in Flink Engine ClickHouse sink if possible? As in the previous version, **the existing doc**([version 2.1.0](https://seatunnel.apache.org/docs/2.1.0/spark/configuration/sink-plugins/Clickhouse#host-string), [version 2.1.1](https://seatunnel.apache.org/docs/2.1.1/connector/sink/Clickhouse#host-string) ) had mentitioned Spark Engine ClickHouse sink supports multiple hosts config, and this commit just fix the existing bug when use this multiple host config.

It's OK to me.

**Comment by xpleaf** [comment]
> > > Please update the doc, and update this logic in Flink clickhouse connector :).
> > 
> > 
> > ok, how about I submit the next issue to add the multiple hosts support in Flink Engine ClickHouse sink if possible? As in the previous version, **the existing doc**([version 2.1.0](https://seatunnel.apache.org/docs/2.1.0/spark/configuration/sink-plugins/Clickhouse#host-string), [version 2.1.1](https://seatunnel.apache.org/docs/2.1.1/connector/sink/Clickhouse#host-string) ) had mentitioned Spark Engine ClickHouse sink supports multiple hosts config, and this commit just fix the existing bug when use this multiple host config.
> 
> It's OK to me.

Ok, I will continue to follow up this matter through other issues.

**Comment by Hisoka-X** [comment]
Can this change work on ClickhouseFile sink?

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Comment by xpleaf** [comment]
> Can this change work on ClickhouseFile sink?

Yes, it works and doesn't affect existing functionality. In fact, both split_mode and ClickHouseFile were added without considering the multiple hosts configuration. In the case of ClickHouseFile, I did some research and there is still a lot of logical room for improvement. In the future, I will optimize ClickHouseFile more to make it more reasonable.

**Comment by Hisoka-X** [comment]
> > Can this change work on ClickhouseFile sink?
> 
> Yes, it works and doesn't affect existing functionality. In fact, both split_mode and ClickHouseFile were added without considering the multiple hosts configuration. In the case of ClickHouseFile, I did some research and there is still a lot of logical room for improvement. In the future, I will optimize ClickHouseFile more to make it more reasonable.

Thanks for contribute, looking forward your improvement on ClickhouseFile.

**Review by ruanwenjun — APPROVED** [review]

**Pull request merged**
