### PR TITLE
 [WIP][Improve][kafkaSink]delete `partition` parameter 

### LINKED ISSUE #4498: [Bug] sink kafka error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

seatunnel sink kafka error

### SeaTunnel Version

2.3.1

### SeaTunnel Config

```conf
env {
    execution.parallelism = 1
}

source {
    Jdbc {
        url = "jdbc:mysql://node04:3306/db_test?serverTimezone=GMT%2b8"
        driver = "com.mysql.cj.jdbc.Driver"
        connection_check_timeout_sec = 100
        user = "hadoop",
        password = "hadoop",
        query = "select province_id,area_code from ads_order_by_province"
    }
}

transform {
}

sink {
  kafka {
      topic = "wyn_test"
      bootstrap.servers = "192.168.0.101:9092"
      partition = 1
      format = json
      kafka.request.timeout.ms = 6000
      semantics = EXACTLY_ONCE
      kafka.config = {
        acks = "all"
        request.timeout.ms = 6000
        buffer.memory = 33554432
      }
  }
}
```

### Running Command

```shell
seatunnel.sh --config /opt/soft/seatunnel/seatunnel-2.3.1/job/seatunnel_mysql_kafka.conf -e local
```

### Error Exception

```log
2023-04-04 16:29:20,764 INFO  org.apache.kafka.clients.Metadata                            [] - [Producer clientId=producer-SeaTunnel0614-1, transactionalId=SeaTunnel0614-1] Resetting the last seen epoch of partition wyn_test-0 to 0 since the associated topicId changed from null to nS8WxqKRQEipTsX003--bA
2023-04-04 16:30:20,760 INFO  org.apache.kafka.clients.producer.internals.TransactionManager [] - [Producer clientId=producer-SeaTunnel0614-1, transactionalId=SeaTunnel0614-1] Transiting to abortable error state due to org.apache.kafka.common.errors.TimeoutException: Topic wyn_test not present in metadata after 60000 ms.
2023-04-04 16:31:20,761 INFO  org.apache.kafka.clients.producer.internals.TransactionManager [] - [Producer clientId=producer-SeaTunnel0614-1, transactionalId=SeaTunnel0614-1] Transiting to abortable error state due to org.apache.kafka.common.errors.TimeoutException: Topic wyn_test not present in metadata after 60000 ms.
2023-04-04 16:32:20,763 INFO  org.apache.kafka.clients.producer.internals.TransactionManager [] - [Producer clientId=producer-SeaTunnel0614-1, transactionalId=SeaTunnel0614-1] Transiting to abortable error state due to org.apache.kafka.common.errors.TimeoutException: Topic wyn_test not present in metadata after 60000 ms.
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Purpose of this pull request
 close #4498

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.

**Comment by MonsterChenzhuo** [comment]
> The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.

图片
Do you have any better suggestions on the code?

**Comment by MonsterChenzhuo** [comment]
> The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.

https://github.com/apache/incubator-seatunnel/issues/4498
This is a problem encountered by the user. When he specified a non-existent partition due to a mistake, the program did not report an error or feedback any valid information, which made the user not know what caused it.

**Comment by lightzhao** [comment]
> > The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.
> 
> #4498 This is a problem encountered by the user. When he specified a non-existent partition due to a mistake, the program did not report an error or feedback any valid information, which made the user not know what caused it.

If there is no get topic metadata within 1 minute, it means that there is a problem with the configuration of the topic or the network. I personally think this prompt is clear.

**Comment by MonsterChenzhuo** [comment]
> > > The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.
> > 
> > 
> > #4498 This is a problem encountered by the user. When he specified a non-existent partition due to a mistake, the program did not report an error or feedback any valid information, which made the user not know what caused it.
> 
> If there is no get topic metadata within 1 minute, it means that there is a problem with the configuration of the topic or the network. I personally think this prompt is clear.

There are too many possible problems with kafka. Is it a cluster problem or a configuration problem? It is all possible.

**Comment by MonsterChenzhuo** [comment]
> > > The introduction of AdminClient requires additional permissions to ensure that it can be executed, and the validity of the topic should be ensured before configuration and use.
> > 
> > 
> > #4498 This is a problem encountered by the user. When he specified a non-existent partition due to a mistake, the program did not report an error or feedback any valid information, which made the user not know what caused it.
> 
> If there is no get topic metadata within 1 minute, it means that there is a problem with the configuration of the topic or the network. I personally think this prompt is clear.

The current situation is not that users can't perceive that something is wrong, but precisely that they have found the problem but don't know how to solve it, reflecting the fact that they can't pinpoint the problem, they know that something is wrong but don't know what it is, and they have never been able to solve it.


The need for my pr is probably threefold:
    1. using AdminClient should not be a very tangled point. On the seatunnel kafka source side, it is heavily used to support fragmentation logic.
    2.kafka has too many possible problems. Is it a cluster issue or a configuration issue? It's all possible.
    3.Users raise "issues" while giving feedback in the community, and no one is able to fix them for a long time because there are so few errors and it is hard to say what is causing them. This prompted me to read the logic of his implementation and submit the current pr.

**Comment by hailin0** [comment]
This feature is a maintenance burden for us, and I don't know if it is really useful, can we consider removing `partition `?

@MonsterChenzhuo @lightzhao

**Comment by MonsterChenzhuo** [comment]
@lightzhao  I think we can actually remove this parameter, because I really think there is no scenario to send data to the specified partition, so I am going to send its email to discuss, let's continue communication on email

**Comment by lightzhao** [comment]
> @lightzhao I think we can actually remove this parameter, because I really think there is no scenario to send data to the specified partition, so I am going to send its email to discuss, let's continue communication on email

Some scenarios may also be used, such as CDC-mysql to kafka, in order to ensure global consistency, specify to send to a partition, can initiate a discussion. @MonsterChenzhuo @hailin0

**Comment by hailin0** [comment]
> > @lightzhao I think we can actually remove this parameter, because I really think there is no scenario to send data to the specified partition, so I am going to send its email to discuss, let's continue communication on email
> 
> Some scenarios may also be used, such as CDC-mysql to kafka, in order to ensure global consistency, specify to send to a partition, can initiate a discussion. @MonsterChenzhuo @hailin0

@lightzhao 


Did you mean message key routing? 
https://seatunnel.apache.org/docs/2.3.1/connector-v2/sink/Kafka#partition_key_fields-array

**Comment by lightzhao** [comment]
> Did you mean message key routing?

It is not the message routing of the key, but the routing of the specified partition.

**Comment by MonsterChenzhuo** [comment]
@lightzhao 

> > Did you mean message key routing?
> 
> It is not the message routing of the key, but the routing of the specified partition.


> > @lightzhao I think we can actually remove this parameter, because I really think there is no scenario to send data to the specified partition, so I am going to send its email to discuss, let's continue communication on email
> 
> Some scenarios may also be used, such as CDC-mysql to kafka, in order to ensure global consistency, specify to send to a partition, can initiate a discussion. @MonsterChenzhuo @hailin0
+1 A scenario comes to mind: to ensure the orderliness of the messages, the messages are typed under a specified partition

**Comment by hailin0** [comment]
> > Did you mean message key routing?
> 
> It is not the message routing of the key, but the routing of the specified partition.

@lightzhao 

CDC usually only needs to send the data of the same table or the same primary key to the same partition, but does not care which partition.

It can be done by `partition_key_fields`

**Comment by lightzhao** [comment]
> CDC usually only needs to send the data of the same table or the same primary key to the same partition, but does not care which partition.

This is only locally ordered. If the order is guaranteed globally, all assignments need to be sent to a partition.

**Comment by hailin0** [comment]
> > CDC usually only needs to send the data of the same table or the same primary key to the same partition, but does not care which partition.
> 
> This is only locally ordered. If the order is guaranteed globally, all assignments need to be sent to a partition.

Can't create a topic with only one partition?

**Comment by lightzhao** [comment]
> > > CDC usually only needs to send the data of the same table or the same primary key to the same partition, but does not care which partition.
> > 
> > 
> > This is only locally ordered. If the order is guaranteed globally, all assignments need to be sent to a partition.
> 
> Can't create a topic with only one partition?

yes, it is possible.

**Comment by MonsterChenzhuo** [comment]
@hailin0 @lightzhao  If there's nothing else wrong, I'll change the title of this issue to remove the `partition` parameter to recomplete the pr

**Pull request closed without merging**
