### PR TITLE
[Bug] [maven] skip executing license-maven-plugin's download-licenses goal by default

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This PR speeded up CI.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by asdf2014** [comment]
Before:
image

After:
image

**Comment by CalvinKirs** [comment]
For me, I think the default parameters are actually enough, and it should be noted that we need to compare with a real case. If you compare the data of the previous pass, you will find that there is no improvement.

**Comment by asdf2014** [comment]
> For me, I think the default parameters are actually enough, and it should be noted that we need to compare with a real case. If you compare the data of the previous pass, you will find that there is no improvement.

@CalvinKirs Okay, thanks for your comment.

**Comment by CalvinKirs** [comment]
> > For me, I think the default parameters are actually enough, and it should be noted that we need to compare with a real case. If you compare the data of the previous pass, you will find that there is no improvement.
> 
> @CalvinKirs Okay, thanks for your comment.

I looked at some failed CIs (CodeQL) and it looks like the timeout canceled during the execution of the analysis report，as the amount of code in the project increases, the 30m timeout of the default CODEQL may no longer be satisfied (perhaps you can create an issue to discuss how to do it better, simply expanding the timeout is not the best way).

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
