### PR TITLE
[INFRA] Fix `notify_test_workflow.yml` not stable

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
We have 31 job to run in fork repository, but github default fetch job size is 30 (ref https://docs.github.com/en/rest/checks/runs?apiVersion=2022-11-28#list-check-runs-for-a-git-reference--parameters). So sometimes we can't get job `Run / License header`. This PR add `per_page` param to 100. So we can get all job in one request. To fix `TypeError: Cannot read properties of undefined (reading 'head_sha')`

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
tested in https://github.com/Hisoka-X/seatunnel-fork/actions/runs/6234419437/job/16921563255?pr=19

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @ruanwenjun @EricJoy2048

**Comment by Hisoka-X** [comment]
The failed CI is what this PR want to fix.

**Review by hailin0 — APPROVED** [review]

**Review by liugddx — APPROVED** [review]

**Comment by Hisoka-X** [comment]
The commit msg from this PR not right.
image
It used my commit msg in fork repository not PR title.
We should pay a attention about this when we merged PR in the future. cc @liugddx

**Comment by liugddx** [comment]
> future

Oh, I overlooked that, I'll pay attention.

**Pull request merged**
