### PR TITLE
[Improve][Connector-V2][MongoDB] Refactor MongoDB connector e2e test …

### LINKED ISSUE #3607: [Improve][Connector-V2][MongoDB] Refactor MongoDB connector e2e test cases
sub-task of #3601

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Purpose of this pull request
close #3607

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Review by ashulin — COMMENTED** [review]
Can you remove `connector-mongodb-spark-e2e` and `connector-mongodb-flink-e2e` module together?

**Comment by MonsterChenzhuo** [comment]
> Can you remove `connector-mongodb-spark-e2e` and `connector-mongodb-flink-e2e` module together?

@ashulin Thanks for your review,I have made the changes.

**Review by TyrantLucifer — DISMISSED** [review]
LGTM

**Comment by TyrantLucifer** [comment]
cc @ashulin @EricJoy2048 @hailin0

**Review by TaoZex — DISMISSED** [review]
+1

**Comment by Hisoka-X** [comment]
Please check the data already write into mongoDB

**Comment by TyrantLucifer** [comment]
> Please check the data already write into mongoDB

Assert sink maybe a best choice.

**Comment by MonsterChenzhuo** [comment]
@TyrantLucifer @Hisoka-X  Sorry, I didn't understand how I need to make the changes

**Comment by MonsterChenzhuo** [comment]
@Hisoka-X   Thanks for your review,I have made the changes.

**Review by Hisoka-X — APPROVED** [review]

**Review by TaoZex — APPROVED** [review]
+1

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
