### PR TITLE
[Feature] [docs] docs document structure  Elasticsearch-flink.md

### PR DESCRIPTION
**Pull request by jj551**
…k-plugin/

Signed-off-by: kodalien <kkodalien@gmail.com>

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by xleoken — APPROVED** [review]

**Comment by CalvinKirs** [comment]
Where is the corresponding English document?

**Comment by xleoken** [comment]
hi @Kodalien, some actions have been cancelled due to timeout, you need to trigger them.

**Comment by Kodalien** [comment]
> Where is the corresponding English document?

https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/flink/configuration/sink-plugins/Elasticsearch.md

**Comment by jj551** [comment]
> 对应的英文文件在哪里？

https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/flink/configuration/sink-plugins/Elasticsearch.md

**Comment by jj551** [comment]
> 嗨@Kodalien，由于超时，某些操作已被取消，您需要触发它们。



> hi @Kodalien, some actions have been cancelled due to timeout, you need to trigger them.

how to tirgger 😅 ! @leo65535 always tangled

**Comment by xleoken** [comment]
try
```
git commit --allow-empty -m 'trigger rebuild' 
git push
```

**Comment by jj551** [comment]
> try
> 
> ```
> git commit --allow-empty -m 'trigger rebuild' 
> git push
> ```

ok

**Comment by CalvinKirs** [comment]
There are some dead links that need to be fixed, you can check the log

**Comment by CalvinKirs** [comment]
If the CI has an obvious error, not a timeout. You should go through the logs to fix it instead of doing pointless rerun.

**Comment by CalvinKirs** [comment]
Since there is no update for a long time, I will close this PR, if there is any follow-up response, please leave a message.

**Pull request closed without merging**
