### PR TITLE
[Bug][Core] Let the SparkCommandArgs do not split the variable value with comma

### PR DESCRIPTION
**Pull request by LinZhaoguan**
## Purpose of this pull request

This pull request optimized the parsing rules for custom command line variables, users can pass the variable value with comma, and variable values will not be divided by comma.
#2514 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]
LGTM

**Comment by Hisoka-X** [comment]
By the way, the code style need be fixed. You can use checkstyle file in `tools/checkstyle` to make sure your code meet the requirements

**Comment by LinZhaoguan** [comment]
> By the way, the code style need be fixed. You can use checkstyle file in `tools/checkstyle` to make sure your code meet the requirements

I have finished the modification, please review the code again.Thanks a lot. @Hisoka-X

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
