### PR TITLE
[Fix][Connector-V2] Fixed iceberg sink can not handle uppercase fields

### PR DESCRIPTION
**Pull request by sunxiaojian**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — APPROVED** [review]

**Review by Hisoka-X — CHANGES_REQUESTED** [review]
Could you add a test case?

**Comment by sunxiaojian** [comment]
> Could you add a test case?

This is useless code, existing case can cover it

**Review by Hisoka-X — DISMISSED** [review]

**Comment by hailin0** [comment]
Is there any need to modify here?
https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113

**Comment by sunxiaojian** [comment]
> Is there any need to modify here? https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113

@hailin0 Is your code old?

**Comment by sunxiaojian** [comment]
> Is there any need to modify here? https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113

@hailin0 Don't need it

**Comment by hailin0** [comment]
> > Is there any need to modify here? https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113
> 
> @hailin0 Don't need it

@sunxiaojian 

Why is it needed here?

https://github.com/apache/seatunnel/blob/4a2e27291c4d16d36ff4edaf70a67242ff78e9bf/seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/data/RowConverter.java#L221

**Comment by sunxiaojian** [comment]
> > > Is there any need to modify here? https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113
> > 
> > 
> > @hailin0 Don't need it
> 
> @sunxiaojian
> 
> Why is it needed here?
> 
> https://github.com/apache/seatunnel/blob/4a2e27291c4d16d36ff4edaf70a67242ff78e9bf/seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/data/RowConverter.java#L221

Primary Keys are passed through configuration, so why not config them correctly ?

**Comment by sunxiaojian** [comment]
> > > Is there any need to modify here? https://github.com/apache/seatunnel/pull/7656/files#diff-75806c45c1b7d159a39a4442309885784ee116d510a2f147b347ab26db03e2b4R113
> > 
> > 
> > @hailin0 Don't need it
> 
> @sunxiaojian
> 
> Why is it needed here?
> 
> https://github.com/apache/seatunnel/blob/4a2e27291c4d16d36ff4edaf70a67242ff78e9bf/seatunnel-connectors-v2/connector-iceberg/src/main/java/org/apache/seatunnel/connectors/seatunnel/iceberg/data/RowConverter.java#L221

 In order to be consistent with the case_Sensitive configuration,  I have already added it,  but the primary keys can be overridden through configuration.

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
