### PR TITLE
[Bug][spark-connector-v2-example] fix the bug of no class found. (#2191)

### LINKED ISSUE #2191: [Bug] [spark-connector-v2-example] No class found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Running spark-connector-v2-example in idea develop environment failed, the error as the following image:

image

I think it maybe the dependencies in pom has some problems, I try to add the 3.0.X  `janino` dependency in pom and fixed it.

In whole project I see it had been added the janino dependency in pom, but the version is `3.1.X`, maybe the `org/codehaus/janino/InternalCompilerException` not be contained in `3.1.X`

In my option, we should add the `janino` 3.0.X dependency in pom.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
none
```

### Running Command

```shell
none
```

### Error Exception

```log
Caused by: java.lang.ClassNotFoundException: org.codehaus.janino.InternalCompilerException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 47 more
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TyrantLucifer**
* add the janino dependency in pom

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]
LGTM

**Review by CalvinKirs — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
But you should fix dependency license error

**Comment by TyrantLucifer** [comment]
> But you should fix dependency license error

fixed, please review.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
