### PR TITLE
[Engine][PhysicalPlan] Add code from LogicalDag to PhysicalPlan

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Add code from LogicalDag to PhysicalPlan
Related issue: #2269.(Don't close, also need to add task related logic)

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by EricJoy2048** [comment]
I see you use `Vertex` in PhysicalPlan. I don't think the vertices of logical plan and physical plan are the same. In physical plan physical vertices need to express y a vertex that can be executed or further converted into a task. If the value of the parallelism attribute of a logical vertex is 4, there should be at least 4 physical vertices in the corresponding physical plan, and each physical vertex should contain an index attribute to express the index of the physical vertex.

**Comment by Hisoka-X** [comment]
> I see you use `Vertex` in PhysicalPlan. I don't think the vertices of logical plan and physical plan are the same. In physical plan physical vertices need to express y a vertex that can be executed or further converted into a task. If the value of the parallelism attribute of a logical vertex is 4, there should be at least 4 physical vertices in the corresponding physical plan, and each physical vertex should contain an index attribute to express the index of the physical vertex.

Hi, `Vertex` already be converted to task list with `ActionWrapper` in the physical plan. There no Vertex in the physical plan.

**Review by EricJoy2048 — COMMENTED** [review]
I don't found the `TaskGroup` in this pr. It is different from the design.

**Comment by Hisoka-X** [comment]
> I don't found the `TaskGroup` in this pr. It is different from the design.

I will fix this in next PR, with jar url together.

**Review by EricJoy2048 — APPROVED** [review]
+1 LGTM cc @CalvinKirs

**Comment by EricJoy2048** [comment]
LGTM

**Pull request merged**
