### PR TITLE
[Doc] [connectors-v2] [Http Source] Http source option key poll_interval_ms different in source code

### PR DESCRIPTION
**Pull request by Zhouwen-CN**
https://github.com/apache/seatunnel/issues/5429

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liunaijie** [comment]
i think it's better update the document not the code.

**Comment by zhilinli123** [comment]
> i think it's better update the document not the code.
+1

**Comment by Zhouwen-CN** [comment]
@liunaijie 
@zhilinli123 
PTAL

**Comment by zhilinli123** [comment]
Good , wait CI

**Review by EricJoy2048 — APPROVED** [review]

**Review by zhilinli123 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
