### PR TITLE
[INFRA] Move CI to running on fork repository container

### LINKED ISSUE #4759: [CI][Improve] Move ci to running on fork repository container
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Currently we run ci on the apache container, but the committer needs to manually trigger the startup and also need to manually retry. We can let ci run on the contributor's fork repository to avoid the problems mentioned above. Please refer to the ci configuration of Apache Spark: https://github.com/apache/spark/tree/master/.github/workflows .

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request

Move most of CI test case run on fork repository.

The idea refer https://github.com/apache/spark/pull/32092 and https://github.com/apache/spark/pull/32193

Please check https://github.com/Hisoka-X/seatunnel-fork/pull/17 and https://github.com/Hisoka-X/seatunnel-fork/pull/17/checks?check_run_id=16812802586 to see what is look like.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @EricJoy2048 @ruanwenjun

**Comment by ruanwenjun** [comment]
@Hisoka-X After this PR is merged the ci will run at contributor's repo?

**Comment by Hisoka-X** [comment]
> @Hisoka-X After this PR is merged the ci will run at contributor's repo?

Yep

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
