### PR TITLE
[Improve][E2E] Reactor jdbc e2e with new api.

### PR DESCRIPTION
**Pull request by FlechazoW**
## Purpose of this pull request

Reactor jdbc e2e with new api.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Good job, let's waiting CICD.

**Comment by liugddx** [comment]
Great pr. Please fix the problem of ci.

**Comment by FlechazoW** [comment]
All test has passed. cc, please @TyrantLucifer @liugddx

**Comment by FlechazoW** [comment]
Miss some cases, WIP.

**Review by liugddx — COMMENTED** [review]
@ic4y PTAL

**Review by TyrantLucifer — DISMISSED** [review]
cc @EricJoy2048 @Hisoka-X

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by FlechazoW** [comment]
PTAL. @TyrantLucifer @EricJoy2048

**Review by TyrantLucifer — APPROVED** [review]
cc @EricJoy2048

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
