### PR TITLE
[Feature] [Connector-V2] Support connector-file-obs

### PR DESCRIPTION
**Pull request by linsen55**
This pull request adds connector-file-obs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi @linsen55 , please follow the guide to open ci on your fork repository. https://github.com/apache/seatunnel/pull/6000/checks?check_run_id=19560285027

**Review by hailin0 — COMMENTED** [review]
add module name into this file
https://github.com/apache/seatunnel/blob/dev/config/plugin_config

**Review by hailin0 — COMMENTED** [review]
Please add e2e testcase & running screenshots

https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-cos-e2e/src/test

**Comment by hailin0** [comment]
Same as https://github.com/apache/seatunnel/pull/4578/

**Pull request closed without merging**
