### PR TITLE
Decide table format using outputFormat in HiveSinkConfig

### PR DESCRIPTION
**Pull request by zhaomin1423**
## Purpose of this pull request

When writing hive table, it use outputFormat to handle data. So, we can using outputFormat property to decide the file format of hive table.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi @EricJoy2048 PTAL.

**Comment by CalvinKirs** [comment]
Hi, please resolved conflicts files

**Comment by zhaomin1423** [comment]
> Hi, please resolved conflicts files

fixed.

**Comment by EricJoy2048** [comment]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
