### PR TITLE
[Improve][Core][spark-starter] Fix the command line generated by SparkStarter

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request

The command line generated by SparkStarter is redundant.

use config:
d7f34e9afd5123c56443f48bc26cc83

1cdade20f522243f294d98da2efa995

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
Did you have tested? From reading the code, I found that you are removing the above parameter, not the below. The parameters above are for spark, and the parameters below are for seatunnel.
image

**Comment by TyrantLucifer** [comment]
> Did you have tested? From reading the code, I found that you are removing the above parameter, not the below. The parameters above are for spark, and the parameters below are for seatunnel. image

+1, please do the integration test. CC @TaoZex

**Comment by TaoZex** [comment]
> > Did you have tested? From reading the code, I found that you are removing the above parameter, not the below. The parameters above are for spark, and the parameters below are for seatunnel. image
> 
> +1, please do the integration test. CC @TaoZex

Thanks for the review.This image is the first submission of the code. Next, I will do the integration test.

**Comment by TaoZex** [comment]
@CalvinKirs @Hisoka-X PTAL

The command line generated by SparkStarter is redundant.

use config:
d7f34e9afd5123c56443f48bc26cc83

1cdade20f522243f294d98da2efa995

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
