### PR TITLE
[Feature][Spark] Support SeaTunnel Time Type.

### PR DESCRIPTION
**Pull request by CheneyYin**
## Purpose of this pull request
TODO #5187 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by CheneyYin** [comment]
image
Need to execute CI again? @liugddx @TyrantLucifer

**Comment by CheneyYin** [comment]
image
Please execute CI again. @liugddx Thanks

**Comment by TyrantLucifer** [comment]
Good pr!

**Comment by hailin0** [comment]
good pr

**Comment by CheneyYin** [comment]
@hailin0 @liugddx PTAL

**Comment by CheneyYin** [comment]
waiting for:
- #5595

**Comment by CheneyYin** [comment]
Waiting for:
- #5647

**Comment by hailin0** [comment]
LGTM

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Thanks @CheneyYin !

**Pull request merged**
