### PR TITLE
[Connector] [Dependency] Add Miss Dependency Cassandra And Change Kudu Plugin Name

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
1. Add Miss Dependency Cassandra
2. Fix PluginIdentifier equals method problem

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  3. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  4. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Review by hailin0 — DISMISSED** [review]

**Review by hailin0 — DISMISSED** [review]

**Review by CalvinKirs — DISMISSED** [review]
It is recommended to change to `seatunnel.source.Kudu = connector-kudu`
It's better to be consistent.

**Review by TyrantLucifer — DISMISSED** [review]
+1

**Comment by TyrantLucifer** [comment]
> It is recommended to change to `seatunnel.source.Kudu = connector-kudu` It's better to be consistent.

Aggre with you.

**Comment by Hisoka-X** [comment]
> It is recommended to change to `seatunnel.source.Kudu = connector-kudu` It's better to be consistent.

Done

**Review by ashulin — APPROVED** [review]
LGTM

**Review by hailin0 — APPROVED** [review]
please update the title

**Comment by Hisoka-X** [comment]
> please update the title

Done

**Pull request merged**
