### PR TITLE
[Improve][e2e] support run multiple job at same time

### LINKED ISSUE #6548: [Feature][e2e] support run mutiple job onetime
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now in e2e we can't run jobs serial, the pervious jobs result can't used in next job.
Will support serial run mutiple job, then 
1. we can use fake source to generate data rather than build data manually
2. we can test mutiple connector in same time, like fake to mysql, mysql to hive, hive to clickhosue etc.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request
close #6548

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
Why do you need this feature?

**Comment by hailin0** [comment]
reference

https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-fake-e2e/src/test/java/org/apache/seatunnel/e2e/connector/fake/FakeIT.java#L35

**Comment by liunaijie** [comment]
> Why do you need this feature?

For now, if we run jobs within mutiple command, like this
```
container.executeJob("conf1");   
container.executeJob("conf2")
```
the con2 can't use conf1  sink result as source.

like conf1 sink is the local file, conf2 want read from this local file rather than generate data manually.

**Comment by hailin0** [comment]
reference

https://github.com/apache/seatunnel/blob/216efb764b31e5d3078036219e73c30fad16aea5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-local-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/local/LocalFileIT.java#L118-L119

**Comment by liunaijie** [comment]
> reference
> 
> https://github.com/apache/seatunnel/blob/216efb764b31e5d3078036219e73c30fad16aea5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-local-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/local/LocalFileIT.java#L118-L119

the `local_excel_to_assert.conf` is read from `/seatunnel/read/excel`, this folder data is copy to container not generated by `fake_to_local_excel.conf`

https://github.com/apache/seatunnel/blob/216efb764b31e5d3078036219e73c30fad16aea5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-local-e2e/src/test/resources/excel/local_excel_to_assert.conf#L32
https://github.com/apache/seatunnel/blob/216efb764b31e5d3078036219e73c30fad16aea5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-file-local-e2e/src/test/java/org/apache/seatunnel/e2e/connector/file/local/LocalFileIT.java#L87

**Comment by hailin0** [comment]
The data path of the sink can be used for the next task to read

**Comment by hailin0** [comment]
For example, kafka sink data is stored in kafka server, the next submitted task is read from kafka server and does not require any special processing.

**Pull request closed without merging**
