### PR TITLE
[Bug][Flink-connector-v2-e2e] Replace the flink docker name

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

#2291 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Please resolve ci problem first

**Comment by TyrantLucifer** [comment]
> Please resolve ci problem first

I found the flink-connector-e2e has some problems in log file, but I didn't change anything in flink-connector-e2e, could you please restart CI progress?

**Comment by Hisoka-X** [comment]
> > Please resolve ci problem first
> 
> I found the flink-connector-e2e has some problems in log file, but I didn't change anything in flink-connector-e2e, could you please restart CI progress?

Done

**Comment by Hisoka-X** [comment]
@CalvinKirs @ruanwenjun Hi Please check this.

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
