### PR TITLE
[FIX][E2E]Modify the OceanBase test case to the latest imageChange image

### LINKED ISSUE #7451: [FIX][E2E]Modify the OceanBase test case to the latest image
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

For testcontainers-java, you need to use oceanbase version 1.20.1 or newer，Oceanbase-client is updated to the latest version，oceanbase test image version use latest tag
### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by xxsc0529**
### Purpose of this pull request
For testcontainers-java, you need to use oceanbase version 1.20.1 or newer，Oceanbase-client is updated to the latest version，oceanbase test image version use latest tag
Close #7451

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?
github workflow test is successful

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Please update https://github.com/apache/seatunnel/blob/8ee129d20f3f200ba04d02623469e3f3008b8c96/seatunnel-connectors-v2/connector-jdbc/pom.xml#L52

**Review by Hisoka-X — COMMENTED** [review]
Please update doc too.
image

**Comment by xxsc0529** [comment]
> Please update doc too. image

Sorry, I've made changes to the global search

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
