### PR TITLE
[Feature][JDBC、CDC] Support Short and Byte Type in spliter

### PR DESCRIPTION
**Pull request by ic4y**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
LGTM
 cc @Hisoka-X

**Comment by Hisoka-X** [comment]
shall we add test case?

**Review by lightzhao — APPROVED** [review]

**Comment by EricJoy2048** [comment]
Please add e2e for this pr.

**Comment by ic4y** [comment]
> Please add e2e for this pr.

It is currently covered by the following tests

https://github.com/apache/seatunnel/blob/7c62b61eed8a87422058ed70a79e6dcf3a950b31/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-7/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcMysqlSplitIT.java#L381-L392

**Comment by Hisoka-X** [comment]
> > Please add e2e for this pr.
> 
> It is currently covered by the following tests
> 
> https://github.com/apache/seatunnel/blob/7c62b61eed8a87422058ed70a79e6dcf3a950b31/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-part-7/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/JdbcMysqlSplitIT.java#L381-L392

I believe current test case never reach the new code. Because the test case without this PR already passed.

**Review by liugddx — APPROVED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
