### PR TITLE
[Imporve][Connector-V2][Elasticsearch] Parameter verification for connector V2 elasticsearch sink

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request

The connector V2 elasticsearch sink has no config check, so it is checked.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
Can you add e2e test for this feature?

reference
https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e

**Comment by TaoZex** [comment]
> 

This e2e issue has been assigned: https://github.com/apache/incubator-seatunnel/issues/2819

**Comment by EricJoy2048** [comment]
Hi, @TaoZex  please update pr title to `[Imporve][Connector-V2][Elasticsearch] Parameter verification for connector V2 elasticsearch sink `

**Comment by TaoZex** [comment]
> Hi, @TaoZex please update pr title to `[Imporve][Connector-V2][Elasticsearch] Parameter verification for connector V2 elasticsearch sink `

Thanks，I have updated the pr title.

**Review by EricJoy2048 — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
