### PR TITLE
[INFRA] Update PR template to add test and user change question

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
Update PR template to make sure contributer to check the change with test covered and it is or not change user-facing change. It will look like this PR msg.

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Unnecessary.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by EricJoy2048** [comment]
Good Job, Can you add some well done tests or document links for contributors to refer to directly?

**Comment by Hisoka-X** [comment]
> Good Job, Can you add some well done tests or document links for contributors to refer to directly?

Code changes involve many different modules, and providing test cases of a certain module may mislead the contributer. The document too, and the all doc link already in `check list`.

**Comment by EricJoy2048** [comment]
> > Good Job, Can you add some well done tests or document links for contributors to refer to directly?
> 
> Code changes involve many different modules, and providing test cases of a certain module may mislead the contributer. The document too, and the all doc link already in `check list`.

I found most of the PRs don't check the data type and value in Sink Connector e2e. And many new connector document did not use our latest document specification, but instead used the old one.

**Comment by Hisoka-X** [comment]
> > > Good Job, Can you add some well done tests or document links for contributors to refer to directly?
> > 
> > 
> > Code changes involve many different modules, and providing test cases of a certain module may mislead the contributer. The document too, and the all doc link already in `check list`.
> 
> I found most of the PRs don't check the data type and value in Sink Connector e2e. And many new connector document did not use our latest document specification, but instead used the old one.

Sounds reasonable, I add some comment for this.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by liugddx — APPROVED** [review]

**Pull request merged**
