### PR TITLE
[imporve] fix mistake and duplicate dependency

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

 #2409 fix mistake and duplicate dependency

Mainly to fix a spelling error `ackson mapper-`，because I am doing the e2e test, so I fix a little of duplicate dependencies  so that  it might be cleaner.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
LGTM.  Please check licenses

**Review by CalvinKirs — DISMISSED** [review]

**Comment by CalvinKirs** [comment]
https://github.com/apache/incubator-seatunnel/blob/65a92f24965ac17d1adec3dc475206ede5dcd7b4/tools/dependencies/known-dependencies.txt#L308
https://github.com/apache/incubator-seatunnel/blob/65a92f24965ac17d1adec3dc475206ede5dcd7b4/seatunnel-dist/release-docs/LICENSE#L879

Just delete these two lines

**Comment by laglangyue** [comment]
> https://github.com/apache/incubator-seatunnel/blob/65a92f24965ac17d1adec3dc475206ede5dcd7b4/tools/dependencies/known-dependencies.txt#L308
> 
> 
> https://github.com/apache/incubator-seatunnel/blob/65a92f24965ac17d1adec3dc475206ede5dcd7b4/seatunnel-dist/release-docs/LICENSE#L879
> 
> Just delete these two lines

done

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
Thanks for your contribution and looking forward to your next contribution;)

**Pull request merged**
