### PR TITLE
[Bug] [connector-spark-console] NoSuchMethodError org.apache.seatunnel.spark.Config

### PR DESCRIPTION
**Pull request by liujinhui1994**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by liujinhui1994** [comment]
Details are here https://github.com/apache/incubator-seatunnel/issues/1595

**Comment by ruanwenjun** [comment]
@liujinhui1994 Thanks for your patch, you have found the cause, but this bug will also exist in other module.
I have submitted a PR #1592 to solve these kinds of problems.

**Comment by liujinhui1994** [comment]
@ruanwenjun  That's great,  close this  PR

**Comment by ruanwenjun** [comment]
> @ruanwenjun That's great, close this PR

Thanks.

**Comment by liujinhui1994** [comment]
It will be resolved here, so close

**Pull request closed without merging**
