### PR TITLE
[Bug] Fix OrcWriteStrategy/ParquetWriteStrategy doesn't login with kerberos

### PR DESCRIPTION
**Pull request by ruanwenjun**
### Purpose of this pull request

When we use ORC/Parquet with kerberos in file connector or hive connector. we will get kerberos unauthorization exception, this is caused by we didn't login with kerberos in OrcWriteStrategy/ParquetWriteStrategy.

### Does this PR introduce _any_ user-facing change?
No

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [X] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Shall we add test case?

**Comment by ruanwenjun** [comment]
> Shall we add test case?

Yes， but this case will rely on Kerberos, I didn't find how to add UT.

**Review by EricJoy2048 — APPROVED** [review]

**Comment by hailin0** [comment]
> > Shall we add test case?
> 
> Yes， but this case will rely on Kerberos, I didn't find how to add UT.

It's okay, we can create an issue and complete it in the future to add test cases

**Comment by ruanwenjun** [comment]
> > > Shall we add test case?
> > 
> > 
> > Yes， but this case will rely on Kerberos, I didn't find how to add UT.
> 
> It's okay, we can create an issue and complete it in the future to add test cases

I create issue https://github.com/apache/seatunnel/issues/6664 for this.

**Comment by hailin0** [comment]
link [paimon sink kerberos](https://github.com/apache/seatunnel/pull/6585/files#diff-2610a87f1a5958d9d73ecffae4f29e860c4327191ab3c623609ed67560cfc6e7R106)

**Review by hailin0 — APPROVED** [review]
LGTM

**Pull request merged**
