### PR TITLE
[Bug] [Writer] hdfs temp folder has not been cleaned up #4321

### LINKED ISSUE #4321: [Bug] [Writer] hdfs temp folder has not been cleaned up
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

After file moved, transaction folder  and sub-folder is not cleaned

image
image
image

```
23/03/09 14:14:25 INFO util.FileSystemUtils: begin rename file oldName :[/tmp/seatunnel/seatunnel/886ea402fb7c4ad08f3495eac49f14f5/fef7457165/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1/NON_PARTITION/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1_20230309_0.orc] to newName :[<mypath>/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1_20230309_0.orc]
23/03/09 14:14:25 INFO util.FileSystemUtils: rename file :[/tmp/seatunnel/seatunnel/886ea402fb7c4ad08f3495eac49f14f5/fef7457165/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1/NON_PARTITION/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1_20230309_0.orc] to [<mypath>/T_886ea402fb7c4ad08f3495eac49f14f5_fef7457165_13_1_20230309_0.orc] finish
```

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
env {
  job.mode = "BATCH"
  parallelism = 4
  spark.app.name = "user"
  spark.driver.cores = 1
  spark.driver.memory = 1g
  spark.executor.instances = 2
  spark.executor.cores = 5
  spark.executor.memory = 5g
}

source { 
    JDBC {
      result_table_name = "t1"
      url = "jdbc:oracle:thin:@"
      driver = "oracle.jdbc.OracleDriver"
      user = ""
      password = ""
      query = ${basic_sql}
    }
}


sink {
  HdfsFile {
    source_table_name = "t1"
    file_name_expression = "${transactionId}_${now}"
    fs.defaultFS = "hdfs://xx"
    hdfs_site_path = "/xx/hdfs-site.xml"
    path = ${out_parent_dir}
    file_format = "orc"
    filename_time_format = "yyyyMMdd"
    is_enable_transaction = true
    batch_size = 50000000
  }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-connector-v2.sh \
--master yarn \
--deploy-mode client \
--config  config/xx.conf \
-i date=20230307
```

### Error Exception

```log
nothing
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhilinli123**
## Check list
close: https://github.com/apache/incubator-seatunnel/issues/4321
* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by lightzhao — CHANGES_REQUESTED** [review]
This is just to delete the directory when commit, and the directory should still exist after the task exits.

**Comment by zhilinli123** [comment]
> This is just to delete the directory when commit, and the directory should still exist after the task exits.

You mean it shouldn't be deleted?

**Comment by lightzhao** [comment]
> > This is just to delete the directory when commit, and the directory should still exist after the task exits.
> 
> You mean it shouldn't be deleted?

It is only deleted after the commit end, and will be created later, but the directory still exists after the task end, and the temporary directory should be deleted when the task exit.

**Comment by zhilinli123** [comment]
> commit结束后才删除



> > > 这只是提交时删除目录，任务退出后目录应还存在。
> > 
> > 
> > 你的意思是它不应该被删除？
> 
> commit结合后才删除，面会创建，但任务结合后该目录仍然存在，任务退出时应删除该临时目录。



> > > This is just to delete the directory when commit, and the directory should still exist after the task exits.
> > 
> > 
> > You mean it shouldn't be deleted?
> 
> It is only deleted after the commit end, and will be created later, but the directory still exists after the task end, and the temporary directory should be deleted when the task exit.

Can you give me some implementation hints I don't see how to tell if this task is over

**Comment by zhilinli123** [comment]
> > > This is just to delete the directory when commit, and the directory should still exist after the task exits.
> > 
> > 
> > You mean it shouldn't be deleted?
> 
> It is only deleted after the commit end, and will be created later, but the directory still exists after the task end, and the temporary directory should be deleted when the task exit.

Can you give me some implementation hints I don't see how to tell if this task is over

**Comment by lightzhao** [comment]
> > > > This is just to delete the directory when commit, and the directory should still exist after the task exits.
> > > 
> > > 
> > > You mean it shouldn't be deleted?
> > 
> > 
> > It is only deleted after the commit end, and will be created later, but the directory still exists after the task end, and the temporary directory should be deleted when the task exit.
> 
> Can you give me some implementation hints I don't see how to tell if this task is over

I tried to delete the temporary directory in the close method before, but found that the close method will not be called when the task exits. The engine use flink. I have not thought of a better way to solve it.

**Comment by TyrantLucifer** [comment]
This pull request not make sense, I will close it, if you have any other questions, please reopen it and send an email to dev@seatunnel.apache.org

**Pull request closed without merging**
