### PR TITLE
[Bug][Connector-v2][HdfsSink]Fix data loss caused by commit failure.

### PR DESCRIPTION
**Pull request by lightzhao**
When the hdfs fails, the commit of the hdfs sink should fail, otherwise the data will be lost.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
When commit operation failed, it will collect these failed transaction information and try to recommit those at engine point (This is the design idea). So it's meaningless to do these things. I will close this PR, if you have any other suggestion or problem, please reopen it. Thanks!

**Comment by lightzhao** [comment]
> When commit operation failed, it will collect these failed transaction information and try to recommit those at engine point (This is the design idea). So it's meaningless to do these things. I will close this PR, if you have any other suggestion or problem, please reopen it. Thanks!

@TyrantLucifer The problem is that on the Flink engine, the commit failure will result in the loss of kafka consumption data, which is not successfully written on the sink side, but the kafka consumption has been committed successfully.

**Comment by lightzhao** [comment]
image

**Comment by lightzhao** [comment]
@TyrantLucifer I don't seem to have permission to re-open this PR. Can you re-open it and invite others to watch this PR together? The test found that it is a bug.

**Comment by Hisoka-X** [comment]
Hi, this is a problem we should faced, in two phase commit, we think the second phase always should success, if we abort it, the two phase commit can't make sure exactly-once. So if second phase failed, in zeta engine, we will recommit it again after job restarted. But flink engine can't support recommit in flink 1.13.6, so user should handle it by themself.

**Pull request closed without merging**
