### PR TITLE
[Fix][Connector-V2][Elasticsearch]Fix sink configuration for DROP_DATA

### PR DESCRIPTION
**Pull request by Wudadada**
### Purpose of this pull request

According to the documentation, the logic for DROP_DATA is to preserve the database structure and delete the data. The original implementation deleted the entire index and recreated it, which caused some field types and parameters to change. This PR corrects the implementation to use the Elasticsearch command to clear index data while preserving the index structure: 
`POST /your_index_name/_delete_by_query
{
    "query": {
      "match_all": {}
    }
}`

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
By running the connector-elasticsearch-e2e and my local es seatunnel task.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @chl-wxp as well.

**Comment by Hisoka-X** [comment]
Thanks @Wudadada for created this PR! Could you follow the guide to open github action on your fork repository? https://github.com/apache/seatunnel/pull/7124/checks?check_run_id=27141444120

**Comment by Hisoka-X** [comment]
cc @hailin0 as well.

**Comment by Hisoka-X** [comment]
Could you add a test case in https://github.com/apache/seatunnel/blob/ae818792131909b5b6ce2d5866360db5ff50a2d5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-elasticsearch-e2e/src/test/java/org/apache/seatunnel/e2e/connector/elasticsearch/ElasticsearchIT.java#L475 to make sure all data are be deleted?

**Comment by Wudadada** [comment]
> Could you add a test case in
> 
> https://github.com/apache/seatunnel/blob/ae818792131909b5b6ce2d5866360db5ff50a2d5/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-elasticsearch-e2e/src/test/java/org/apache/seatunnel/e2e/connector/elasticsearch/ElasticsearchIT.java#L475
> 
> to make sure all data are be deleted?

Thanks for pointing out the issues! I encountered a problem in #7140 that is preventing me from debugging, and I am trying to solve the situation.

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @Wudadada !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
