### PR TITLE
[Improve]Optimize packaging dependencies

### PR DESCRIPTION
**Pull request by CalvinKirs**
We just need to introduce the parent dependency instead of manually introducing the corresponding submodule each time
package result:
```
connectors % find ./
./
.//.DS_Store
.//flink-sql
.//flink-sql/flink-sql-connector-elasticsearch-7-2.1.3-SNAPSHOT.jar
.//flink-sql/flink-sql-connector-jdbc-2.1.3-SNAPSHOT.jar
.//flink-sql/flink-sql-connector-kafka-2.1.3-SNAPSHOT.jar
.//flink-sql/flink-sql-connector-elasticsearch-6-2.1.3-SNAPSHOT.jar
.//flink
.//flink/seatunnel-connector-flink-elasticsearch7-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-jdbc-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-fake-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-doris-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-socket-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-kafka-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-file-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-elasticsearch6-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-console-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-clickhouse-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-http-2.1.3-SNAPSHOT.jar
.//flink/seatunnel-connector-flink-assert-2.1.3-SNAPSHOT.jar
.//plugin-mapping.properties
.//seatunnel
.//seatunnel/connector-file-local-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-neo4j-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-hive-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-redis-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-http-feishu-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-kafka-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-mongodb-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-file-ftp-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-hudi-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-pulsar-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-elasticsearch-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-sentry-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-clickhouse-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-kudu-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-fake-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-console-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-iotdb-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-http-wechat-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-file-oss-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-assert-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-file-base-hadoop-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-http-base-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-datahub-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-file-hadoop-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-socket-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-jdbc-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-email-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-iceberg-2.1.3-SNAPSHOT.jar
.//seatunnel/connector-dingtalk-2.1.3-SNAPSHOT.jar
.//spark
.//spark/seatunnel-connector-spark-tidb-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-feishu-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-console-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-hudi-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-clickhouse-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-elasticsearch-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-email-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-hbase-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-iceberg-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-hive-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-http-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-socket-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-file-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-phoenix-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-redis-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-kafka-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-jdbc-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-neo4j-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-doris-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-fake-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-kudu-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-mongodb-2.1.3-SNAPSHOT.jar
.//spark/seatunnel-connector-spark-webhook-2.1.3-SNAPSHOT.jar

```

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Good job!

**Review by ashulin — COMMENTED** [review]
This doesn't seem to have the desired effect.
I checked this maven command: 

```shell
mvn clean package -pl seatunnel-dist -am -T1C -Pseatunnel
```

image

**Review by ashulin — CHANGES_REQUESTED** [review]
```log
[ERROR] Failed to execute goal on project seatunnel-dist: Could not resolve dependencies for project org.apache.seatunnel:seatunnel-dist:pom:2.1.3-SNAPSHOT: Cannot access central-repository (https://repo1.maven.org/maven2/) in offline mode and the artifact org.apache.seatunnel:seatunnel-connectors-v2:jar:2.1.3-SNAPSHOT has not been downloaded from it before. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :seatunnel-dist
```

**Comment by CalvinKirs** [comment]
I forgot, this does not work, maybe we can create a new connector-v2 module, but that adds to the workload and makes no sense.

**Pull request closed without merging**
