### PR TITLE
[Feature][Connector-V2] JDBC source support string type as partition key

### LINKED ISSUE #3973: [Feature][Connector-V2] JDBC Source Connector `partition_key` support Date/String type.
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

JDBC Source Connector only support number as `partition_key` type. We should support Date and String as `partition_key` type.
1. Support Date(Or Date Type String, like: `2022-12-11`) and String as `partition_key` type
2. String type support `prefix`, so if users string always start with `seatunnel`, we can config prefix `seatunnel` to split all data start with `seatunnel`, like `seatunnel-1`, `seatunnel-2`, `seatunnel-3`.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by EricJoy2048 — APPROVED** [review]

**Review by liugddx — APPROVED** [review]
+1

**Comment by 2416210017** [comment]
Although the implementation supports string types as partitioning keys, this design is not very reasonable. Firstly, it affects the table_ The MD5 hash function is applied to each value in the name column, and the obtained hash value is modulo 10, followed by an absolute value. Only rows with a result equal to 1 will be selected.

For example, the specified partition is 10:
The actual SQL executed in the business library is:

partition 1：
SELECT * FROM (
	select * from metastore_bdc.collect_dct_table_info
) tt where ABS(MD5(table_name) % 10) = 1;

partition 2：
SELECT * FROM (
	select * from metastore_bdc.collect_dct_table_info
) tt where ABS(MD5(table_name) % 10) = 2;
。。。

a9a1d7da54004dbcb5a088fd91879b9

As shown in the figure, this type of query runs through the entire table in the business library and does not utilize index keys, resulting in no performance improvement.
Suggested reference: Sqoop's method of string segmentation, digitizing existing Unicode characters

Reference link：https://blog.csdn.net/fyhailin/article/details/79069475


I have a suggestion：
Fragmentation rules (indexed, not indexed)
1. The step size of fixed field values is determined by setting the number of shards using the maximum and minimum values of the fields. Advantage: Fast sharding speed，Disadvantage: Data skew

2. Fixed number of records, starting with the minimum value, sorted to take the fixed number of records, calculated the corresponding end position, and used the current end position as the starting position for the next sharding prediction, iteratively obtaining the sharding rules.
Advantages: Absolute data balance Disadvantages: Slow sharding prediction

Supplementary explanation:
Using Scheme 1 without Index
Using Scheme 2 with indexes (indexes can improve sharding prediction)

**Comment by Hisoka-X** [comment]
Thanks @2416210017 !

> As shown in the figure, this type of query runs through the entire table in the business library and does not utilize index keys, resulting in no performance improvement.

Yes, this way not perfect. Just the simple way to implement this feature.

> Suggested reference: Sqoop's method of string segmentation, digitizing existing Unicode characters

Can you create an issue for this? (If you can create a PR for this would be wonderful).

**Comment by 2416210017** [comment]
> Thanks @2416210017 !
> 
> > As shown in the figure, this type of query runs through the entire table in the business library and does not utilize index keys, resulting in no performance improvement.
> 
> Yes, this way not perfect. Just the simple way to implement this feature.
> 
> > Suggested reference: Sqoop's method of string segmentation, digitizing existing Unicode characters
> 
> Can you create an issue for this? (If you can create a PR for this would be wonderful).

Of course, the issue has been submitted:https://github.com/apache/seatunnel/issues/5432 thank you for your reply!

**Pull request merged**
