### PR TITLE
[Bug][Connector-v2][PulsarSource]Pulsar consumer ack exception.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request

At present, the ack of pulsar consumer is based on a single message, which results in some messages not being ack. The cumulative message should be used to ensure that all consumed messages can be ack. Exclusive subscription mode also supports cumulative confirmation.
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@EricJoy2048 @Hisoka-X @ashulin @TyrantLucifer PTAL.

**Review by Hisoka-X — DISMISSED** [review]
LGTM

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
Update https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/Error-Quick-Reference-Manual.md

**Comment by lightzhao** [comment]
> Update https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/connector-v2/Error-Quick-Reference-Manual.md

done.

**Review by TyrantLucifer — APPROVED** [review]
cc @ashulin

**Review by ashulin — APPROVED** [review]
LGTM

**Pull request merged**
