### PR TITLE
[Feature][API] Support hocon style declare row type in generic type

### PR DESCRIPTION
**Pull request by CheneyYin**
### Purpose of this pull request

close:
- #6124 

This PR can keep backward compatibility. So, the following schema declaration is available. 
```hocon
schema {
  fields {
    # Hocon style declare row type in generic type
    map0 = "map<string, {c_int = int, c_string = string, c_row = {c_int = int}}>"
    # Json style declare row type in generic type
    map1 = "map<string, {\"c_int\":\"int\", \"c_string\":\"string\", \"c_row\":{\"c_int\":\"int\"}}>"
  }
}
```

### Does this PR introduce _any_ user-facing change?

Update `schema-feature.md`.

### How was this patch tested?

Add new test cases.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Please add doc to `schema-feature.md`

**Comment by CheneyYin** [comment]
> Please add doc to `schema-feature.md`

Done

**Comment by CheneyYin** [comment]
PTAL @Hisoka-X @hailin0

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Thanks @CheneyYin !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
