### PR TITLE
[Bug][Spark] When have empty data source, transform not execute

### LINKED ISSUE #1508: [Bug] [Spark] When have empty data source, transform not execute
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When have sources not only one, but first source data is empty, the transform will not execute
`/tmp/test.csv` is empty file

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
env {
  # You can set spark configuration here
  # see available properties defined by spark: https://spark.apache.org/docs/latest/configuration.html#available-properties
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
  spark.master = local
}

source {
  # This is a example input plugin **only for test and demonstrate the feature input plugin**

  File {
    path = "/tmp/test.csv"
    format = "csv"
    result_table_name = "csv"
  }

  Fake {
    result_table_name = "my_dataset"
  }

}

transform {
  # split data by specific delimiter

  # you can also use other transform plugins, such as sql
  sql {
    sql = "select * from my_dataset"
  }

}

sink {
  # choose stdout output plugin to output data to console
  Console {}
}
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
fix: When have empty data source, transform not execute
This close #1508 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by ruanwenjun — CHANGES_REQUESTED** [review]
@BenJFan I still have confused with the current pipeline design.

I see the code, and find right now if we have multiple resources, transforms, sinks, we will lose some executions.

For example, in the below picture, if we have 3 sources, 2 two transforms, 2 sinks. In the current code, there only source1 will be transformed and sinked. 
image

I am not clear if this is reasonable.

I know what you want to fix in this PR, but I want to discuss this problem, otherwise we may still need to repair this again.

If my understanding is wrong, please let me know.

**Comment by Hisoka-X** [comment]
@ruanwenjun 
> For example, in the below picture, if we have 3 sources, 2 two transforms, 2 sinks. In the current code, there only source1 will be transformed and sinked.

At now, 3 sources, 2 two transforms, 2 sinks both will execute. The problem is if first source no data, then all transforms will not execute. (If first source' data isn't empty, all plugin will execute)

> I know what you want to fix in this PR, but I want to discuss this problem, otherwise we may still need to repair this again.

We can use multiple source, transform, sink. Because one source/transform will registe as table. So user can join multiple source or transform. Also can do complex data process.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Comment by ruanwenjun** [comment]
> @ruanwenjun
> 
> > For example, in the below picture, if we have 3 sources, 2 two transforms, 2 sinks. In the current code, there only source1 will be transformed and sinked.
> 
> At now, 3 sources, 2 two transforms, 2 sinks both will execute. The problem is if first source no data, then all transforms will not execute. (If first source' data isn't empty, all plugin will execute)
> 
> > I know what you want to fix in this PR, but I want to discuss this problem, otherwise we may still need to repair this again.
> 
> We can use multiple source, transform, sink. Because one source/transform will registe as table. So user can join multiple source or transform. Also can do complex data process.

Okay, I just misunderstand something. The source and transform data will be registered as a table.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
