### PR TITLE
[Bugfix][Connector-V2][mysql cdc] Conversion of tinyint(1) to boolean is supported

### LINKED ISSUE #5095: [Bug] [mysql cdc] where binlog create table  tinyint(1) default false  then error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when binlog contain "create table xxx (  xxx   tinyint(1) default false )" 
then  the process exit and report error  cannot parse false to int 

### SeaTunnel Version

2.3.2

### SeaTunnel Config

```conf
XXXX
```

### Running Command

```shell
XXXX
```

### Error Exception

```log
error processing binlog event
java.lang.NumberFormatException :for input string "false"
java.lang.Integer.parseInt(Integer.java:580)
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Carl-Zhou-CN**
…s supported

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

close #5095

### CODE REVIEW

**Review by TaoZex — APPROVED** [review]
LGTM
It is better to change feature to bugfix in the title.

**Review by liugddx — APPROVED** [review]
+1

**Comment by Hisoka-X** [comment]
Does MySQL will create boolean as tinyint?

**Comment by Carl-Zhou-CN** [comment]
> Does MySQL will create boolean as tinyint?

image
yes，it is possible to perform such an operation

**Comment by Carl-Zhou-CN** [comment]
> Does MySQL will create boolean as tinyint?

image
yes,It is possible to perform such an operation

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
