### PR TITLE
[Feature][Druid]Support multi table for druid sink

### PR DESCRIPTION
**Pull request by TaoZex**
### Purpose of this pull request

issue:https://github.com/apache/seatunnel/issues/7002
subtask of https://github.com/apache/seatunnel/issues/5652
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Missed `SupportMultiTableSink` in `DruidSink`. Please refer https://github.com/apache/seatunnel/blob/9b371cd3129845183d14aed303ef2b4657fc0055/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcSink.java#L63

**Comment by TaoZex** [comment]
> Missed `SupportMultiTableSink` in `DruidSink`. Please refer
> 
> https://github.com/apache/seatunnel/blob/9b371cd3129845183d14aed303ef2b4657fc0055/seatunnel-connectors-v2/connector-jdbc/src/main/java/org/apache/seatunnel/connectors/seatunnel/jdbc/sink/JdbcSink.java#L63

Done. Thanks.

**Comment by TaoZex** [comment]
PTAL @hailin0

**Review by Hisoka-X — APPROVED** [review]
LGTM.

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
