### PR TITLE
[Improve][KafkaSource]Concurrent reading of Kafka partitions.

### PR DESCRIPTION
**Pull request by lightzhao**
### Purpose of this pull request
If there is only one Task, then the reading of multiple partitions is synchronized, which affects performance and should be upgraded to concurrent.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@hailin0 @EricJoy2048 @Hisoka-X PTAL.

**Comment by Hisoka-X** [comment]
Thanks @lightzhao for created this PR. Quick question: why not recommend users to add parallelism to job?

**Comment by lightzhao** [comment]
> Quick question: why not recommend users to add parallelism to job?

More concurrency requires more Task Managers, resulting in higher resource usage and costs.

**Comment by Hisoka-X** [comment]
> > Quick question: why not recommend users to add parallelism to job?
> 
> More concurrency requires more Task Managers, resulting in higher resource usage and costs.

This change will bring uncertainty, for example, data from different splits are not written in order, and we do not guarantee the thread safety of the Collector. I prefer to use the parallelism parameter.

**Comment by lightzhao** [comment]
> This change will bring uncertainty, for example, data from different splits are not written in order, and we do not guarantee the thread safety of the Collector. I prefer to use the parallelism parameter.

Yes, there may indeed be issues with out of order, and the collector may also have thread safety issues.

**Pull request closed without merging**
