### PR TITLE
[Bug#851] [spark-clickhouse-sink] Support /DateTime64/DateTime/Date Column

### LINKED ISSUE #851: [Feature][plugin-spark-output-clickhouse] DateTime/Date Column support Timestamp
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

When inserting data into ClickHouse with DateTime or Date column must convert data into string data with a specified format. If the plugin can insert from Spark Timestamp column would be better.

当前写入 ClickHouse 中 DateTime/Date 列时，必须将对应字段转换为指定格式字符串（yyyy-MM-dd），如果支持通过 Spark 中的 Timestamp 就能够写入DateTime/Date的话最好了。

### Usage Scenario

data synchronization

### Related issues

#848 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kyle-cx91**
## Purpose of this pull request
fixed #851 
spark-clickhouse-sink Support /DateTime64/DateTime/Date Column

## step to test

```
-- create source table
CREATE TABLE pdi.st_source_dates
(
    `date01` Date,
    `date03` DateTime,
    `date04` DateTime,
    `cust_id` String,
    `cust_name` String,
    `cust_idcard` String,
    `age` Int32,
    `sex` String
)
ENGINE = StripeLog


--create target table
CREATE TABLE pdi.st_sink_dates
(
    `date01` Date,
    `date03` DateTime,
    `date04` DateTime64,
    `cust_id` String,
    `cust_name` String,
    `cust_idcard` String,
    `age` Int32,
    `sex` String
)
ENGINE = StripeLog
```

**make Some test data**

```
insert into pdi.st_source_dates values
('2022-03-05','2019-01-01 12:12:22','2019-01-01 12:22:22','1111111','test_nameaaaa','card11111111',55,'男'),
('2022-03-05','2019-01-01 12:12:22','2019-01-01 12:22:22','1111111','test_naaaa','card11111111',90,'男');
```

**config SeaTunnel**
vi ./config/jdbc2ck_dates.conf

```
env {
  spark.app.name = "SeaTunnel"
  spark.executor.instances = 2
  spark.executor.cores = 1
  spark.executor.memory = "1g"
}

source {
  jdbc {
    driver = "ru.yandex.clickhouse.ClickHouseDriver"
    url = "jdbc:clickhouse://192.168.1.111:8123/pdi"
    table = "st_source_date"
    result_table_name = "SOURCE_VIEW"
    user = "default"
    password = "jRtXD8F8"
  } 
}

transform {
}

sink {
  clickhouse {
    host = "192.168.1.111:8123"
    clickhouse.socket_timeout = 50000
    database = "pdi"
    table = "st_sink_date"
    fields = ["date01","date03","date04","cust_id","cust_name","cust_idcard","age","sex"]
    username = "default"
    password = "jRtXD8F8"
    bulk_size = 20000
 }
}


```

**start SeaTunnel**

```
./bin/start-seatunnel-spark.sh \
--master local \
--deploy-mode client \
--config ./config/jdbc2ck_dates.conf
```

check the data in target table 
```
select * from pdi.st_sink_dates
```

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by kyle-cx91** [comment]
@CalvinKirs Please have a review

**Comment by wuchunfu** [comment]
@ZhangchengHu0923 Please resolve the conflict, thanks

**Comment by kyle-cx91** [comment]
> @ZhangchengHu0923 Please resolve the conflict, thanks

done @wuchunfu

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
@CalvinKirs LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
