### PR TITLE
[Improve][seatunnel-engine-common] move serializer to common

### PR DESCRIPTION
**Pull request by liugddx**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Other modules need this function? A lot of modules depend on common module, add extra dependency in common module can cause the jar so fat. If only st-engine using the proto serializer I think it put in engine module might be better.

cc @hailin0 @Hisoka-X @ic4y @EricJoy2048 @CalvinKirs @ashulin 

Hey guys, what do you think about it?

**Comment by Hisoka-X** [comment]
> Other modules need this function? A lot of modules depend on common module, add extra dependency in common module can cause the jar so fat. If only st-engine using the proto serializer I think it put in engine module might be better.
> 
> cc @hailin0 @Hisoka-X @ic4y @EricJoy2048 @CalvinKirs @ashulin
> 
> Hey guys, what do you think about it?

+1

**Comment by CalvinKirs** [comment]
> Other modules need this function? A lot of modules depend on common module, add extra dependency in common module can cause the jar so fat. If only st-engine using the proto serializer I think it put in engine module might be better.↳
> 
> cc @hailin0 @Hisoka-X @ic4y @EricJoy2048 @CalvinKirs @ashulin
> 
> Hey guys, what do you think about it?↳

yes, it belongs to the engine module.

**Comment by liugddx** [comment]
> > Other modules need this function? A lot of modules depend on common module, add extra dependency in common module can cause the jar so fat. If only st-engine using the proto serializer I think it put in engine module might be better.↳
> > cc @hailin0 @Hisoka-X @ic4y @EricJoy2048 @CalvinKirs @ashulin
> > Hey guys, what do you think about it?↳
> 
> yes, it belongs to the engine module.

Ok, I will migrate to the engine module.

**Comment by liugddx** [comment]
#3792

**Review by TaoZex — DISMISSED** [review]
+1

**Review by CalvinKirs — DISMISSED** [review]
the `checkpoint-storage` should also be replaced.

**Comment by liugddx** [comment]
> the `checkpoint-storage` should also be replaced.

Done.

**Comment by liugddx** [comment]
@CalvinKirs @EricJoy2048 PTAL thanks.

**Comment by CalvinKirs** [comment]
image
should delete this comment

**Comment by CalvinKirs** [comment]
Btw, A better way is to serialize as a separate module, and we may support other ways in the future, such as protobuf, json and more

**Comment by liugddx** [comment]
> Btw, A better way is to serialize as a separate module, and we may support other ways in the future, such as protobuf, json and more

Done. PTAL thanks.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
