### PR TITLE
[Doc][Improve]Support Chinese for /seatunnel-engine/rest-api.md and local-mode.md and cluster-mode.md and checkpoint-storage.md

### PR DESCRIPTION
**Pull request by dzygoon**
Support Chinese for 
/seatunnel-engine/rest-api.md 
and local-mode.md 
and cluster-mode.md 
and checkpoint-storage.md

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Please fix CI.

**Comment by dzygoon** [comment]
> Please fix CI.

whats mean is CI?

**Comment by dzygoon** [comment]
> Please fix CI.

i got it.dead links.

**Comment by Hisoka-X** [comment]
You can merge from dev to fix dead link because it already be fixed in https://github.com/apache/seatunnel/pull/6442

**Comment by dzygoon** [comment]
> You can merge from dev to fix dead link because it already be fixed in #6442

done,pls recheck.

**Review by davidzollo — APPROVED** [review]
Good Job
LGTM, +1

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
