### PR TITLE
[Update][install-plugin.sh] Change script version to 2.3.3

### LINKED ISSUE #5347: [Improve][install-plugin.sh] Show specified version instead of default
Now the script to install the plugin will use 2.3.1 by default. I suggest not to specify the default value and require the user to manually select.

https://github.com/apache/seatunnel/blob/0cdd3066b358658f0e3019aa92a373ada1a062da/bin/install-plugin.sh#L27

### PR DESCRIPTION
**Pull request by tungbq**
## Purpose of this pull request
Show specified version instead of default
Closes: #5347 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by liugddx — DISMISSED** [review]
LGTM. Thanks for your contribution!

**Comment by Hisoka-X** [comment]
@liugddx Hi, why we should do this change? This change makes our work easier by making it more complicated for users, which I don't think is a good approach. cc@EricJoy2048 @hailin0

**Comment by liugddx** [comment]
> @liugddx Hi, why we should do this change? This change makes our work easier by making it more complicated for users, which I don't think is a good approach. cc@EricJoy2048 @hailin0

IMO, If the user does not specify a version when downloading the plugin, 2.3.1 will be downloaded by default, which may not be what the user wants to see.

**Comment by Hisoka-X** [comment]
In fact, we would change the version value when we prepare release. https://github.com/apache/seatunnel/commit/576f76fe21310817e900965ff87691b74a113b9a

**Comment by liugddx** [comment]
> In fact, we would change the version value when we prepare release. [576f76f](https://github.com/apache/seatunnel/commit/576f76fe21310817e900965ff87691b74a113b9a)

Um. This is also possible, but we need to modify it every time we publish.

**Comment by Hisoka-X** [comment]
Yes, not a big deal than user configure it.

**Comment by liugddx** [comment]
> > In fact, we would change the version value when we prepare release. [576f76f](https://github.com/apache/seatunnel/commit/576f76fe21310817e900965ff87691b74a113b9a)
> 
> Um. This is also possible, but we need to modify it every time we publish.



> Yes, not a big deal than user configure it.

Can this pr change the version to 2.3.3 or turn it off?

**Comment by Hisoka-X** [comment]
Let's change it to 2.3.3 @tungbq

**Comment by tungbq** [comment]
> Let's change it to 2.3.3 @tungbq

So we keep the script approach as is, revert current change in this PR, only change the version to 2.3.3. Is that right? @Hisoka-X @liugddx

**Comment by Hisoka-X** [comment]
> > Let's change it to 2.3.3 @tungbq
> 
> So we keep the script approach as is, revert current change in this PR, only change the version to 2.3.3. Is that right? @Hisoka-X @liugddx

Yes, please.

**Comment by liugddx** [comment]
> > Let's change it to 2.3.3 @tungbq
> 
> So we keep the script approach as is, revert current change in this PR, only change the version to 2.3.3. Is that right? @Hisoka-X @liugddx

Yes

**Comment by tungbq** [comment]
Sure, updated version to 2.3.3! @Hisoka-X @liugddx

**Review by liugddx — APPROVED** [review]
+1

**Review by Hisoka-X — APPROVED** [review]
Thanks @tungbq

**Pull request merged**
