### PR TITLE
[Improve] Speed up ClickhouseFile Local generate a mmap  object

### LINKED ISSUE #5819: [Bug] [Module Name] Hive2CK using CK File  generate data_local.log slow
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

using  CK File sync hive data to ck，total data count 2.3KW，using CK JDBC 40m, using CK File 8h。

From Spark Log, know generate data_local.log  spend 7h, from data_local.log to CK table file spend 5h

### SeaTunnel Version

2.3.3

### SeaTunnel Config

```conf
env {
  spark.app.name = "hive_to_ck_file"
  spark.executor.instances = 4
  spark.executor.cores = 1
  spark.executor.memory = "3g"
  // This configuration is required
  spark.sql.catalogImplementation = "hive"
  spark.executor.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.driver.extraJavaOptions = "-Dfile.encoding=UTF-8"
  spark.hadoop.hive.exec.dynamic.partition = "true"
  spark.hadoop.hive.exec.dynamic.partition.mode = "nonstrict"
  spark.debug.maxToStringFields = 100000
}
source {
    hive {
        table_name = "dms_ddcx.xx_table"
        metastore_uri = "thrift://xxxxx:9083"
        result_table_name = "table"
        parallelism = 4
        read_partitions = ["dt=2023-10-30"]
    }
}
transform {}
sink {
    ClickhouseFile {
        host = "xxx:8123"
        server_time_zone = "Asia/Shanghai"
        database = "dms_ddcx"
        parallelism = 4
        table = "xxxx"
        source_table_name = "xxxx"
        sharding_key = "diversion_id"
        username = "default"
        password = ""
        node_free_password = true
        clickhouse_local_path = "/opt/software/clickhouse local"
        node_pass = []
    }
}
```

### Running Command

```shell
./bin/start-seatunnel-spark-3-connector-v2.sh --master yarn --deploy-mode cluster --config config/hive_to_ck_test.config
```

### Error Exception

```log
no error
```

### Zeta or Flink or Spark Version

spark 3.2.4

### Java or Scala Version

java 1.8

### Screenshots

image

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by viverlxl**
### Purpose of this pull request
Speed up ClickhouseFile Local generate data_local.log file

### Does this PR introduce _any_ user-facing change?
 No

### How was this patch tested?
Use the previous test case, I had test  in my production env,  eg: https://github.com/apache/seatunnel/issues/5819

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @viverlxl ! Please enable the test case run on your fork repository. You can follow the guide. 
image

**Comment by viverlxl** [comment]
> Thanks @viverlxl ! Please enable the test case run on your fork repository. You can follow the guide. image
Done

**Comment by Hisoka-X** [comment]
Please add some empty commit to retrigger CI.

**Comment by Hisoka-X** [comment]
Also I think you should add comment for other better know this PR doing what, and the reason of why we should add this PR?
image

**Comment by viverlxl** [comment]
> Also I think you should add comment for other better know this PR doing what, and the reason of why we should add this PR? image
done

**Review by Hisoka-X — APPROVED** [review]
Thanks @viverlxl !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
