### PR TITLE
[DISCUSS] Delete lombok

### PR DESCRIPTION
**Pull request by liujinhui1994**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by kezhenxu94** [comment]
@liujinhui1994 do you have any issue or mailing list discussion to change this ?

**Comment by liujinhui1994** [comment]
lombok, too redundant for a project. Also less readable, so I recommend removing it. @kezhenxu94

**Comment by CalvinKirs** [comment]
> lombok, too redundant for a project. Also less readable, so I recommend removing it. @kezhenxu94

It's better to be able to discuss in email, I think lombok is good, he makes our code look cleaner, I don't like spending a lot of time in redundant code,.

**Comment by kezhenxu94** [comment]
> lombok, too redundant for a project. @kezhenxu94

When you come to a community you have to learn the community's rules, it's not your own opinion whether Lombok is redundant or not (though some people consider Java codes without Lombok are verbose / redundant and Lombok is a live-saver), you need to discuss with the community when you want to do some changes that effect the developers

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
`vcs` should not be deleted, you can check git log to track the corresponding context.

**Comment by liujinhui1994** [comment]
Because considering the subsequent development, lombok will seriously affect the readability and scalability of the code. Of course I will close this PR if it is not needed by the community here

**Comment by liujinhui1994** [comment]
@CalvinKirs  @kezhenxu94  It's closed, I can open it anytime if needed，thanks

**Comment by CalvinKirs** [comment]
> Because considering the subsequent development, 
>> lombok will seriously affect the readability and scalability of the code. Of course I will close this PR if it is not needed by the community here
If you really feel it is necessary, you can initiate a discussion. But I don't agree with this.

**Pull request closed without merging**
