### PR TITLE
[Improve][Docs][Kafka]Reconstruct the kafka connector document

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Purpose of this pull request
subtask:#4572

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by zhilinli123** [comment]
image
It is recommended to refer to flink for Kafka ssl configuration because users encountered this escape problem before

**Comment by zhilinli123** [comment]
image

`'org.apache.kafka.common.security.scram.ScramLoginModule required username=\"username\" password=\"password\";'
`

It is recommended to refer to flink for Kafka ssl configuration because users encountered this escape problem before

**Comment by MonsterChenzhuo** [comment]
@zhilinli123 @hailin0 @Hisoka-X PTAL,thanks.

**Review by EricJoy2048 — DISMISSED** [review]

**Review by TaoZex — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Hi, please resolve conflict, thanks.

**Comment by MonsterChenzhuo** [comment]
> Hi, please resolve conflict, thanks.

done.

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
