### PR TITLE
[Improve] [Engine] Enables engine to configure all GC parameters

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request
https://github.com/apache/incubator-seatunnel/issues/3155
Enables engine to configure GC parameters Xms and Xmx

Start the engine directly and view the heap using jmap：

Configure Xms and Xmx for seatunnel-env.sh：

Start the engine again and view the heap using jmap

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
How about use `$@` to instead of it? Currently only heap memory size can be set, other jvm parameters are not supported, such as garbage collection. CC @Hisoka-X

**Comment by Hisoka-X** [comment]
> How about use `$@` to instead of it? Currently only heap memory size can be set, other jvm parameters are not supported, such as garbage collection. CC @Hisoka-X

Yes, not only heap memory size, we should can use it to set any jvm parameter.

**Comment by TaoZex** [comment]
> > How about use `$@` to instead of it? Currently only heap memory size can be set, other jvm parameters are not supported, such as garbage collection. CC @Hisoka-X
> 
> Yes, not only heap memory size, we should can use it to set any jvm parameter.

Thanks.I have modified the code and can set all gc parameters via JvmOption.

gc

Set a small gc heap size proves that JvmOption works：

gc1

**Comment by Hisoka-X** [comment]
You should support config parameters in seatunnel-env.sh too. Thanks!

**Comment by TaoZex** [comment]
> You should support config parameters in seatunnel-env.sh too. Thanks!

Thanks for your advice,i have fixed it.

set JvmOption in seatunnel-env.sh config:

34fa3d1ba2759f3de19dd0fa6a3de6e

command input:

af53769795b6326df6ea0d120c5c5e0

Start the engine and view the heap using jmap:

295b84e7a2e1412259df9c2df9543d1

**Comment by TaoZex** [comment]
@Hisoka-X @EricJoy2048 @TyrantLucifer PTAL

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
