### PR TITLE
[Feature][Connector-V2][Jdbc] Add OceanBase catalog

### LINKED ISSUE #5076: [Feature][Connector-V2][Jdbc] Add OceanBase catalog
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add oceanbase catalog to support DataSaveMode, which  is necessary for multiple table job.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by whhe**
## Purpose of this pull request

Add OceanBase catalog in jdbc connector, close #5076.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by whhe** [comment]
Tested on my dev environment and all tests passed.

mvn verify -pl :connector-jdbc-e2e-part-2 -Dtest=JdbcOceanBaseMysqlIT -DfailIfNoTests=false -amd
obmysql

mvn verify -pl :connector-jdbc-e2e-part-2 -Dtest=JdbcOceanBaseOracleIT#testCatalog -DfailIfNoTests=false -amd
oboracle

**Comment by whhe** [comment]
@EricJoy2048 PTAL

**Review by FlechazoW — APPROVED** [review]
LGTM. Nice job!

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by whhe** [comment]
I tried to enable the oceanbase it case with the new docker image, and there are still some issues about the container startup, which I will fix in another pr. The label is removed by the bot, PTAL again @EricJoy2048

**Comment by whhe** [comment]
The ci failure is not related to this pr. I tried the case `JdbcVerticaIT` on my dev machine and it executed successfully, it's a little weird.

https://github.com/whhe/incubator-seatunnel/actions/runs/6465553249/job/17560811546

**Comment by whhe** [comment]
https://github.com/whhe/incubator-seatunnel/actions/runs/6492005114/job/17630374248

**Review by hailin0 — COMMENTED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Review by ic4y — APPROVED** [review]

**Pull request merged**
