### PR TITLE
[hotfix][Connector-V2]--help according to repair

### PR DESCRIPTION
**Pull request by Carl-Zhou-CN**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Carl-Zhou-CN** [comment]
#2811

**Comment by Carl-Zhou-CN** [comment]
image

**Comment by Carl-Zhou-CN** [comment]
@EricJoy2048 Please help to check whether this is what you want to achieve

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]
+1

**Pull request merged**
