### PR TITLE
Display project icon in idea

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request
add logo

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by EricJoy2048** [comment]
Hi, Can you explain in detail what problem this PR wants to solve?

**Comment by liunaijie** [comment]
> Hi, Can you explain in detail what problem this PR wants to solve?

No, this is not to solve any problem, just want add an icon to IDEA for funny. 
after this, when you open the project you can see the icon instead of the `S` word.

**Review by davidzollo — APPROVED** [review]
+1, it works

**Review by hailin0 — APPROVED** [review]

**Comment by hailin0** [comment]
LGTM

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
