### PR TITLE
[Improve][Connector-V2] Refactor hdfs file sink connector code structure

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

According to pr https://github.com/apache/incubator-seatunnel/pull/2555 , this pr has optimized the hdfs file sink connector on top of it.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
@CalvinKirs @EricJoy2048 PTAL.

**Comment by TyrantLucifer** [comment]
> @CalvinKirs @EricJoy2048 PTAL.

Sorry, some classes are used in hive-connector, I need to refactor hive connector first.

**Comment by TyrantLucifer** [comment]
> > @CalvinKirs @EricJoy2048 PTAL.
> 
> Sorry, some classes are used in hive-connector, I need to refactor hive connector first.

This pr is ready. Please review. @EricJoy2048 @CalvinKirs

**Review by EricJoy2048 — APPROVED** [review]
+1

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
