### PR TITLE
[fix] revert IMAP cache data field type to compatible with old version

### LINKED ISSUE #6853: [Bug] when upgrade 2.3.5 version from 2.3.4, job restore failed
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

In version 2.3.4, i enable the IMAP storage cache, when upgrade to version 2.3.5. Will get exception when read data from the cached imap data.
the error reason is this pr https://github.com/apache/seatunnel/pull/6666/files#r1598217272 update the field type in IMAP cached class. 

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
na
```

### Running Command

```shell
na
```

### Error Exception

image

### Zeta or Flink or Spark Version

zeta

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request

fix #6853

### How was this patch tested?
using exist test.

**we need conside how to test the version compatible.**

now we can't save binary file to github, so we can't read from binary file to check whether compatible with current. and we can't gererate the old version cache data from current version.

now just revert the code.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
> now we can't save binary file to github, so we can't read from binary file to check whether compatible with current. and we can't gererate the old version cache data from current version.

We can use old version jar to submit job then get binary file. Then use new version jar to submit job and read binary file. It's all in docker. So I think it should be worked.

**Review by EricJoy2048 — APPROVED** [review]

**Comment by liunaijie** [comment]
if we fix it in version 2.3.6 , it still has issue when upgrade from 2.3.5. but it's ok for older version like 2.3.4.
if we not fix it, it will be ok when upgrade from 2.3.5. but will has issue when from version before 2.3.4

**Comment by Hisoka-X** [comment]
> if we fix it in version 2.3.6 , it still has issue when upgrade from 2.3.5. but it's ok for older version like 2.3.4. if we not fix it, it will be ok when upgrade from 2.3.5. but will has issue when from version before 2.3.4

Yes, we should fix it before release 2.3.6. Could you create an issue about add test case for imap upgrade?

**Comment by Hisoka-X** [comment]
> > if we fix it in version 2.3.6 , it still has issue when upgrade from 2.3.5. but it's ok for older version like 2.3.4. if we not fix it, it will be ok when upgrade from 2.3.5. but will has issue when from version before 2.3.4
> 
> Yes, we should fix it before release 2.3.6. Could you create an issue about add test case for imap upgrade?

Added https://github.com/apache/seatunnel/issues/7055

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
