### PR TITLE
[Improve] [core] Remove System.out.print with Logger

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This patch removes System.out.print with Logger

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@asdf2014 In my knowledge, `ExposeSparkConf` is used to extract conf and set in args, if use log may cause problem, you can find some details in `start-seatunnel-spark.sh`.

**Comment by asdf2014** [comment]
Hi @ruanwenjun, thanks for your comment. Okay, I see. Maybe we can add a relate test to guard this logic.

**Comment by ruanwenjun** [comment]
> Hi @ruanwenjun, thanks for your comment. Okay, I see. Maybe we can add a relate test to guard this logic.

Agree with you.

**Comment by yx91490** [comment]
> @asdf2014 In my knowledge, `ExposeSparkConf` is used to extract conf and set in args, if use log may cause problem, you can find some details in `start-seatunnel-spark.sh`.

+1, close this pr if no more questions.

**Pull request closed without merging**
