### PR TITLE
[bugfix][file-execl] Fix The Row duplicate case by SeaTunnelRow multiplexing

### PR DESCRIPTION
**Pull request by ic4y**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Please add test case

**Review by EricJoy2048 — APPROVED** [review]

**Comment by EricJoy2048** [comment]
> Please add test case



> Please add test case



> Please add test case

I think you can use a localfile sink to check the data read from excel.

**Comment by EricJoy2048** [comment]
https://github.com/apache/seatunnel/issues/6159 test issue created.

**Comment by hailin0** [comment]
> #6159 test issue created.

ok 
Please add test cases later

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
