### PR TITLE
[Fix] Fix the cdc bug about NPE when the original table deletes a field

### PR DESCRIPTION
**Pull request by JohnZp**
### Purpose of this pull request

Fix NPE, it introduced by https://github.com/apache/seatunnel/issues/5575

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Nothing

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Could you open your fork repository action follow the guide?
image

**Comment by JohnZp** [comment]
@Hisoka-X The checked have passed, please help review

**Review by Hisoka-X — APPROVED** [review]
Make sense to me, cc @hailin0 @ic4y .

**Review by liugddx — APPROVED** [review]
Good job.

**Pull request merged**
