### PR TITLE
[Improve] [config]  Optimize clickhouse connector checkConfig

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
subTask of #1153 
Optimize clickhouse connector checkConfig

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by xleoken** [comment]
hi @simon824, you can create an umbrella issue, so we can know more about this patch.

**Comment by simon824** [comment]
> hi @simon824, you can create an umbrella issue, so we can know more about this patch.

#1153  cc @leo65535

**Comment by simon824** [comment]
@leo65535 @CalvinKirs PTAL, thx. This pr aim to optimized check config logic by `checkConfigUtil`, reduce redundant code.

**Review by wuchunfu — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
