### PR TITLE
[Bugfix][CDC Base] Fix NPE caused by adding a table for restore job

### PR DESCRIPTION
**Pull request by ic4y**
### Purpose of this pull request

Fix NPE caused by adding a table for restore job
image

image

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
LGTM

Writing e2e is difficult, what do you think?
cc @Hisoka-X 

@ic4y Can you write unit tests?

**Review by EricJoy2048 — APPROVED** [review]

**Comment by Hisoka-X** [comment]
> LGTM
> 
> Writing e2e is difficult, what do you think? cc @Hisoka-X
> 
> @ic4y Can you write unit tests?

I think this is caused by the lack of our CDC-related test cases. Without basic use cases, it is difficult to add use cases for specific scenarios. We need to gradually improve CDC-related test cases. E2E testing is difficult to achieve, but through fine control of the code flow, it should be possible to write use cases for special scenarios.

We can do it later.

**Comment by EricJoy2048** [comment]
> > LGTM
> > Writing e2e is difficult, what do you think? cc @Hisoka-X
> > @ic4y Can you write unit tests?
> 
> I think this is caused by the lack of our CDC-related test cases. Without basic use cases, it is difficult to add use cases for specific scenarios. We need to gradually improve CDC-related test cases. E2E testing is difficult to achieve, but through fine control of the code flow, it should be possible to write use cases for special scenarios.
> 
> We can do it later.

Yes, The test cases for CDC are difficult, but we still need to find a way to add e2e, especially as our CDC supports more and more connectors. cc @Carl-Zhou-CN

**Comment by hailin0** [comment]
> > LGTM
> > Writing e2e is difficult, what do you think? cc @Hisoka-X
> > @ic4y Can you write unit tests?
> 
> I think this is caused by the lack of our CDC-related test cases. Without basic use cases, it is difficult to add use cases for specific scenarios. We need to gradually improve CDC-related test cases. E2E testing is difficult to achieve, but through fine control of the code flow, it should be possible to write use cases for special scenarios.
> 
> We can do it later.

Yes, need to add basic restore/add/drop table e2e cases

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
