### PR TITLE
[Docs] Fix error examples of kafka sink

### PR DESCRIPTION
**Pull request by hailin0**
### Purpose of this pull request
Remove error exapmles

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
only update docs example

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
PTAL

**Comment by Hisoka-X** [comment]
So kafka dosen't support read from specific partition now? I remember we support it before.

**Comment by Hisoka-X** [comment]
Also please add some comment for this PR
image

**Comment by hailin0** [comment]
> So kafka dosen't support read from specific partition now? I remember we support it before.

Only updated docs examples, no feature changed

**Comment by hailin0** [comment]
> Also please add some comment for this PR image

Done

**Review by Hisoka-X — APPROVED** [review]

**Review by lightzhao — APPROVED** [review]

**Review by liugddx — APPROVED** [review]

**Pull request merged**
