### PR TITLE
[Bug] [root directory] Delete .idea directory #2258

### PR DESCRIPTION
**Pull request by MRYOG**
delete .idea directory

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ic4y** [comment]
cc @CalvinKirs

**Comment by xleoken** [comment]
hi @MRYOG, why need delete the directory? can you explain in detail?

**Comment by xleoken** [comment]
https://github.com/apache/incubator-kyuubi/tree/master/.idea
https://github.com/apache/flink/tree/master/.idea

**Comment by CalvinKirs** [comment]
hi, this is not a bug, if you need context, you can use `gitlog` look .

**Comment by MRYOG** [comment]
> hi @MRYOG, why need delete the directory? can you explain in detail?

first clone seatunnel project , idea can not find package , like this 
image
If idea normal display package , can delete .idea and local recompile ，I don't think it is very friendly to new users

**Comment by xleoken** [comment]
> > hi @MRYOG, why need delete the directory? can you explain in detail?
> 
> first clone seatunnel project , idea can not find package , like thisIf idea normal display package , can delete .idea and local recompile ，I don't think it is very friendly to new users

hi @MRYOG, the `vcs.xml` will not affect ide import SeaTunnel project, you should clean the idea cache.

When the maven compile successful, the idea will display normally.

**Comment by MRYOG** [comment]
> hi, this is not a bug, if you need context, you can use `gitlog` look .

ok, but i think this is a open source project , the directory of a compiler should not appear

**Pull request closed without merging**
