### PR TITLE
[Improve][Zeta] Add restore when commit failed

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
This PR change the behavior of commit failed. We should retry job as usual.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add new test

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by TaoZex — APPROVED** [review]
+1

**Review by hailin0 — DISMISSED** [review]

**Comment by TyrantLucifer** [comment]
What test case can verify it?

**Comment by Hisoka-X** [comment]
> What test case can verify it?

adding

**Comment by TyrantLucifer** [comment]
> > What test case can verify it?
> 
> adding

Could you please offer the details?

**Comment by Hisoka-X** [comment]
> Could you please offer the details?

I'm adding test case, after it ready, I will push to this PR branch.

**Comment by Hisoka-X** [comment]
I added new test to cover this. PTAL @TyrantLucifer @hailin0 @TaoZex @EricJoy2048

**Review by EricJoy2048 — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]
LGTM

**Pull request merged**
