### PR TITLE
[Bugfix][Clickhouse] Fix clickhouse sink flush bug

### PR DESCRIPTION
**Pull request by happyboy1024**
#5352 
Because the try-with-resource syntax sugar is used, the connection is closed early during the checkpoint trigger phase, resulting in subsequent data writes failing

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Carl-Zhou-CN** [comment]
Yeah, you're right

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X PTAL

**Comment by Hisoka-X** [comment]
Thanks for the fix! Do you know which PR bring this bug?

**Comment by Carl-Zhou-CN** [comment]
> Thanks for the fix! Do you know which PR bring this bug?

#4999

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X  I'm sorry. It's because I ignored the grammar candy

**Comment by Hisoka-X** [comment]
> @Hisoka-X I'm sorry. It's because I ignored the grammar candy

never mind, I just want to know why it passed ci.

**Review by EricJoy2048 — APPROVED** [review]

**Review by liugddx — APPROVED** [review]

**Pull request merged**
