### PR TITLE
[Hotfix][Docs] Fix error words in QuickStart Doc

### PR DESCRIPTION
**Pull request by lianghuan-xatu**
## Purpose of this pull request

There is a syntax error and a word spelling error in the document. The configuration directory as a specific noun needs to be preceded by a definite article.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Good job! Thanks for your contribution! Let's waiting CI.

**Review by TyrantLucifer — APPROVED** [review]
LGTM

**Comment by lianghuan-xatu** [comment]
> Good job! Thanks for your contribution! Let's waiting CI.

Thx

**Review by EricJoy2048 — APPROVED** [review]
LGTM, Thanks for your contribution.

**Pull request merged**
