### PR TITLE
[Feature][connector-tidb][PIW] add tidb connector

### PR DESCRIPTION
**Pull request by lhyundeadsoul**
add tidb connector which is referring jdbc connector and do some simplification such as removing postgre dialect etc.

## Purpose of this pull request
refer to https://github.com/apache/incubator-seatunnel/issues/2173

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ic4y** [comment]
@lhyundeadsoul  thanks for your contribution
Is there any difference with the JDBC connector currently, or is there any optimization point。Currently looks the same as the JDBC connector

**Comment by lhyundeadsoul** [comment]
> 

We have discussed this in https://github.com/apache/incubator-seatunnel/issues/2173  ,but we have no further idea. TiDB obeys MySQL protocol, indeed it can handle by JDBC connector. So I did some simplification, such as removing postgre Dialect etc. If there are some special optimization for TiDB , we can add them based on this module.
Is there any good idea ,please let me know. Thx!

**Comment by ic4y** [comment]
If it is only based on the jdbc connector, it is better to support TiDB directly in the JDBC connector. You now have a lot of the same code for the tidb connector and the JDBC connector,It's not good for maintenance.

**Comment by lhyundeadsoul** [comment]
> If it is only based on the jdbc connector, it is better to support TiDB directly in the JDBC connector. You now have a lot of the same code for the tidb connector and the JDBC connector,It's not good for maintenance.

I think so.

**Pull request closed without merging**
