### PR TITLE
[Hotfix][connector-v2][clickhouse] Fixed an out-of-order BUG with output data fields of clickhouse-sink

### PR DESCRIPTION
**Pull request by wowzx**
If the order of the output data fields is not in accordance with the order of the table_schema fields, the output fields are out of order.
This is caused by the array of fields returned with ` JdbcBatchStatementExecutorBuilder#getDefaultProjectionFields` being sorted in table_schema field order
See: [#5176](https://github.com/apache/seatunnel/issues/5176)

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by liugddx — COMMENTED** [review]
LGTM . @Hisoka-X PTAL

**Review by liugddx — DISMISSED** [review]

**Comment by liugddx** [comment]
Please fix CI error. Run  `mvn spotless:apply`

**Comment by wowzx** [comment]
> Please fix CI error. Run `mvn spotless:apply`

Fixed, please check it

**Comment by Hisoka-X** [comment]
Could you add a test case for this bug fixed? To make sure this bug will not regression.

**Comment by wowzx** [comment]
> Could you add a test case for this bug fixed? To make sure this bug will not regression.

create sql 
```sql
create table test(
     `field1`          String,
     `field2`          String,
     `field3`          String,
     `field4`          String
)engine=Memory;
```
config file
```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}
source {
  FakeSource {
    source_table_name = "fake"
    schema = {
      fields {
        field1 = string
        field2 = string
        field3 = string
        field4 = string
      }
    }
    rows = [
      {
        kind = INSERT
        fields = ["v_1", "v_2", "v_3","v_4"]
      }
    ]
  }
}
transform {
  FieldMapper {
    source_table_name = "fake"
    result_table_name = "test"
    field_mapper = {
        field2 = field2
        field4 = field4
        field3 = field3
        field1 = field1
    }
  }
}
sink {
  Clickhouse {
    source_table_name = "test"
    host = "127.0.0.1:8123"
    database = "Test"
    table = "test"
    username = "default"
    password = ""
    bulk_size = 1
  }
}
```
before fix
image

after fix
image

**Comment by Hisoka-X** [comment]
@wowzx Could you add UT for this? Thanks.

**Comment by EricJoy2048** [comment]
> 

You can add this test case to e2e test reference https://github.com/apache/seatunnel/blob/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-clickhouse-e2e/src/test/java/org/apache/seatunnel/connectors/seatunnel/clickhouse/ClickhouseIT.java

**Review by ZhaoRuidong — APPROVED** [review]
aggre

**Review by hailin0 — APPROVED** [review]

**Comment by hailin0** [comment]
Does anyone want to help add testcase?

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
