### PR TITLE
[e2e] Fix missing module name in pom

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

Fix missing module name in pom

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by ashulin — COMMENTED** [review]
@hailin0 CC

**Comment by ashulin** [comment]
@Hisoka-X CC

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by hailin0 — COMMENTED** [review]
LGTM

**Comment by Hisoka-X** [comment]
The clickhouse e2e have some problem, can you help to fix it? Thanks

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
