### PR TITLE
[Improve][connector-file-s3] update save mode function for s3

### PR DESCRIPTION
**Pull request by chl-wxp**
### Purpose of this pull request

update save mode function for s3

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?
user test

### Check list

* [ ] update save mode function for s3

### CODE REVIEW

**Comment by EricJoy2048** [comment]
Document?

**Comment by EricJoy2048** [comment]
Please upload local test screenshots

**Comment by chl-wxp** [comment]
**run first**
image
image
**run second**
image
image
**run third**
image
image
**run forth**
image
image

**Comment by chl-wxp** [comment]
can close

**Pull request closed without merging**
