### PR TITLE
[Build] Remove `connector/seatunnel` directory

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
This PR remove `connector/seatunnel` directory in binary package. Move all connector to `connector` directory. Because we only have one series connector.

Tested in local, also if CI passed means change work fine.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by hailin0 — COMMENTED** [review]
update `bin/install-plugin.sh`?

**Comment by Hisoka-X** [comment]
> update `bin/install-plugin.sh`?

oh, I forgot it. Thanks for remind.

**Comment by ruanwenjun** [comment]
> update `bin/install-plugin.sh`?

update `bin/install-plugin.cmd`

**Comment by Hisoka-X** [comment]
> > update `bin/install-plugin.sh`?
> 
> update `bin/install-plugin.cmd`

Done

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
