### PR TITLE
[Feature][st-engine] Add user-defined class loader

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

#2345 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by EricJoy2048** [comment]
LGTM

**Comment by EricJoy2048** [comment]
cc @Hisoka-X  @CalvinKirs

**Comment by Hisoka-X** [comment]
The classloader should implement child first logic.

**Comment by TyrantLucifer** [comment]
If we implement child first logic, we should discuss which classes should be loaded by the parent, I think this is a topic we can discuss in community meeting at tonight.

**Comment by Hisoka-X** [comment]
> If we implement child first logic, we should discuss which classes should be loaded by the parent, I think this is a topic we can discuss in community meeting at tonight.

Agree with you

**Comment by EricJoy2048** [comment]
> > If we implement child first logic, we should discuss which classes should be loaded by the parent, I think this is a topic we can discuss in community meeting at tonight.
> 
> Agree with you

Do we have any conclusions about this discussion?

**Comment by Hisoka-X** [comment]
> > > If we implement child first logic, we should discuss which classes should be loaded by the parent, I think this is a topic we can discuss in community meeting at tonight.
> > 
> > 
> > Agree with you
> 
> Do we have any conclusions about this discussion?

The `org.apache.seatunnel` should alway load by parent, other use child first.

**Comment by TyrantLucifer** [comment]
@EricJoy2048 @Hisoka-X pls review, thx.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
