### PR TITLE
[Feature][Connector-v2]add raw format with KafkaSource

### PR DESCRIPTION
**Pull request by lightzhao**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@Hisoka-X @EricJoy2048  @TyrantLucifer please approve ci.

**Review by TaoZex — COMMENTED** [review]
Please add UT for Raw format.

**Comment by lightzhao** [comment]
> Please add UT for Raw format.
e2e has been added, please approve ci.

**Comment by ic4y** [comment]
@lightzhao Please merge the latest dev branch and resolve the conflicts.

**Comment by lightzhao** [comment]
> @lightzhao Please merge the latest dev branch and resolve the conflicts.

fixed.

**Comment by lightzhao** [comment]
@TaoZex @ic4y @Hisoka-X PTAL.

**Comment by lightzhao** [comment]
image
Why is there such an exception? It has nothing to do with the module I submitted, and the latest code has also been merged.

**Comment by lightzhao** [comment]
@TaoZex @ic4y @EricJoy2048 @Hisoka-X PTAL.

**Review by yx91490 — DISMISSED** [review]

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning. cc @EricJoy2048 @hailin0

**Comment by hailin0** [comment]
> When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning. cc @EricJoy2048 @hailin0

+1

This is a duplicate feature

**Comment by lightzhao** [comment]
> When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning.

If schema information is not set, how should field information be obtained in the transform and sink phases?

**Comment by EricJoy2048** [comment]
> > When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning.
> 
> If schema information is not set, how should field information be obtained in the transform and sink phases?

Schema is required when read message from kafka.

**Comment by EricJoy2048** [comment]
> When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning. cc @EricJoy2048 @hailin0

+1

**Comment by lightzhao** [comment]
> > When we specify format as text and do not configure schema information, the record will be output as is, so I believe this modification has no meaning. cc @EricJoy2048 @hailin0
> 
> +1

I don’t understand the previous and later replies. You need to set the schema, but the alternative method is not to set it. What does it mean?

**Pull request closed without merging**
