### PR TITLE
[Bug Fix] [seatunnel-connectors-v2][SFTP] Fix incorrect exception handling logic

### PR DESCRIPTION
**Pull request by lucklilili**
Return cannot be used in a finally block. When a return in a finally block is returned, the method ends execution and the return statement in a try block will no longer be executed.

@https://github.com/apache/incubator-seatunnel/issues/4719#issue-1699730124

## Purpose of this pull request
Fix Return cannot be used in a finally block. When a return in a finally block is returned, the method ends execution and the return statement in a try block will no longer be executed.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]
Good catch! LGTM

**Comment by zhilinli123** [comment]
Please check your CI @lucklilili 
https://github.com/apache/incubator-seatunnel/actions/runs/4913075392/jobs/8777251678?pr=4720
You should do `mvn spotless:apply ` To ensure that the code style is uniform

**Comment by lucklilili** [comment]
@zhilinli123 The mvn spotless: apply check CI has been executed and a new pull request has been submitted

**Review by EricJoy2048 — DISMISSED** [review]
LGTM, Please wait CI

**Comment by lucklilili** [comment]
@EricJoy2048 Corrected errors during CI process, please CI

**Review by EricJoy2048 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
@lucklilili Thanks!

**Comment by lucklilili** [comment]
@Hisoka-X No need to be polite, we will also participate in the future

**Pull request merged**
