### PR TITLE
[SeaTunnel#1191] DorisSink,DruidSink,DruidSource,Elasticsearch,FileSo…

### PR DESCRIPTION
**Pull request by bigdataf**
…urce,FileSink,InfluxDbSink Support for parallel parameters

Signed-off-by: bigdataf <fwt_428@163.com>

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by bobqiu — COMMENTED** [review]
good

**Comment by asdf2014** [comment]
Hi @bigdataf, thanks for your contribution, Overall LGTM, however you may need fix the check style to pass the CI

image

**Comment by bigdataf** [comment]
I had been fix the check style of this pr,and add doc,please review. Thank you!

**Comment by bigdataf** [comment]
@[asdf2014](https://github.com/asdf2014) I had been fix the check style of this pr,and add doc,please review. Thank you!

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
