### PR TITLE
[Bugfix][connector-cdc-mysql] Fix listener not released when BinlogClient reuse

### PR DESCRIPTION
**Pull request by happyboy1024**
## Purpose of this pull request
resolve mysql connections and memory of jvm increased abnormally

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TaoZex** [comment]
please improve the pr title

**Comment by happyboy1024** [comment]
> please improve the pr title

PTAL

**Comment by hailin0** [comment]
fix it like this
https://github.com/apache/seatunnel/pull/5037

**Comment by happyboy1024** [comment]
> fix it like this #5037

yes, #5037 fixed the connections leak, but I think we need to unregister this listener after the backfillReadTask is finished. Because the binlogClient is reuse and its internal listener are a list, subsequent binlog records trigger these listener and add data to the queue, causing memory to grow and GC to be triggered frequently. Do you think there is such a problem here?

**Comment by hailin0** [comment]
> > fix it like this #5037
> 
> yes, #5037 fixed the connections leak, but I think we need to unregister this listener after the backfillReadTask is finished. Because the binlogClient is reuse and its internal listener are a list, subsequent binlog records trigger these listener and add data to the queue, causing memory to grow and GC to be triggered frequently. Do you think there is such a problem here?


Agree with you, but copy `MySqlStreamingChangeEventSource` is difficult to maintain

Can it be modified like this?

image

**Comment by happyboy1024** [comment]
> > > fix it like this #5037
> > 
> > 
> > yes, #5037 fixed the connections leak, but I think we need to unregister this listener after the backfillReadTask is finished. Because the binlogClient is reuse and its internal listener are a list, subsequent binlog records trigger these listener and add data to the queue, causing memory to grow and GC to be triggered frequently. Do you think there is such a problem here?
> 
> Agree with you, but copy `MySqlStreamingChangeEventSource` is difficult to maintain
> 
> Can it be modified like this?
> 
> image

It looks better this way. I did not consider using reflection to solve this problem, I will test it again.

**Comment by happyboy1024** [comment]
@hailin0 I have modified and tested it. The problem seems to have been solved correctly.

**Review by hailin0 — COMMENTED** [review]
LGTM

**Review by hailin0 — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
