### PR TITLE
[hotfix][flink-1.13] fix flink example NPE & NoSuchMethodError

### PR DESCRIPTION
**Pull request by ashulin**
## Purpose of this pull request
1. Datahub don't add example to the `seatunnel-flink-connector-v2-example` module.
2. `connector-datahub` depends on the lower version of `common-io`, causing dependency conflicts.
3. NoSuchMethodError exception caused by dependency conflict.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ashulin** [comment]
@2013650523 @wuchunfu PTAL.

**Comment by CalvinKirs** [comment]
Do we no longer require users to submit the code of the example?  and this module is only used for local debugging by users?
Otherwise, the problem of this module jar conflict will still exist.

In addition, some connectors can't combine used (maybe a large number of tests are required to be reflected in the document), and for some reason, it is difficult for us to achieve unified version management.

**Comment by TyrantLucifer** [comment]
> 

The same as you. I think it is necessary to ask the user not to submit code to this module, this module only used by developers to debug their own programs.

**Comment by ashulin** [comment]
> Do we no longer require users to submit the code of the example? and this module is only used for local debugging by users? Otherwise, the problem of this module jar conflict will still exist.
> 
> In addition, some connectors can't combine used (maybe a large number of tests are required to be reflected in the document), and for some reason, it is difficult for us to achieve unified version management.

In the future, we will support multiple versions of the flink/spark engine, and version management will become an important issue.

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
I will merge this PR first,
Could you create an issue to discuss this?

**Pull request merged**
