### PR TITLE
[Api-draft] Support Spark Sink convert to SeaTunnel

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Support Spark Sink convert to SeaTunnel

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ashulin** [comment]
Why does the Converter interface exist? Each engine can directly convert the sink of seatunnel to it‘s inner class when translating, and the converter just makes the class file more.

**Comment by Hisoka-X** [comment]
> Why does the Converter interface exist? Each engine can directly convert the sink of seatunnel to it‘s inner class when translating, and the converter just makes the class file more.

I think Converter can make the convert logic clearer, let the engine translation implementers know what components they need to convert, and a more general code structure.

**Comment by Hisoka-X** [comment]
> > Why does the Converter interface exist? Each engine can directly convert the sink of seatunnel to it‘s inner class when translating, and the converter just makes the class file more.
> 
> I think Converter can make the convert logic clearer, let the engine translation implementers know what components they need to convert, and a more general code structure.

@ruanwenjun @CalvinKirs What do you think?

**Comment by ashulin** [comment]
I think how to translate can only be determined by the current engine. For example, on flink 1.11, SinkCommitter and SinkWriter cannot be converted separately.

**Comment by ruanwenjun** [comment]
> > > Why does the Converter interface exist? Each engine can directly convert the sink of seatunnel to it‘s inner class when translating, and the converter just makes the class file more.
> > 
> > 
> > I think Converter can make the convert logic clearer, let the engine translation implementers know what components they need to convert, and a more general code structure.
> 
> @ruanwenjun @CalvinKirs What do you think?

If we can define a template method by converter, this will be great. Anyway, I think we need to implement this first, the code can be optimized if we find any problem. The current implementation is OK to me. 

In my knowledge, we need to implement different translation for different version. For example, we may need to create a module `seatunnel-translation-flink1.11` to support flink 1.11, and create a module `seatunnel-translation-flink2.11` to support the version 2.11.

**Comment by Hisoka-X** [comment]
> I think how to translate can only be determined by the current engine. For example, on flink 1.11, SinkCommitter and SinkWriter cannot be converted separately.



> I think how to translate can only be determined by the current engine. For example, on flink 1.11, SinkCommitter and SinkWriter cannot be converted separately.

I think we should run it first, when we make this translation logic come true. And if like you say, we can't use converter logic in flink 1.11 and so on. I will change this to support that. But the common structure is more important in my view.

**Comment by ruanwenjun** [comment]
I merge this first.

**Pull request merged**
