### PR TITLE
 [Feature][Zeta][REST-API] Add REST API To Get System Monitoring Information

### LINKED ISSUE #4144: [Feature][Zeta][REST-API]Get system monitoring information.
Get cluster metrics to rest api. Link to #4139

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Purpose of this pull request

close #4144 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
request

http://localhost:5801/hazelcast/rest/maps/system-monitoring-information

response

图片


图片


[
    {
        "processors":"8",
        "physical.memory.total":"16.0G",
        "physical.memory.free":"16.3M",
        "swap.space.total":"0",
        "swap.space.free":"0",
        "heap.memory.used":"135.7M",
        "heap.memory.free":"440.8M",
        "heap.memory.total":"576.5M",
        "heap.memory.max":"3.6G",
        "heap.memory.used/total":"23.54%",
        "heap.memory.used/max":"3.73%",
        "minor.gc.count":"6",
        "minor.gc.time":"110ms",
        "major.gc.count":"2",
        "major.gc.time":"73ms",
        "load.process":"24.78%",
        "load.system":"60.00%",
        "load.systemAverage":"2.07",
        "thread.count":"117",
        "thread.peakCount":"118",
        "cluster.timeDiff":"0",
        "event.q.size":"0",
        "executor.q.async.size":"0",
        "executor.q.client.size":"0",
        "executor.q.client.query.size":"0",
        "executor.q.client.blocking.size":"0",
        "executor.q.query.size":"0",
        "executor.q.scheduled.size":"0",
        "executor.q.io.size":"0",
        "executor.q.system.size":"0",
        "executor.q.operations.size":"0",
        "executor.q.priorityOperation.size":"0",
        "operations.completed.count":"10",
        "executor.q.mapLoad.size":"0",
        "executor.q.mapLoadAllKeys.size":"0",
        "executor.q.cluster.size":"0",
        "executor.q.response.size":"0",
        "operations.running.count":"0",
        "operations.pending.invocations.percentage":"0.00%",
        "operations.pending.invocations.count":"0",
        "proxy.count":"8",
        "clientEndpoint.count":"0",
        "connection.active.count":"2",
        "client.connection.count":"0",
        "connection.count":"0"
    }
]

**Comment by MonsterChenzhuo** [comment]
In cluster mode:
图片

**Comment by liugddx** [comment]
Please add e2e case  like #4140

**Review by liugddx — APPROVED** [review]
LGTM

**Comment by liugddx** [comment]
@Hisoka-X @EricJoy2048 PTAL thanks.

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
