### PR TITLE
[Hotfix][Zeta] Fix batch tasks cannot be stopped after retrying

### PR DESCRIPTION
**Pull request by hailin0**
### Purpose of this pull request

[Zeta] Fix that batch tasks cannot be stopped after retrying

image

https://github.com/apache/seatunnel/blob/c645d925dcb85d6d0932427eba39a7e4283ec8ed/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java#L496
https://github.com/apache/seatunnel/blob/c645d925dcb85d6d0932427eba39a7e4283ec8ed/seatunnel-engine/seatunnel-engine-server/src/main/java/org/apache/seatunnel/engine/server/checkpoint/CheckpointCoordinator.java#L922

### Does this PR introduce _any_ user-facing change?
No

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
I think this bug we should add some test case to cover it.

**Comment by hailin0** [comment]
image

**Comment by Hisoka-X** [comment]
Please merge from dev to fix engine-k8s-it

**Comment by hailin0** [comment]
image

**Review by Hisoka-X — COMMENTED** [review]
LGTM

**Review by Hisoka-X — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
