### PR TITLE
[Improve#1319] [code style] config module enables checkstyle 

### LINKED ISSUE #1319: [Improve] [code style] config module enables checkstyle
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

There is code that doesn't seem to meet the requirements of Code Style, but it is not checked out

image

### SeaTunnel Version

The latest (2.0.5-SNAPSHOT)

### SeaTunnel Config

```conf
N/A
```

### Running Command

```shell
N/A
```

### Error Exception

```log
N/A
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

Fixes #1319

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — COMMENTED** [review]
I think what you need to work out is why CI doesn't check ut, maybe you should look at the checkStyle file.

**Comment by asdf2014** [comment]
Hi @CalvinKirs, thanks for your comment. Indeed, I’m working on it, but this PR still can be merged, right. Also we should keep the relate issue open until the root cause has been located and solved.

**Comment by wuchunfu** [comment]
> Hi @CalvinKirs, thanks for your comment. Indeed, I’m working on it, but this PR still can be merged, right. Also we should keep the relate issue open until the root cause has been located and solved.

@asdf2014 I think it is still necessary to find out why ci is not checked, and then check and modify it as a whole. What do you think?

**Comment by asdf2014** [comment]
@wuchunfu Sure, if you say so

**Comment by asdf2014** [comment]
> I think what you need to work out is why CI doesn't check ut, maybe you should look at the checkStyle file.

@CalvinKirs The root cause is not about the checkStyle file but the pom file. After removed the skip configuration from pom file, the check style is working again. May I ask do you know the historical reason of adding the skip config here 😅  cc @wuchunfu

**Comment by CalvinKirs** [comment]
> > I think what you need to work out is why CI doesn't check ut, maybe you should look at the checkStyle file.
> 
> @CalvinKirs The root cause is not about the checkStyle file but the pom file. After removed the skip configuration from pom file, the check style is working again. May I ask do you know the historical reason of adding the skip config here 😅 cc @wuchunfu

This module is a modification of `typesafe`, so I want to keep the format as consistent (and `typesafe`) as possible, well, that might not be a big problem.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
