### PR TITLE
[Fix][Connector-V2][connector-file-base-hadoop] Fixed HdfsFile source load the krb5_path configuration

### PR DESCRIPTION
**Pull request by JeremyXin**
### Purpose of this pull request
This pull request fixed HdfsFile source load the krb5_path configuration
issues: #7867 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?

test cases in commit: add seatunnel-engine-examples test cases

use this seatunnel config in seatunnel-examples/seatunnel-engine-examples/src/main/resources/examples/fake_to_console.conf:

`
env {
  parallelism = 1
  job.mode = "BATCH"
}

source {
  HdfsFile {
    path = "/user/hive/test/dt=2024-10-15"
    file_format_type = "parquet"
    fs.defaultFS = "hdfs://hadoop"
    hdfs_site_path = "/local/hadoop/hdfs-site.xml"
    krb5_path = "/local/kerberos/krb5.conf"
    kerberos_principal = "xxx"
    kerberos_keytab_path = "/local/kerberos/xxx.keytab"
  }
}

sink {
  console {
  }
}
`

and debug SeaTunnelEngineExample.class，the value of hadoopConf can be seen at the breakpoint of the BaseHdfsFileSource class as shown in the following figure:
hadoopConfig

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi @JeremyXin , please run 'mvn spotless:apply' to fix code style before commit. Thanks

**Comment by JeremyXin** [comment]
Hi, @Hisoka-X , sry It's my fault.  I have ran 'mvn spotless:apply' and resubmitted. Thanks

**Comment by Hisoka-X** [comment]
Please do not commit code from `seatunnel-example`. 
image

**Comment by JeremyXin** [comment]
Hi, @Hisoka-X , I have removed this part of commit, please check. Thanks

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @JeremyXin !

**Review by hailin0 — APPROVED** [review]

**Comment by Hisoka-X** [comment]
The failure of the test case is not related to the current PR.

**Pull request merged**
