### PR TITLE
[Bugfix] [connector-jdbc] Fix when type is int and null value will always get 0 instead of null

### PR DESCRIPTION
**Pull request by choucmei**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by choucmei** [comment]
This PR was blocked by e2e because mysql e2e was losing data.
https://github.com/apache/seatunnel/issues/4732

**Comment by EricJoy2048** [comment]
What problem is this PR trying to solve? Do you need to modify the title?

**Comment by ic4y** [comment]
@EricJoy2048 Can you help figure out why there's no CI/CD?

**Comment by EricJoy2048** [comment]
Please fix CI error.

**Comment by EricJoy2048** [comment]
LGTM, Should you add e2e test to test this pr?

**Comment by choucmei** [comment]
> LGTM, Should you add e2e test to test this pr?


> LGTM, Should you add e2e test to test this pr?

I will add e2e testing as soon as possible

**Comment by hailin0** [comment]
@choucmei 
Please check ci error

**Pull request closed without merging**
