### PR TITLE
[Bugfix][Connector-V2][StarRocks]Fix StarRocks StreamLoad retry bug and fix doc

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request
1.
sink config：
7aa9d201e3d32d4fdf85a4c8e9ae120

import data result：
47c114e00d8d9335761063f3cfd6c6a

Reason of the error：

`Each retry uses a different tuple`.

After bug fix:

tip:  The starrocks e2e test has no check row count, so it passes the test.

2.
a8fd8b729926b529416a66967780ee3

Using log.warn is better for retry.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by FWLamb** [comment]
How did you know that the program ended? It did not end when I tested locally.

**Comment by TaoZex** [comment]
> How did you know that the program ended? It did not end when I tested locally.

Agree with you.

**Review by EricJoy2048 — APPROVED** [review]

**Review by 531651225 — APPROVED** [review]

**Comment by ic4y** [comment]
Nice work, you can also fix the e2e check row count by the way, or submit another pr to fix it.

**Review by ic4y — APPROVED** [review]
+1

**Comment by TaoZex** [comment]
> Nice work, you can also fix the e2e check row count by the way, or submit another pr to fix it.

Thanks for your advice: https://github.com/apache/incubator-seatunnel/pull/3421

**Pull request merged**
