### PR TITLE
[HotFix] [Remote Debug] Description When remote debug is enabled, the Seatunel Server 5801 port is not listening properly

### PR DESCRIPTION
**Pull request by hawk9821**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

OS： 
############## Kylin Linux Version #################
Release:
Kylin Linux Advanced Server release V10 (Lance)

Kernel:
4.19.90-52.36.v2207.ky10.x86_64

Build:
Kylin Linux Advanced Server
release V10 (SP3) /(Lance)-x86_64-Build23/20230324

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi, any detail for this bug? This seems to be a normal situation. When debug is paused, other threads will not respond.

**Comment by hawk9821** [comment]
> Hi, any detail for this bug? This seems to be a normal situation. When debug is paused, other threads will not respond.

When starting Seatunnel Server for the first time and turning on Debug (suspend=y), Seatunnel Server port 5801 listening exception

企业微信截图_17205951641472

**Comment by Hisoka-X** [comment]
Your commit history is messy. Please solve this problem. Thanks.

**Comment by hawk9821** [comment]
> Your commit history is messy. Please solve this problem. Thanks.

OK

**Pull request closed without merging**
