### PR TITLE
[Feature] add dockerfile

### LINKED ISSUE #5475: [Discuss] Dockerfile
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now we don't have the docker image, And seatunnel has a lots of connectors, most time user don't need all connector.

So I think we can have a base docker image (or only have fake and console connector). and give an example Dockerfile to download the needed connector.

### Usage Scenario

# Basic image Dockerfile
```
FROM eclipse-temurin:8-jre

RUN apt update ; \
    apt install -y wget ;

ARG version=2.3.2
ARG SEATUNNEL_HOME=/opt/seatunnel

# there I download from maven repo. It can be changed to copy from locally if we want build when release

RUN wget "https://archive.apache.org/dist/seatunnel/${version}/apache-seatunnel-${version}-bin.tar.gz" -P $SEATUNNEL_HOME && \
    cd $SEATUNNEL_HOME && \
    tar -zxvf apache-seatunnel-${version}-bin.tar.gz



```

# Example Re-Build Dockefile
```
FROM seatunnel-base-image

COPY bin/docker_install_plugin.sh /opt/seatunnel/install_plugin.sh
RUN chmod 777 /opt/seatunnel/install_plugin.sh && \
    ./opt/seatunnel/install_plugin.sh
```

### The connector install script:
```
#!/bin/bash

plugins=("connector-fake" "connector-console")
for item in "${plugins[@]}"; do
    wget https://repo1.maven.org/maven2/org/apache/seatunnel/${item}/${version}/${item}-${version}.jar -P /opt/seatunnel/connectors/seatunel
done

```

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
### Purpose of this pull request
close https://github.com/apache/seatunnel/issues/5475

add dockerfile, added `docker`, `docker-full` maven profile.
when use `docker` profile it will build the light docker image (only include fake, console connector) (image name will be `apache/seatunnel:<VERSION>`)
when use `docker-full` profile it will build the full connector docker image (image name will be `apache/seatunnel:<VERSION>-full`)

Now it need manually publish docker image to docker hub. 

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
with github action, added a new job, will run docker image and submit a job.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  3. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  4. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Could you retrigger there failed CI? Thanks.

**Comment by liunaijie** [comment]
> Could you retrigger there failed CI? Thanks.

me? I can't trigger the CI in this repo

**Comment by Hisoka-X** [comment]
Our CI runnning on your own fork repository, so you can retirgger it in your repository action.
image

**Comment by liunaijie** [comment]
> Our CI runnning on your own fork repository, so you can retirgger it in your repository action. image

Done.

**Comment by liunaijie** [comment]
@ruanwenjun @Hisoka-X  PTAL

**Review by FlechazoW — APPROVED** [review]
This document only for SeaTunnel Zeta and is more appropriately named docker_for_zeta.md

**Comment by liunaijie** [comment]
> This document only for SeaTunnel Zeta and is more appropriately named docker_for_zeta.md

Done

**Comment by liunaijie** [comment]
@FlechazoW i update the document add flink/spark engine. PTAL.

**Comment by FlechazoW** [comment]
You need to enable ci/cd first.

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
Same as https://github.com/apache/seatunnel/pull/5594#issuecomment-1757087541 .

**Comment by liunaijie** [comment]
@Hisoka-X the test result attached, 

image
image

**Comment by Hisoka-X** [comment]
Hi @liunaijie . Could you follow #5594 to add a test case for docker?

**Comment by liunaijie** [comment]
> Hi @liunaijie . Could you follow #5594 to add a test case for docker?

I add a test case on maven verify phase. run a command to verify.

**Comment by liunaijie** [comment]
One question: when i pakcage locally, i find the `starter` jar has version info. like `seatunnel-starter-2.3.3-SNAPSHOT.jar` not the format `seatunnel-starter.jar`. so when i submit job, it will get error. I manually change the `seatunnel.sh` script to pass the test in local. 
Does anyone know why the finnalName is without version but the jar still has version info.

**Comment by Hisoka-X** [comment]
> One question: when i pakcage locally, i find the `starter` jar has version info. like `seatunnel-starter-2.3.3-SNAPSHOT.jar` not the format `seatunnel-starter.jar`. so when i submit job, it will get error. I manually change the `seatunnel.sh` script to pass the test in local. Does anyone know why the finnalName is without version but the jar still has version info.

In my environment, these are not exist `seatunnel-starter-2.3.3-SNAPSHOT.jar` but only `seatunnel-starter.jar`. Where did you get `seatunnel-starter-2.3.3-SNAPSHOT.jar` jar?
image

**Comment by liunaijie** [comment]
> > One question: when i pakcage locally, i find the `starter` jar has version info. like `seatunnel-starter-2.3.3-SNAPSHOT.jar` not the format `seatunnel-starter.jar`. so when i submit job, it will get error. I manually change the `seatunnel.sh` script to pass the test in local. Does anyone know why the finnalName is without version but the jar still has version info.
> 
> In my environment, these are not exist `seatunnel-starter-2.3.3-SNAPSHOT.jar` but only `seatunnel-starter.jar`. Where did you get `seatunnel-starter-2.3.3-SNAPSHOT.jar` jar? image

package dist module, unzip `apache-seatunnel-2.3.3-SNAPSHOT-bin.tar.gz`.

**Comment by Hisoka-X** [comment]
image
Fine for me too.

**Comment by liunaijie** [comment]
> image Fine for me too.

It work well in CI phase https://github.com/liunaijie/seatunnel/actions/runs/6785810765/job/18475827132, maybe i have something change in my local i am not noticed.

**Comment by liunaijie** [comment]
> > image Fine for me too.
> 
> It work well in CI phase https://github.com/liunaijie/seatunnel/actions/runs/6785810765/job/18475827132, maybe i have something change in my local i am not noticed.

I re-run clean, install command in version 2.3.4-snapshot. it works for me.

**Comment by liunaijie** [comment]
@Hisoka-X @ruanwenjun @EricJoy2048 PTAL when you have time. when we push tag, it will build, verify, push docker image to docker hub.
Here is a successful job link for your refer: https://github.com/liunaijie/seatunnel/actions/runs/6811013504/job/18520474386.
and docker hub images generate by this job: https://hub.docker.com/r/liunaijie/seatunnel/tags

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by liunaijie** [comment]
removed action file, now it won't auto publish image to docker hub. when the release manager want publish image, he can package dist module with docker profile, the image will auto build, need manually publish.

**Comment by Hisoka-X** [comment]
cc @TyrantLucifer

**Comment by EricJoy2048** [comment]
@TyrantLucifer  PTAL

**Comment by liunaijie** [comment]
@EricJoy2048 @TyrantLucifer Do we need full connector docker image?
And I still want add github action to auto deploy docker image to docker hub.
For the case @TyrantLucifer mentioned, we will rollback/fix when review process find some bug. 
1. I am not clear about the pre-release process. but i think we can only monitor the tag/branch of finial tag/branch instand of pre-release tag/branch.
2. or we can delete the error image manually when we find bug

**Comment by liunaijie** [comment]
@Hisoka-X @hailin0 can you help take a look about this pr. 
add Dockerfile, we can build publish docker image to offical docker hub. 
user won't need build the image byself. and we also can include all lib to image user can skip the install plugin step.

**Pull request closed without merging**
