### PR TITLE
[Feature][core] Use different command to execute task #1421

### LINKED ISSUE #1421: [Feature][core] Use different command to execute task
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Now, we have several tasks in Seatunnel, e.g. `check conf`, `execute a spark task`, `execute a flink task`.

In the future, we may have more task. It's better to use different command class to execute different task, rather then write all the code in `Seatunnel.java`.

A solution is creating a target command for each task, and execute the task by command.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ruanwenjun**
close #1421 

## Purpose of this pull request

More details see #1421 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@wuchunfu Take a look? If you are interested.

**Comment by wuchunfu** [comment]
Looks good overall, but I would say it's better to discuss this change next time, @CalvinKirs PTAL, thanks

**Comment by ruanwenjun** [comment]
> Looks good overall, but I would say it's better to discuss this change next time, @CalvinKirs PTAL, thanks

Yeal, I got, it's important to discuss beforehand.

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
