### PR TITLE
[hotfix][starter][flink] Fix inject invalid jar into config throw FileNotFoundException

### PR DESCRIPTION
**Pull request by hailin0**
## Purpose of this pull request

Currently only thrown when the example is running.

Fixed PR #2982 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
image

**Comment by hailin0** [comment]
@liugddx @iture123 th. PTAL

**Review by TyrantLucifer — APPROVED** [review]
+1

**Review by ashulin — APPROVED** [review]
LGTM

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by hailin0** [comment]
image

**Comment by Hisoka-X** [comment]
> image

This is a bug which fixed by #3216

**Review by iture123 — COMMENTED** [review]
LGTM.

**Pull request merged**
