### PR TITLE
[Chore][Transforms-v2][ZetaSQLEngine] Remove redundancy code in validateSQL

### PR DESCRIPTION
**Pull request by CheneyYin**
## Purpose of this pull request
Remove redundancy code and useless placeholder in `org.apache.seatunnel.transform.sqlengine.zeta.ZetaSQLEngine#validateSQL`.
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
cc @rewerma PTAL

**Review by hailin0 — APPROVED** [review]

**Comment by CheneyYin** [comment]
In check of  [c20dc0c](https://github.com/apache/incubator-seatunnel/pull/4506/commits/c20dc0ce4b2e24425b604a7fd193aaa93e4865ce), CI can't to start kafka container successfully. @hailin0 
```shell
2023-04-06T10:53:44.4485294Z 2023-04-06 10:53:44,440 INFO  🐳 [confluentinc/cp-kafka:6.2.1] - Container confluentinc/cp-kafka:6.2.1 is starting: 373a19547300b388edf857a93e8489b23f7c7fd3d6dea71d95e1bcf6be775c59
2023-04-06T10:53:44.5399924Z 2023-04-06 10:53:44,532 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - Could not start container
2023-04-06T10:53:44.5400936Z com.github.dockerjava.api.exception.InternalServerErrorException: Status 500: {"message":"driver failed programming external connectivity on endpoint trusting_ramanujan (cafffed0ddbc71d393841a678ab78161323c00c2b3e200eaa6adde76875c9e1f): Bind for 0.0.0.0:9093 failed: port is already allocated"}
2023-04-06T10:53:44.5401794Z 
2023-04-06T10:53:44.5402505Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:247) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5403685Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.post(DefaultInvocationBuilder.java:102) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5405478Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:31) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5406642Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:13) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5407813Z 	at org.testcontainers.shaded.com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5408914Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5410352Z 	at org.testcontainers.shaded.com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:43) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5411367Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:441) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5412236Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5413080Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
2023-04-06T10:53:44.5414125Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5415495Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322) ~[testcontainers-1.17.6.jar:1.17.6]
2023-04-06T10:53:44.5416153Z 	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) [?:?]
2023-04-06T10:53:44.5416742Z 	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
2023-04-06T10:53:44.5417315Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
2023-04-06T10:53:44.5417903Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
2023-04-06T10:53:44.5418374Z 	at java.lang.Thread.run(Thread.java:829) [?:?]
2023-04-06T10:53:44.5448871Z 2023-04-06 10:53:44,544 ERROR 🐳 [confluentinc/cp-kafka:6.2.1] - There are no stdout/stderr logs available for the failed container
2023-04-06T10:53:44.6706825Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 20.093 s <<< FAILURE! - in org.apache.seatunnel.e2e.connector.kafka.KafkaIT
2023-04-06T10:53:44.6711775Z [ERROR] org.apache.seatunnel.e2e.connector.kafka.KafkaIT  Time elapsed: 20.093 s  <<< ERROR!
2023-04-06T10:53:44.6712672Z java.util.concurrent.CompletionException: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2023-04-06T10:53:44.6739698Z Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
2023-04-06T10:53:44.6741432Z Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception
2023-04-06T10:53:44.6742088Z Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
2023-04-06T10:53:44.6742740Z Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: 
2023-04-06T10:53:44.6743521Z Status 500: {"message":"driver failed programming external connectivity on endpoint trusting_ramanujan (cafffed0ddbc71d393841a678ab78161323c00c2b3e200eaa6adde76875c9e1f): Bind for 0.0.0.0:9093 failed: port is already allocated"}
2023-04-06T10:53:44.6744051Z 
2023-04-06T10:53:44.6744127Z 
2023-04-06T10:53:45.0455089Z [INFO] 
2023-04-06T10:53:45.0455597Z [INFO] Results:
2023-04-06T10:53:45.0455941Z [INFO] 
2023-04-06T10:53:45.0468838Z [ERROR] Errors: 
2023-04-06T10:53:45.0528537Z [ERROR]   KafkaIT » Completion org.testcontainers.containers.ContainerLaunchException: C...
```

**Review by Hisoka-X — APPROVED** [review]

**Comment by CheneyYin** [comment]
Fail to start Kafka container. Please restart it at your leisure. Thanks. @Hisoka-X

**Comment by Hisoka-X** [comment]
> Fail to start Kafka container. Please restart it at your leisure. Thanks. @Hisoka-X

Never mind, the error not belong the change from this.

**Pull request merged**
