### PR TITLE
[Feature][Scripts] Throw exception in start scripts when config file not exist

### LINKED ISSUE #1467: [Feature][Scripts] Throw exception in start scripts when config file not exist
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Before:
image

After:
image

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
Before:
image

After:
image

closed #1467

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by simon824** [comment]
@CalvinKirs @wuchunfu ,PTAL thanks.

**Comment by wuchunfu** [comment]
I also had this problem strangely yesterday, and I haven't had time to see where the problem is.

**Comment by CalvinKirs** [comment]
@BenJFan ,Hi PTAL,thx

**Comment by Hisoka-X** [comment]
Only one question: Why doesn't do this thing in java side? Will only change once in java side, easier to maintain.

**Comment by simon824** [comment]
> Only one question: Why doesn't do this thing in java side? Will only change once in java side, easier to maintain.

hi @BenJFan , IMO, it's better to judge these basic parameters in the scripts, which is more efficient and reducing the overhead of starting jvm. Regarding the redundancy, I am considering merging the startup scripts to solve it.

**Comment by Hisoka-X** [comment]
@CalvinKirs LGTM

**Review by Hisoka-X — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
