### PR TITLE
[Hotfix][st-engine] Fix client cannot be stopped when submit jobs to cluster exception

### PR DESCRIPTION
**Pull request by hailin0**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
@ashulin @Hisoka-X @EricJoy2048 PTAL

**Comment by hailin0** [comment]
企业微信截图_dda7b74d-5ae9-4ca5-8041-c1ec0392af7d

**Comment by Hisoka-X** [comment]
Check out #3142

**Comment by hailin0** [comment]
> #3142

**Pull request closed without merging**
