### PR TITLE
[Improve][Connector-v2][HdfsSink]Different NS causes the HdfsSink rename operation to fail.

### PR DESCRIPTION
**Pull request by lightzhao**
### What happen
If tmp_path and path are not in the same namespace, the rename operation will fail.
image

### Solution
By default, tmp_path is set to path to ensure that cross-Namespace problems do not occur.
### Test
image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
You can set temp_path to solve this problem, BTW, are you sure your change is right?

image

**Comment by lightzhao** [comment]
> You can set temp_path to solve this problem, BTW, are you sure your change is right?
> 
> image

By default, the tmp path should be set as a subdirectory of the path to avoid cross ns issues. I believe it is a more recommended approach, and I have completed testing to confirm that this is not a problem

**Comment by TyrantLucifer** [comment]
IMO, this pull request is not make sense, now temp_path is configuable so I will close it, if you have any questions please send an email to dev@seatunnel.apache.org and start a discussion with this.

image

**Comment by lightzhao** [comment]
Of course, the tmp path can be set, but the default configuration should be a more reasonable one. I think there are potential bugs in the current default configuration, and I will initiate discussions in the future.

**Comment by TCoherence** [comment]
@TyrantLucifer I didn't find this tmp_path actually in the doc which is hidden from the real user/developer. Also could you elaborate more why moving tmp folder under the same subdir where "path" is set. AFAIK cross namespace issue might have a higher possibility to happen...

**Pull request closed without merging**
