### PR TITLE
[Api-draft] Add spark example

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
 Add spark example

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@BenJFan Need to add dependency license.

**Comment by Hisoka-X** [comment]
> @BenJFan Need to add dependency license.

It's weird, I didn't add any dependency. I will check it out.

**Comment by ruanwenjun** [comment]
You can try to add orc-shims-1.5.2.jar

**Comment by ruanwenjun** [comment]
I merge this first, I will add the dependency in notice.

**Pull request merged**
