### PR TITLE
[Improve][connector]Singleton mode should be more optimized for write creation clients

### PR DESCRIPTION
**Pull request by zhilinli123**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by Hisoka-X — COMMENTED** [review]
Is there any proof that this problem has occurred? In fact, this worry is a bit unnecessary, because the write method will not be called concurrently, and the write method in the same writer will always be invoked only one write at same time.

**Comment by zhilinli123** [comment]
> Is there any proof that this problem has occurred? In fact, this worry is a bit unnecessary, because the write method will not be called concurrently, and the write method in the same writer will always be invoked only one write at same time.

image
I see, but I think it's more elegant than before!
@Hisoka-X

**Comment by Hisoka-X** [comment]
> I see, but I think it's more elegant than before!

I personally feel that this change is currently unnecessary. It does not improve the running logic, but only adds extra burden.

**Comment by zhilinli123** [comment]
Okay, thanks for the review and I'll shut it down

**Pull request closed without merging**
