### PR TITLE
[bug] fix flink-translate lost the dependency commons-io

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

the flink-v2-example will exec error, because it lost the dependency commons-io
and the dependency has in the file known-dependencies.txt.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by laglangyue** [comment]
image


image

**Comment by laglangyue** [comment]
when I add the commons-io,it's ok

**Comment by laglangyue** [comment]
it't not need to add license,because it exist.

**Comment by TyrantLucifer** [comment]
Please check dependencies list, if you add extra dependencies in project please add it in `know-denpencies.txt`. BTW, you can exeute `bash tools/dependencies/checkLicense.sh` in shell and check it.

**Comment by CalvinKirs** [comment]
Could you retest after updating the code? No clear log, but it's ok on my local

**Pull request closed without merging**
