### PR TITLE
[SeaTunnel #1040] Add success message for CheckResult by Constants.CHECK_SUCCESS 

### LINKED ISSUE #1040: [Feature][common] Add success message for `CheckResult` by Constants.CHECK_SUCCESS
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Add success message for `CheckResult` by Constants.CHECK_SUCCESS

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request
closes #1040 
Add success message for CheckResult by Constants.CHECK_SUCCESS 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by yx91490** [comment]
I think better to put a constant CheckResult instance 'CHECK_SUCCESS' to CheckResult.

**Comment by simon824** [comment]
> I think better to put a constant CheckResult instance 'CHECK_SUCCESS' to CheckResult.

Thanks for your reply, I think constants are managed together by `Constants`  maybe better.

**Comment by simon824** [comment]
Hi @CalvinKirs , can you help to solve the `CodeQL` problem, Thx.

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs , can you help to solve the `CodeQL` problem, Thx.

hi,rerun

**Review by RickyHuo — APPROVED** [review]
LGTM

**Pull request merged**
