### PR TITLE
[BUG][Connector-V2] Fixed an exception in excel reading data

### PR DESCRIPTION
**Pull request by mrliufox**
### Purpose of this pull request
Fix the following two issues：
[1]An exception was thrown when importing an empty cell
[2]If multiple rows of data are imported, all the data is the last row

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Import excel with multiple pieces of data and empty cells to verify that the data can be successfully imported

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi @mrliufox , please follow the guide to open CI on your fork repository. Thanks. https://github.com/apache/seatunnel/pull/5886/checks?check_run_id=18875206748

**Review by Hisoka-X — COMMENTED** [review]
Could you add a test case for this? Thanks

**Comment by mrliufox** [comment]
> open CI on your fork repository

i have opened CI on your fork repository

**Comment by Hisoka-X** [comment]
Please do not use dev as your feature branch. Just create an branch from dev like `fix-excel-exception`, then create an PR for it.
image.
BTW, seem like the action not enable for now. 
image

**Comment by EricJoy2048** [comment]
Hi, @mrliufox  Is there any new progress in the pr?

**Pull request closed without merging**
