### PR TITLE
[Connector-V2][jdbc-connector] add license

### PR DESCRIPTION
**Pull request by ic4y**
Add the source code dependency of JDBC on some files of flink

related #2397

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — CHANGES_REQUESTED** [review]
Flink is the AL2 license. you copied a lot of code, you should keep the other party's NOTICE in your NOTICE.

**Comment by ic4y** [comment]
@CalvinKirs I added, is that correct?

**Comment by CalvinKirs** [comment]
> @CalvinKirs I added, is that correct?

Source code NOTICE also.

**Comment by ic4y** [comment]
@CalvinKirs ok i added.

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
