### PR TITLE
[Feature] [docs] File format and translation

### PR DESCRIPTION
**Pull request by jj551**
modify https://github.com/apache/incubator-seatunnel/tree/dev/docs file format andtranslation

### CODE REVIEW

**Comment by xleoken** [comment]
hi @Kodalien, please rename the title of the patch.

**Comment by jj551** [comment]
> hi @Kodalien, please rename the title of the patch.



> hi @Kodalien, please rename the title of the patch.

@leo65535 revised

**Comment by CalvinKirs** [comment]
Please check deadlink

**Comment by CalvinKirs** [comment]
Can you describe what changes you made in this PR?

**Comment by Kodalien** [comment]
> Can you describe what changes you made in this PR?

/docs/zh-cn/translation @Kodalien

**Comment by jj551** [comment]
> 你能描述一下你在这个 PR 中做了哪些改变吗？

/docs !!!! translation @CalvinKirs

**Comment by xleoken** [comment]
@CalvinKirs, seems the network of the github action is unstable.

image

**Comment by asdf2014** [comment]
Hi @Kodalien, it seems that there are some dead links, would you please fix them to pass the CI, thanks

image

**Comment by jj551** [comment]
> Hi @Kodalien, it seems that there are some dead links, would you please fix them to pass the CI, thanks
> 
> image

@asdf2014 I close this pr and resubmit a new pr

**Pull request closed without merging**
