### PR TITLE
[Bug][Connector] Fix Flink ConsoleSink not printing results

### PR DESCRIPTION
**Pull request by simon824**
## Purpose of this pull request

Fix Flink ConsoleSink not printing results

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by simon824** [comment]
cc @mans2singh @ruanwenjun

**Review by ruanwenjun — COMMENTED** [review]
This can work, but I would like to print the cord in `writeRecord(Row record)` method, this might be the right hook method of `OutputFormat`.

**Comment by simon824** [comment]
> This can work, but I would like to print the cord in `writeRecord(Row record)` method, this might be the right hook method of `OutputFormat`.

Yes i tried this method, it works, but `System.out.println` will trigger checkStyle exception.

**Comment by ruanwenjun** [comment]
> 

Ok, I understand, it's ok to use print directly, since this sink plugin is just used in test case in most of the cases.

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by wuchunfu** [comment]
Well done

**Pull request merged**
