### PR TITLE
[Bug][flink-connector-jdbc]fix jdbc partition coloumn sql error

### PR DESCRIPTION
**Pull request by tobezhou33**
## Purpose of this pull request

fix the jdbc add partition column then splicing the sql error because the quotation marks use error

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@BenJFan Please take a look, thanks.

**Comment by ruanwenjun** [comment]
Can we add UT or IT to cover this case?

**Comment by Hisoka-X** [comment]
> Can we add UT or IT to cover this case?

Argge with this.

**Comment by BenJFan** [comment]
> Can we add UT or IT to cover this case?
Argge with this.

**Comment by tobezhou33** [comment]
i add ut for jdbcsource  to test extendPartitionQuerySql method

**Comment by Hisoka-X** [comment]
Hi, in #1781 flink-jdbc connector use different way to support partition. So this PR maybe not neccessy, but you can review it and make your contribute on it.

**Pull request closed without merging**
