### PR TITLE
[Bug][CDC][E2E] Fix mysql-cdc e2e error #4944

### PR DESCRIPTION
**Pull request by zhilinli123**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by zhilinli123** [comment]
@hailin0 @Hisoka-X PTAL Thanks
image

**Comment by liugddx** [comment]
I have fixed it in this pr. https://github.com/apache/seatunnel/pull/4936

**Comment by zhilinli123** [comment]
> Member



> I have fixed it in this pr. #4936
+1,
https://github.com/apache/seatunnel/pull/4923

**Comment by zhilinli123** [comment]
> I have fixed it in this pr. #4936
It looks like this Pr fixes the document, how about you make a separate fix cdc or use the current pr to fix the e2e issue?

**Comment by zhilinli123** [comment]
PTAL: @hailin0 @Hisoka-X @ic4y  thks

**Comment by Hisoka-X** [comment]
deplicate of #4936 , thanks for your contribute.

**Pull request closed without merging**
