### PR TITLE
[Feature][API]Flink interface upgrade (#1313)

### PR DESCRIPTION
**Pull request by suxinshuo**
## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by suxinshuo** [comment]
Hi PTAL.Thx. @CalvinKirs @nielifeng

**Comment by CalvinKirs** [comment]
@leo65535 Hi,PTAL,thx

**Comment by xleoken** [comment]
Thanks @xsaffable, will check this.

**Comment by CalvinKirs** [comment]
no updates, if you have any updates, you can leave a message, and I will reopen it.

**Pull request closed without merging**
