### PR TITLE
[Feature]Rename seatunnel-engine module

### PR DESCRIPTION
**Pull request by kanha-gupta**
issue: https://github.com/apache/incubator-seatunnel/issues/3857
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by kanha-gupta** [comment]
Hi ! I have changed the pom files, let me know if Module & package name change is also required.
I tried to do that & due to entire codebase refactoring around 400 files were being deleted & regenerated therefore i resorted to changing only the pom files.
If needed, please suggest if that amount of file change is acceptable & if not, then please suggest what to do to avoid that. 
Would happily do that too if required
Thank you :)

**Comment by CalvinKirs** [comment]
Do we need to change the package name? @EricJoy2048

**Comment by kanha-gupta** [comment]
@EricJoy2048 Hello, can you please review this pr ?

**Comment by EricJoy2048** [comment]
> Do we need to change the package name? @EricJoy2048

I think package name need update too.

**Comment by EricJoy2048** [comment]
> Hi ! I have changed the pom files, let me know if Module & package name change is also required.
> I tried to do that & due to entire codebase refactoring around 400 files were being deleted & regenerated therefore i resorted to changing only the pom files.
> If needed, please suggest if that amount of file change is acceptable & if not, then please suggest what to do to avoid that.
> Would happily do that too if required
> Thank you :)

I think module and package name need update too. I believe that our CI can guarantee the quality of the code, and you can do it with confidence.

**Pull request closed without merging**
