### PR TITLE
[Bugfix] [REST-API] Fixed the problem that the return list is empty due to no status parameters

### LINKED ISSUE #6037: [Bug] [REST-API] Cannot get finished job status with new api `/hazelcast/rest/maps/finished-jobs/:state`
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I build seatunnel pacakge with latest dev branch to test new merged [rest -api-feature ](https://github.com/apache/seatunnel/pull/5949).

After I run the job, when I call `/hazelcast/rest/maps/finished-jobs/:state` only 204 returned.

### SeaTunnel Version

latest dev branch 

### SeaTunnel Config

```conf
env {
  execution.parallelism = 1
  job.mode = "BATCH"
}

source {
  FakeSource {
    result_table_name = "fake1"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
        created_time = "timestamp"
        destroyed_time = "timestamp"
      }
    }
  }
}

transform {


    SQL {
    source_table_name = "fake1"
    result_table_name = "fake2"
    query = "SELECT name, age, created_time, destroyed_time, CURRENT_DATE() today, DATEDIFF(created_time, destroyed_time, 'SECOND') duration FROM fake1 "
  }

  SQL {
    source_table_name = "fake2"
    result_table_name = "fake3"
    query = "SELECT name, age, today, duration FROM fake2 "
  }
}

sink {
  Console {
    source_table_name = "fake3"
  }
}
```

### Running Command

```shell
bin/seatunnel.sh -c config/demo.conf
```

### Error Exception

```log
no exception
```

### Zeta or Flink or Spark Version

Zeta

### Java or Scala Version

_No response_

### Screenshots

api call

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
### Purpose of this pull request

close #6037

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

Already covered

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by sheng-jie** [comment]
I passed the state parameter in the url actually: `http://localhost:5801/hazelcast/rest/maps/finished-jobs/FINISHED`.

So this fix may not solve the bug #6037 .

**Comment by liugddx** [comment]
> I passed the state parameter in the url actually: `http://localhost:5801/hazelcast/rest/maps/finished-jobs/FINISHED`.
> 
> So this fix may not solve the bug #6037 .

Can you send the specific error message?

**Comment by sheng-jie** [comment]
> > I passed the state parameter in the url actually: `http://localhost:5801/hazelcast/rest/maps/finished-jobs/FINISHED`.
> > 
> > So this fix may not solve the bug #6037 .
> 
> Can you send the specific error message?
> 

Sorry for my mistake, it's ok now.Thanks
.

**Comment by sheng-jie** [comment]
I found another issue: The metrics were not serialized in CamelCase format.


```
curl --location --request GET 'http://seatunnel-svc:5801/hazelcast/rest/maps/finished-jobs/FINISHED' \
--header 'User-Agent: Apifox/1.0.0 (https://www.apifox.cn)' \
--header 'Accept: */*' \
--header 'Host: seatunnel-svc:5801' \
--header 'Connection: keep-alive'

[
    {
        "jobId": "790041833823535105",
        "jobName": "fake-to-console",
        "jobStatus": "FINISHED",
        "errorMsg": null,
        "createTime": "2023-12-21 02:24:11",
        "finishTime": "2023-12-21 02:24:13",
        "jobDag": {
            "jobId": 790041833823535105,
            "pipelineEdges": {
                "1": [
                    {
                        "inputVertexId": 1,
                        "targetVertexId": 2
                    }
                ]
            },
            "vertexInfoMap": {
                "1": {
                    "vertexId": 1,
                    "type": "SOURCE",
                    "connectorType": "pipeline-1 [Source[0]-FakeSource]"
                },
                "2": {
                    "vertexId": 2,
                    "type": "SINK",
                    "connectorType": "pipeline-1 [Sink[0]-Console-MultiTableSink]"
                }
            }
        },
        "metrics": {
            "SourceReceivedCount": "10000",
            "SinkWriteCount": "10000"
        }
    }
]
```

**Comment by liugddx** [comment]
> I found another issue: The metrics were not serialized in CamelCase format.
> 
> ```
> curl --location --request GET 'http://seatunnel-svc:5801/hazelcast/rest/maps/finished-jobs/FINISHED' \
> --header 'User-Agent: Apifox/1.0.0 (https://www.apifox.cn)' \
> --header 'Accept: */*' \
> --header 'Host: seatunnel-svc:5801' \
> --header 'Connection: keep-alive'
> 
> [
>     {
>         "jobId": "790041833823535105",
>         "jobName": "fake-to-console",
>         "jobStatus": "FINISHED",
>         "errorMsg": null,
>         "createTime": "2023-12-21 02:24:11",
>         "finishTime": "2023-12-21 02:24:13",
>         "jobDag": {
>             "jobId": 790041833823535105,
>             "pipelineEdges": {
>                 "1": [
>                     {
>                         "inputVertexId": 1,
>                         "targetVertexId": 2
>                     }
>                 ]
>             },
>             "vertexInfoMap": {
>                 "1": {
>                     "vertexId": 1,
>                     "type": "SOURCE",
>                     "connectorType": "pipeline-1 [Source[0]-FakeSource]"
>                 },
>                 "2": {
>                     "vertexId": 2,
>                     "type": "SINK",
>                     "connectorType": "pipeline-1 [Sink[0]-Console-MultiTableSink]"
>                 }
>             }
>         },
>         "metrics": {
>             "SourceReceivedCount": "10000",
>             "SinkWriteCount": "10000"
>         }
>     }
> ]
> ```

Thanks for reminding me, I will enrich the metrics in another PR.

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by EricJoy2048** [comment]
> > I found another issue: The metrics were not serialized in CamelCase format.
> > ```
> > curl --location --request GET 'http://seatunnel-svc:5801/hazelcast/rest/maps/finished-jobs/FINISHED' \
> > --header 'User-Agent: Apifox/1.0.0 (https://www.apifox.cn)' \
> > --header 'Accept: */*' \
> > --header 'Host: seatunnel-svc:5801' \
> > --header 'Connection: keep-alive'
> > 
> > [
> >     {
> >         "jobId": "790041833823535105",
> >         "jobName": "fake-to-console",
> >         "jobStatus": "FINISHED",
> >         "errorMsg": null,
> >         "createTime": "2023-12-21 02:24:11",
> >         "finishTime": "2023-12-21 02:24:13",
> >         "jobDag": {
> >             "jobId": 790041833823535105,
> >             "pipelineEdges": {
> >                 "1": [
> >                     {
> >                         "inputVertexId": 1,
> >                         "targetVertexId": 2
> >                     }
> >                 ]
> >             },
> >             "vertexInfoMap": {
> >                 "1": {
> >                     "vertexId": 1,
> >                     "type": "SOURCE",
> >                     "connectorType": "pipeline-1 [Source[0]-FakeSource]"
> >                 },
> >                 "2": {
> >                     "vertexId": 2,
> >                     "type": "SINK",
> >                     "connectorType": "pipeline-1 [Sink[0]-Console-MultiTableSink]"
> >                 }
> >             }
> >         },
> >         "metrics": {
> >             "SourceReceivedCount": "10000",
> >             "SinkWriteCount": "10000"
> >         }
> >     }
> > ]
> > ```
> 
> Thanks for reminding me, I will enrich the metrics in another PR.

Please create an issue for it, let us not lost it.

**Review by Hisoka-X — COMMENTED** [review]
please add test case to avoid regression.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
