### PR TITLE
Self-Achieved Redis Proxy which is not support redis function of "info replication"

### PR DESCRIPTION
**Pull request by chocolateBlack**
https://github.com/apache/incubator-seatunnel/issues/2150

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by wuchunfu — COMMENTED** [review]
@chocolateBlack Please add license header, thx.

**Comment by chocolateBlack** [comment]
> @chocolateBlack Please add license header, thx.
@wuchunfu  licence header is added , is that ok?  please do me a favor to check it 
@wuchunfu  please approve running workflows, thanks a lot

**Comment by wuchunfu** [comment]
@chocolateBlack Please update the relevant documentation, thanks.

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by CalvinKirs** [comment]
Could you check connector-v2? does it have this feature?

**Comment by chocolateBlack** [comment]
> Could you check connector-v2? does it have this feature?

@CalvinKirs There is no Redis Sink in connector-v2. 
what's the different between v1 and v2. Is there any docs for us to learn the purpose and details of v2.

**Pull request merged**
