### PR TITLE
[Improve][Connector-v2-jdbc] Support for specify number of partitions when parallel reading

### PR DESCRIPTION
**Pull request by hailin0**
## Purpose of this pull request

example:
e.g: partition_lower_bound = 1, partition_upper_bound = 20
  - partition_num = 2 
    - output:
      -  partition-1 {start=1, end=10} 
      - partition-2 {start=11, end=20}
  - partition_num = 4 
    - output: 
      - partition-1 {start=1, end=5} 
      - partition-2 {start=6, end=10} 
      - partition-3 {start11, end=15} 
      - partition-4 {start=16, end=20}

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Can you add test case to prove  that `partition_num` can work fine?

**Comment by liugddx** [comment]
@ashulin Is this PR done at the operator level? cc: @hailin0 #2965

**Comment by ashulin** [comment]
@liugddx partition_num and parallelism are not the same: 
parallelism defines the number of readers, 
and partition_num defines the number of splits.

For tables with hundreds of millions of levels, this function is necessary, because the number of readers cannot be expanded indefinitely.

**Review by ashulin — DISMISSED** [review]
LGTM, @ic4y CC

**Comment by liugddx** [comment]
> @liugddx partition_num and parallelism are not the same: parallelism defines the number of readers, and partition_num defines the number of splits.
> 
> For tables with hundreds of millions of levels, this function is necessary, because the number of readers cannot be expanded indefinitely.

I see. Thank you.

**Review by EricJoy2048 — DISMISSED** [review]
+1

**Review by EricJoy2048 — APPROVED** [review]
+1

**Review by ashulin — APPROVED** [review]

**Pull request merged**
