### PR TITLE
[Bugfix][Zeta] Fix job dag parse

### PR DESCRIPTION
**Pull request by liugddx**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liugddx** [comment]
image

Change the collection order.

**Review by lightzhao — DISMISSED** [review]

**Comment by TyrantLucifer** [comment]
#4369 has passed all test cases. It seems ths pull request is not make sense.

**Comment by TyrantLucifer** [comment]
> #4369 has passed all test cases. It seems ths pull request is not make sense.

cc @EricJoy2048 @hailin0

**Comment by liugddx** [comment]
> > #4369 has passed all test cases. It seems ths pull request is not make sense.
> 
> cc @EricJoy2048 @hailin0
image
I search for the next, as if no test log. Is this test not printing any logs or not executing?

**Comment by liugddx** [comment]
image

I found a strange problem, the test case fails but passes normally

https://github.com/apache/incubator-seatunnel/actions/runs/4485929422/jobs/7889738474?pr=4369#step:4:22169

**Comment by liugddx** [comment]
> image
> 
> I found a strange problem, the test case fails but passes normally
> 
> https://github.com/apache/incubator-seatunnel/actions/runs/4485929422/jobs/7889738474?pr=4369#step:4:22169

@TyrantLucifer @EricJoy2048 @Hisoka-X @hailin0

**Pull request closed without merging**
