### PR TITLE
[Feature][Zeta] Improve local mode startup request ports

### LINKED ISSUE #4607: [Feature][Zeta] Improve local mode startup request ports
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Local mode automatically sets the hazelcast startup port to `auto-increment`

local mode startup example
```shell
bin/seatunnel.sh -m local -config job.file
```

reference
https://github.com/apache/incubator-seatunnel/blob/dev/config/hazelcast.yaml#L34

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liunaijie**
## Purpose of this pull request

close #4607

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liunaijie** [comment]
@hailin0 please help review, thanks.

**Comment by hailin0** [comment]
@Hisoka-X @EricJoy2048

**Comment by Hisoka-X** [comment]
Can you add test case for this change? Like use e2e create two local mode job in one container at same time.

**Comment by hailin0** [comment]
> Can you add test case for this change? Like use e2e create two local mode job in one container at same time.

good idea

**Comment by liunaijie** [comment]
image
image


```
./bin/seatunnel.sh --config ./config/v2.batch.config.template -e local
```
i run this command with zeta engine, it shows successful

**Pull request closed without merging**
