### PR TITLE
[Connector-V2][Doc]add new socket source doc

### PR DESCRIPTION
**Pull request by zhuangchong**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Hi, I can't know the data format which I should send to socket if I only read this doc. Maybe you can add some data example.

**Comment by zhuangchong** [comment]
> Hi, I can't know the data format which I should send to socket if I only read this doc. Maybe you can add some data example.

ok

**Comment by zhuangchong** [comment]
@Hisoka-X @CalvinKirs please help with code review.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
