### PR TITLE
[Fix][KuduCatalogFactory]: Fix KuduCatalogFactory.optionRule() will throw an Exception

### PR DESCRIPTION
**Pull request by Jetiaime**
### Purpose of this pull request

Fix `KuduCatalogFactory.optionRule()` will throw an Exception because conditional OptionRule should be in the optinal or required options.

### Does this PR introduce _any_ user-facing change?

No.

### How was this patch tested?

Covered By the Tests

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Carl-Zhou-CN** [comment]
@Jetiaime hi, Follow these steps to resolve the error
image

**Comment by Hisoka-X** [comment]
same as https://github.com/apache/seatunnel/pull/6788#issuecomment-2095108195

**Comment by Hisoka-X** [comment]
Could you add test case like https://github.com/apache/seatunnel/blob/4d9287fce4943a30e31e5dbda013c1cee17034ab/seatunnel-connectors-v2/connector-elasticsearch/src/test/java/org/apache/seatunnel/connectors/seatunnel/elasticsearch/ElasticsearchFactoryTest.java#L26 ?

**Comment by Jetiaime** [comment]
> Could you add test case like
> 
> https://github.com/apache/seatunnel/blob/4d9287fce4943a30e31e5dbda013c1cee17034ab/seatunnel-connectors-v2/connector-elasticsearch/src/test/java/org/apache/seatunnel/connectors/seatunnel/elasticsearch/ElasticsearchFactoryTest.java#L26
> 
> ?

thx, test has been added.

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passed.

**Review by Carl-Zhou-CN — APPROVED** [review]
+1

**Pull request merged**
