### PR TITLE
[Feature] [transform]  Add concat transform for Spark plugins

### LINKED ISSUE #1165: [Feature][Transform] Add concat transform for Spark plugins
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

# Transform plugin : Concat [Spark]

## Description

Concat additional string according to `addition`

## Options

| name           | type   | required | default value       |
| -------------- | ------ | -------- | ------------------- |
| addition       | string | no       | `""` (Empty String) |
| source_field   | string | no       | `raw_message`       |
| target_field   | string | no       | `__root__`          |
| common-options | string | no       | -                   |

### addition [string]

The additional string will be concated to the source field. The default addition is a empty string `("")` .

### source_field [string]

The source field of the string before being concated, if not configured, the default is `raw_message`.

### target_field [string]

The target field of the string after being concated, if not configured, the default is `__root__`.

### common options [string]

Transform plugin common parameters, please refer to [Transform Plugin](./transform-plugin.md) for details

## Examples

```bash
concat {
  fields = ["msg"]
  addition = "+++++"
}
```

```bash
concat {
  fields = ["msg"]
  addition = "+++++"
  source_field = "raw_message"
  target_field = "msg_concat"
}
```

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

Fixes #1165

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by RickyHuo** [comment]
Compare with the spark built-in function concat `https://spark.apache.org/docs/latest/api/sql/index.html#concat`, the transform of concat is too simply.

**Comment by asdf2014** [comment]
Hi @RickyHuo, thanks for your comment. Indeed, this is the first version, and I will continue to strengthen the functions according to the link you provided in following PRs, and strive to be better than it 😄

**Comment by CalvinKirs** [comment]
@leo65535 Hi, PTAL thx

**Comment by wuchunfu** [comment]
> Hi @RickyHuo, thanks for your comment. Indeed, this is the first version, and I will continue to strengthen the functions according to the link you provided in following PRs, and strive to be better than it 😄

Can you tell me about your plan, thanks

**Comment by asdf2014** [comment]
@wuchunfu Maybe later I will create a umbrella issues to show the details

**Comment by asdf2014** [comment]
@wuchunfu I’m so glad you start reviewing PR again, may I ask is there any other comments about this?

**Comment by asdf2014** [comment]
@wuchunfu And there are lots of PR I submitted, you are welcome to take a look, thanks https://github.com/apache/incubator-seatunnel/pulls/asdf2014

**Pull request closed without merging**
