### PR TITLE
[Improve][Doc] Add IMap OSS config jars into document

### LINKED ISSUE #7019: [Doc] [Map OSS] org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem not found
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

when develop cluster by config map using aliyun oss `fs.oss.credentials.provider: org.apache.hadoop.fs.aliyun.oss.AliyunCredentialsProvider ` 。
error occur : class org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem not found 
微信截图_20240619091601

did I miss some thing?  connector-file-oss-2.3.5.jar is in connectors folder.

### SeaTunnel Version

2.3.5

### SeaTunnel Config

```conf
map config in hazelcast.yaml
map:
    engine*:
       map-store:
         enabled: true
         initial-mode: EAGER
         factory-class-name: org.apache.seatunnel.engine.server.persistence.FileMapStoreFactory
         properties:
           type: hdfs
           namespace: /tmp/seatunnel/imap
           clusterName: seatunnel-cluster
           storage.type: oss
           block.size: block size(bytes)
           oss.bucket: oss://bucket name/
           fs.oss.accessKeyId: OSS access key id
           fs.oss.accessKeySecret: OSS access key secret
           fs.oss.endpoint: OSS endpoint
           fs.oss.credentials.provider: org.apache.hadoop.fs.aliyun.oss.AliyunCredentialsProvider
```

### Running Command

```shell
./bin/seatunnel-cluster.sh -d
```

### Error Exception

```log
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2638) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3269) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3301) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:124) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3352) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3320) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:227) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.seatunnel.engine.imap.storage.file.IMapFileStorage.initialize(IMapFileStorage.java:156) ~[seatunnel-starter.jar:2.3.5]
	at org.apache.seatunnel.engine.imap.storage.file.IMapFileStorageFactory.create(IMapFileStorageFactory.java:41) ~[seatunnel-starter.jar:2.3.5]
	at org.apache.seatunnel.engine.server.persistence.FileMapStore.init(FileMapStore.java:49) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapStoreWrapper.init(MapStoreWrapper.java:87) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.callLifecycleSupportInit(BasicMapStoreContext.java:164) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:137) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:148) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapServiceContextImpl.createMapContainer(MapServiceContextImpl.java:206) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapServiceContextImpl.lambda$createMapConstructor$0(MapServiceContextImpl.java:197) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:140) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:288) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.PartitionContainer.createRecordStore(PartitionContainer.java:91) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:120) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.PartitionContainer.getRecordStore(PartitionContainer.java:153) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.MapServiceContextImpl.getRecordStore(MapServiceContextImpl.java:491) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.operation.MapChunk.getRecordStore(MapChunk.java:385) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.map.impl.operation.MapChunk.afterRunFinal(MapChunk.java:153) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.OperationRunner.runDirect(OperationRunner.java:173) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.partition.operation.MigrationOperation.runMigrationOperation(MigrationOperation.java:139) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.partition.operation.MigrationOperation.doRun(MigrationOperation.java:115) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.partition.operation.MigrationOperation.run(MigrationOperation.java:95) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.Operation.call(Operation.java:189) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.call(OperationRunnerImpl.java:273) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:248) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:471) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:197) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.process(OperationThread.java:137) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.spi.impl.operationexecutor.impl.OperationThread.executeRun(OperationThread.java:123) ~[seatunnel-starter.jar:2.3.5]
	at com.hazelcast.internal.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:102) ~[seatunnel-starter.jar:2.3.5]
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.aliyun.oss.AliyunOSSFileSystem not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2542) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2636) ~[seatunnel-hadoop3-3.1.4-uber.jar:2.3.5]
	... 37 more
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### LINKED ISSUE #7027: [Bug] [Document] Fix IMap Config document error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

Imap config document have some error.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
*
```

### Running Command

```shell
*
```

### Error Exception

```log
*
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zhouhoo**
When configuring Alibaba Cloud OSS, pay attention to the jar in the lib directory, as missing jar may cause failure

### Purpose of this pull request

closes https://github.com/apache/seatunnel/issues/7027 

closes https://github.com/apache/seatunnel/issues/7019

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by zhouhoo** [comment]
https://github.com/apache/seatunnel/issues/7019

**Review by Hisoka-X — COMMENTED** [review]
How about add this new part into english doc too? https://github.com/apache/seatunnel/blob/9fe844f62a3382f44a0b55d6036d63d9372b8578/docs/en/seatunnel-engine/deployment.md#53-map cc @EricJoy2048 @Carl-Zhou-CN

**Comment by EricJoy2048** [comment]
> How about add this new part into english doc too? https://github.com/apache/seatunnel/blob/9fe844f62a3382f44a0b55d6036d63d9372b8578/docs/en/seatunnel-engine/deployment.md#53-map cc @EricJoy2048 @Carl-Zhou-CN

Yes.

**Review by Hisoka-X — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X hi, This seems to be missed some details, should remove configuration: fs.oss.credentials.provider: org.apache.hadoop.fs.aliyun.oss.AliyunCredentialsProvider

**Comment by Hisoka-X** [comment]
> @Hisoka-X hi, This seems to be missed some details, should remove configuration: fs.oss.credentials.provider: org.apache.hadoop.fs.aliyun.oss.AliyunCredentialsProvider

Oh, could you create a PR to fix it?

**Comment by Carl-Zhou-CN** [comment]
@Hisoka-X link #7332

**Comment by loustler** [comment]
Do you guys have a plan to bump a version of shaded hadoop from 3.1.3 to 3.3.6?
According to #7019  and this PR, We should need to bump a version of hadoop.

**Comment by Hisoka-X** [comment]
> Do you guys have a plan to bump a version of shaded hadoop from 3.1.3 to 3.3.6? According to #7019 and this PR, We should need to bump a version of hadoop.

including in https://github.com/apache/seatunnel/pull/7086
before do this, we need add hive e2e test case first. However, hive's e2e test cases have not yet been implemented.😭
Could you mind to add one?
cc @liugddx

**Comment by loustler** [comment]
What kind of tests are needed? Could you create a issue about it?
I'll add hive tests if I have capacities for it.

**Comment by Hisoka-X** [comment]
> What kind of tests are needed? Could you create a issue about it? I'll add hive tests if I have capacities for it.

https://github.com/apache/seatunnel/issues/7474

**Pull request merged**
