### PR TITLE
[Improve]code cleanup

### PR DESCRIPTION
**Pull request by CalvinKirs**
- NPE
-  resource  created using "try-with-resources" 
- Bump jackson-databind from 2.11.0 to 2.12.6.1

### CODE REVIEW

**Review by ruanwenjun — DISMISSED** [review]
Good catch, LGTM.

**Review by zhongjiajie — APPROVED** [review]
LGTM, thanks

**Comment by zhongjiajie** [comment]
Hi @CalvinKirs be careful when you merge PR to dev, we get `[WIP]` in the commit title
image

**Comment by CalvinKirs** [comment]
> Hi @CalvinKirs be careful when you merge PR to dev, we get `[WIP]` in the commit title image

Sorry, I forget to update the commit log and PR title :(

**Pull request merged**
