### PR TITLE
[Connector-V2] [Test] Fix Iceberg test with time type on spark

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Remove time type on spark test. The test will failed if not.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
@hailin0 PTAL

**Review by hailin0 — DISMISSED** [review]
LGTM

**Comment by TaoZex** [comment]
https://github.com/apache/incubator-seatunnel/pull/3189
I tried to deprecate this e2e, but workflow still failed.

**Comment by Hisoka-X** [comment]
> #3189 I tried to deprecate this e2e, but workflow still failed.

Yes, have another problem, we will fix it both in this PR.

**Review by hailin0 — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]
+1

**Review by ic4y — APPROVED** [review]
LGTM

**Pull request merged**
