### PR TITLE
[Feature][Rabbitmq] Allow configuration of queue durability and deletion policy

### LINKED ISSUE #7363: [Feature][Rabbitmq] Allow configuration of queue durability and deletion policy
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

The RabbitMQ connector's queue settings currently do not support configuring the durable, exclusive, and auto-delete options. These features will be implemented in the future to allow users to define queue behavior.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zqr10159**
Queue settings in Rabbitmq connector are now configurable to specify durable,exclusive, and auto-delete options. This enables users to define queue behavior

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @zqr10159 for contribute this! Could you add a test case in https://github.com/apache/seatunnel/blob/862e2055cec6a4428ec4cf67b472ba41ca364d05/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-rabbitmq-e2e/src/test/java/org/apache/seatunnel/e2e/connector/rabbitmq/RabbitmqIT.java#L4 ?

**Comment by zqr10159** [comment]
> Thanks @zqr10159 for contribute this! Could you add a test case in https://github.com/apache/seatunnel/blob/862e2055cec6a4428ec4cf67b472ba41ca364d05/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-rabbitmq-e2e/src/test/java/org/apache/seatunnel/e2e/connector/rabbitmq/RabbitmqIT.java#L4 ?

Ok，I will add it later.

**Comment by zqr10159** [comment]
@Hisoka-X Done!

**Comment by Hisoka-X** [comment]
please fix ci

**Comment by zqr10159** [comment]
Sorry, I don't know how to fix this. I created a new branch and rolled back all my code, but still the local test doesn't pass, can you give me some guidance, thank you very much!
image

**Comment by Hisoka-X** [comment]
> Sorry, I don't know how to fix this. I created a new branch and rolled back all my code, but still the local test doesn't pass, can you give me some guidance, thank you very much! image

Have you try build package (eg: `mvn clean package -DskipTests`) before execute e2e test case?

**Comment by Carl-Zhou-CN** [comment]
> Sorry, I don't know how to fix this. I created a new branch and rolled back all my code, but still the local test doesn't pass, can you give me some guidance, thank you very much! image

In my opinion, you should be the window system, which is due to the package not copy to the container, or the script newline problem, you modify the idea newline environment

**Comment by zqr10159** [comment]
> > Sorry, I don't know how to fix this. I created a new branch and rolled back all my code, but still the local test doesn't pass, can you give me some guidance, thank you very much! image
> 
> 
> 
> In my opinion, you should be the window system, which is due to the package not copy to the container, or the script newline problem, you modify the idea newline environment

Thanks,I'll try it

**Comment by Hisoka-X** [comment]
Could you retry the failed ci? Thanks.

**Comment by zqr10159** [comment]
> Could you retry the failed ci? Thanks.

The previous local test was a Windows line break issue, the local modification has passed the test, but the github ci seems to have a different error.

**Comment by Hisoka-X** [comment]
Please merge from dev to retrigger it.

**Comment by zqr10159** [comment]
@Hisoka-X All done， Thanks!

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @zqr10159 !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
