### PR TITLE
[doc] Move introduction.md from website

### PR DESCRIPTION
**Pull request by zhongjiajie**
Doc introduction.md is in repository seatunnel-website,
and this patch move it to main repo to keep our docs
together which make more sense and maintainable.

### CODE REVIEW

**Comment by zhongjiajie** [comment]
WTF, deadlink!

**Comment by zhongjiajie** [comment]
It odd,  why our CI do not run?

**Comment by CalvinKirs** [comment]
> It odd, why our CI do not run?

Occasionally, recognition is slow. Maybe at a time when resources are tight. I guess

**Review by CalvinKirs — APPROVED** [review]
well done

**Pull request merged**
