### PR TITLE
[bug]fix  commandArgs  -t(--check)  conflict  with flink deployment t…

### PR DESCRIPTION
**Pull request by sandyfog**
…arget

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by Hisoka-X — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
Hi, some test failed in seatunnel-core-flink. They use `-t` to test command, you should change them too.

**Comment by sandyfog** [comment]
I don't know how to re-run the  test,  @Hisoka-X  PTAL

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Comment by Hisoka-X** [comment]
Thanks for your contribute, looking forward your next PR

**Pull request merged**
