### PR TITLE
[Bug] [Connector-V2] Clickhouse File Connector failed to sink to table with settings like storage_policy

### PR DESCRIPTION
**Pull request by wineternity**
related to #4003 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by liugddx — COMMENTED** [review]
Can you add e2e test for this pr?

**Comment by wineternity** [comment]
> Can you add e2e test for this pr?

OK

**Comment by Hisoka-X** [comment]
Hi, any progress?

**Comment by wineternity** [comment]
> Hi, any progress?

may be next week, try to add a e2e case

**Comment by wineternity** [comment]
> Can you add e2e test for this pr?

@liugddx @Hisoka-X  hi, I found it is a little bit difficult to add an e2e for ClickhouseFile sink.    After finished  add ssh service to clickhouse images,  it still need to add clickhouse-local client in flink taskmanager or spark executor docker image.  Could we just  ignore this ?  The pr is tested in the real environment.

**Comment by Hisoka-X** [comment]
> > Can you add e2e test for this pr?
> 
> @liugddx @Hisoka-X hi, I found it is a little bit difficult to add an e2e for ClickhouseFile sink. After finished add ssh service to clickhouse images, it still need to add clickhouse-local client in flink taskmanager or spark executor docker image. Could we just ignore this ? The pr is tested in the real environment.

Ok for me, I will add e2e for clickhousefile later.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by liugddx — APPROVED** [review]

**Pull request merged**
