### PR TITLE
 [Bugfix] [connector-jdbc] Fix when type is int and null value will always get 0 instead of null

### PR DESCRIPTION
**Pull request by choucmei**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by ic4y** [comment]
We need to cover scenarios involving null values in the e2e test, so as to ensure that the code won't encounter this issue again and to confirm that the current modification is effective.

**Comment by hailin0** [comment]
add e2e testcase 

https://github.com/apache/incubator-seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e

**Comment by ic4y** [comment]
The class that has overridden the toInternal method also needs to be modified, for example, PostgresJdbcRowConverter#toInternal.

**Comment by choucmei** [comment]
> The class that has overridden the toInternal method also needs to be modified, for example, PostgresJdbcRowConverter#toInternal.

Okk

**Comment by choucmei** [comment]
This PR was blocked by e2e because mysql e2e was losing data.
https://github.com/apache/seatunnel/issues/4732

**Pull request closed without merging**
