### PR TITLE
[Feature][Jdbc] Support hive compatibleMode add inceptor dialect

### PR DESCRIPTION
**Pull request by Xuzhengz**
add hive compatibleMode,support inceptor read and writer.

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @Xuzhengz ! Quick question: does inceptor has docker to build e2e test case?

**Comment by Xuzhengz** [comment]
> Thanks @Xuzhengz ! Quick question: does inceptor has docker to build e2e test case?

对不起，Inceptor仅支持transwarp TDH平台运行,没有独立可执行的docker容器,它是transwarp基于hive二次开发,支持jdbc sink.

**Comment by Xuzhengz** [comment]
> Thanks @Xuzhengz ! Quick question: does inceptor has docker to build e2e test case?

Sorry, Inceptor only supports running on the Transwarp TDH platform and does not have a standalone executable Docker container. It is developed based on Hive and supports JDBC Sink

**Comment by Hisoka-X** [comment]
> > Thanks @Xuzhengz ! Quick question: does inceptor has docker to build e2e test case?
> 
> Sorry, Inceptor only supports running on the Transwarp TDH platform and does not have a standalone executable Docker container. It is developed based on Hive and supports JDBC Sink

oh I got it. Have you tested it?

**Comment by Xuzhengz** [comment]
> oh I got it. Have you tested it?
Yes, I have tested it. I have run it locally and can write data through the JDBC plugin, but I have not implemented the 'catalog' feature and cannot run the 'save mode'

**Review by Hisoka-X — APPROVED** [review]

**Comment by Hisoka-X** [comment]
please update the doc

**Comment by Xuzhengz** [comment]
> please update the doc

ok

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
