### PR TITLE
[Bug][Connector-v2][KafkaSink]Fix KafkaProducer resources have never been released.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
When KafkaSink turns on the "EXACTLY_ONCE" semantics, a KafkaProducer will be created every time the checkpoint is executed, but it has not been closed, resulting in the creation of a large number of Kafka sender threads and connections. Therefore, it is necessary to check and close the release of resources before creating.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@ruanwenjun @Hisoka-X @TyrantLucifer PTAL.

**Comment by lightzhao** [comment]
@EricJoy2048 @ruanwenjun @ashulin @TaoZex @Hisoka-X PTAL.

**Review by Hisoka-X — DISMISSED** [review]
Good Catch

**Comment by lightzhao** [comment]
@TyrantLucifer @EricJoy2048 @ruanwenjun @ashulin @TaoZex  PTAL.

**Comment by lightzhao** [comment]
@EricJoy2048 @ruanwenjun @ashulin @TaoZex @TyrantLucifer PTAL.

**Review by Hisoka-X — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
