### PR TITLE
[Bugfix][zeta] Resolved the issue causing checkpoints to halt on tolerable-failure=0.

### PR DESCRIPTION
**Pull request by ic4y**
…rable-failure=0.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by ic4y** [comment]
@Hisoka-X @hailin0 PTAL

**Comment by wu-a-ge** [comment]
hi, why are these two parameters removed? Is there no need to exist, or are there other better solutions?

**Comment by ic4y** [comment]
> hi, why are these two parameters removed? Is there no need to exist, or are there other better solutions?

At present, the engine internally only supports situations with `max-concurrent=1` and `tolerable-failure=0`. Therefore, these two parameters are meaningless. Removing them will make the code clearer and less prone to errors. Moreover, I believe there is no need for concurrent checkpointing in the synchronous engine scenario. Without concurrent checkpoints, `tolerable-failure` can only be set to 0; otherwise, it may lead to data inconsistency.

**Review by EricJoy2048 — APPROVED** [review]

**Review by davidzollo — APPROVED** [review]
+1

**Pull request merged**
