### PR TITLE
[Bug][connector-v2][PulsarSource]can't consume messages all the time

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
Question:  The running flag is not enabled all the time, so the message cannot be consumed.
image
Solution：Initialize setting running to true.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@ashulin @Hisoka-X PTAL.

**Comment by lightzhao** [comment]
@ashulin PTAL.

**Comment by lightzhao** [comment]
@Hisoka-X @ashulin @TyrantLucifer PTAL.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Comment by lightzhao** [comment]
@EricJoy2048 @ashulin @TyrantLucifer PTAL.

**Comment by lightzhao** [comment]
@EricJoy2048 @ashulin @TyrantLucifer PTAL.

**Comment by lightzhao** [comment]
@ashulin PTAL.

**Comment by lightzhao** [comment]
@ashulin @TyrantLucifer PTAL.

**Comment by lightzhao** [comment]
@ashulin @ EricJoy2048 PTAL.

**Comment by lightzhao** [comment]
@EricJoy2048  @ashulin   PTAL.

**Comment by lightzhao** [comment]
Hello everyone, who has the time to help with the review, the current bug has caused the pulsar source to fail to work normally, and the data cannot be consumed.

**Review by ashulin — APPROVED** [review]

**Comment by Hisoka-X** [comment]
> Hello everyone, who has the time to help with the review, the current bug has caused the pulsar source to fail to work normally, and the data cannot be consumed.

Thanks for push this PR, sorry for response slow.

**Comment by lightzhao** [comment]
> > Hello everyone, who has the time to help with the review, the current bug has caused the pulsar source to fail to work normally, and the data cannot be consumed.
> 
> Thanks for push this PR, sorry for response slow.
You are welcome, everyone who has time will review these pr #4302 #4246 #3990 , thank you.

**Pull request merged**
