### PR TITLE
[Feature][connector] clickhousefile sink connector support non-root username for fileTransfer

### PR DESCRIPTION
**Pull request by stormrise**
## Purpose of this pull request

TO CLOSE THIS #2262 https://github.com/apache/incubator-seatunnel/issues/2262

clickhousefile sink connector support non-root username for fileTransfer

it's common using non-root user for production server for security reason

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Nice work, but you should fix some checkstyle problem

**Comment by stormrise** [comment]
@Hisoka-X may I ask if these has some instuctions to dev, I run `mvn package` or `mvn checkstyle` but didnot show the checkstyle problem

**Comment by Hisoka-X** [comment]
> @Hisoka-X may I ask if these has some instuctions to dev, I run `mvn package` or `mvn checkstyle` but didnot show the checkstyle problem

If so, the ci will pass(not including license check).

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
