### PR TITLE
[improve][shade] Upgrade hadoop client to 3.3.4

### PR DESCRIPTION
**Pull request by liugddx**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by litiliu** [comment]
Hadoop 3.4.0 has been released on Mar 17, 2024. How about we directly update to 3.4.0?

**Comment by liugddx** [comment]
> Hadoop 3.4.0 has been released on Mar 17, 2024. How about we directly update to 3.4.0?

I recommend upgrading step by step and then upgrading to the latest version after it is stable.

**Comment by liugddx** [comment]
This pr has been merged into jdk17, so i will close it.

**Comment by liugddx** [comment]
> This pr has been merged into jdk17, so i will close it.

https://github.com/apache/seatunnel/pull/7086

**Pull request closed without merging**
