### PR TITLE
modify seatunnel-flink-starter-common version adapt dev envirement

### PR DESCRIPTION
**Pull request by Slashoper**
### Purpose of this pull request

This PR solves the problem of developers' local development seatunnel-translation-link-15.jar package installation failure

<dependency>
            <groupId>org.apache.seatunnel</groupId>
            <artifactId>seatunnel-translation-flink-15</artifactId>
            <version>${project.version}</version>
 </dependency>

### Does this PR introduce _any_ user-facing change?

no
### How was this patch tested?

Tested in local , It work fine.
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
-1, what the meaning of this?

**Comment by Slashoper** [comment]
Resolve issues with local debugging by developers and Maven dependency errors in seatunnel-flink starter common modules

**Comment by CheneyYin** [comment]
@Slashoper Please elaborate on the problem you encountered, and submit your issue. Perhaps we will find other ways to solve it.

**Comment by liunaijie** [comment]
Is there any problem when you compile code in local? 
Here is the document [link](https://seatunnel.apache.org/docs/2.3.3/contribution/setup/) of how to setup in your local.

**Comment by Hisoka-X** [comment]
I believe it's not a problem. It work fine for now. Could you retry build in you enviorment? Please do that after clean cache.

**Comment by Hisoka-X** [comment]
I will close this PR. If you have any concern or question, just go on add comment.

**Pull request closed without merging**
