### PR TITLE
[Improve][Connector-V2][JDBC] Test to select the appropriate batch size for jdbc sink

### PR DESCRIPTION
**Pull request by TaoZex**
## Purpose of this pull request

Use config：fake souce to mysql sink，parallelism = 1

Test the total data of 1w, 10w, and 100w respectively, and use batch size from 100 to 10000 to select appropriate parameters for jdbc sink.

The results are shown in the figure below:

image

To sum up, using bacth size 2000 is a better choice.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Could you please do the same test case on another type databases such as `Postgre` `Oracle` and so on?

**Review by CalvinKirs — COMMENTED** [review]
For this kind of test, I don't think it has any meaning. Different system environments and different data sizes may result in different results.

**Comment by EricJoy2048** [comment]
> For this kind of test, I don't think it has any meaning. Different system environments and different data sizes may result in different results.

Yes, I agree with you. So @TaoZex  can you close this pr?

**Comment by hailin0** [comment]
> Different system environments and different data sizes may result in different results.

+1

**Comment by TaoZex** [comment]
> > For this kind of test, I don't think it has any meaning. Different system environments and different data sizes may result in different results.
> 
> Yes, I agree with you. So @TaoZex can you close this pr?

**Pull request closed without merging**
