### PR TITLE
[Improve][Zeta] Remove `result_table_name` from action name(checkpoint state key)

### PR DESCRIPTION
**Pull request by hailin0**
### Purpose of this pull request

[Improve][Zeta] Remove `result_table_name` from action name(checkpoint state key)

### Does this PR introduce _any_ user-facing change?
NO

### How was this patch tested?

updated testcase

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Wait #5780 to solve the compile error.

**Review by Hisoka-X — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
Waiting CI

**Review by Hisoka-X — DISMISSED** [review]
LGTM. Only one minior problem. I think you can remove `sources` now. https://github.com/apache/seatunnel/pull/5779/files#diff-b6335a868b35247b6345c86bd423c54ba9a874f2c19de6005ba4b2144c7fd198R73

**Comment by hailin0** [comment]
> LGTM. Only one minior problem. I think you can remove `sources` now. https://github.com/apache/seatunnel/pull/5779/files#diff-b6335a868b35247b6345c86bd423c54ba9a874f2c19de6005ba4b2144c7fd198R73

@Hisoka-X fixed

**Review by Hisoka-X — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
+1

**Pull request merged**
