### PR TITLE
[Improve]Use Jackson replace Fastjson (#1971)

### PR DESCRIPTION
**Pull request by CalvinKirs**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by xleoken — APPROVED** [review]
Great!, we always receive security vulnerability report about fastjson.

**Comment by Hisoka-X** [comment]
Hi Kris, #1971 will release on 2.1.2, Do we must merge this PR into 2.1.2 to reduce risk？

**Comment by CalvinKirs** [comment]
> Hi Kris, #1971 will release on 2.1.2, Do we must merge this PR into 2.1.2 to reduce risk？

 I think it's better best

**Review by zhuangchong — APPROVED** [review]
LGTM.

**Pull request merged**
