### PR TITLE
[api-draft][connector] Fix hive sink dist package in new connector.

### PR DESCRIPTION
**Pull request by zhuangchong**
## Purpose of this pull request

associated pr: #1997 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by zhuangchong** [comment]
@EricJoy2048 @CalvinKirs Please help review. thx.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Comment by zhuangchong** [comment]
I build the project locally it's normal, I don't know why the build fails in CI.

https://github.com/apache/incubator-seatunnel/runs/6810637063?check_suite_focus=true#step:6:24226

image

image

---
My current process is to remove the `@Overrider` annotation in the `hive/src/main/java/org/apache/seatunnel/connectors/seatunnel/hive/sink/HiveSinkWriter.java:[93,4]` code, CI passes normally.

**Comment by Hisoka-X** [comment]
> I build the project locally it's normal, I don't know why the build fails in CI.
> 
> https://github.com/apache/incubator-seatunnel/runs/6810637063?check_suite_focus=true#step:6:24226
> 
> image
> 
> image
> 
> My current process is to remove the `@Overrider` annotation in the `hive/src/main/java/org/apache/seatunnel/connectors/seatunnel/hive/sink/HiveSinkWriter.java:[93,4]` code, CI passes normally.



> I build the project locally it's normal, I don't know why the build fails in CI.
> 
> https://github.com/apache/incubator-seatunnel/runs/6810637063?check_suite_focus=true#step:6:24226
> 
> image
> 
> image
> 
> My current process is to remove the `@Overrider` annotation in the `hive/src/main/java/org/apache/seatunnel/connectors/seatunnel/hive/sink/HiveSinkWriter.java:[93,4]` code, CI passes normally.

Please pull your local code again, we had update this `snapshotState` interface.

**Comment by Hisoka-X** [comment]
> I build the project locally it's normal, I don't know why the build fails in CI.
> 
> https://github.com/apache/incubator-seatunnel/runs/6810637063?check_suite_focus=true#step:6:24226
> 
> image
> 
> image
> 
> My current process is to remove the `@Overrider` annotation in the `hive/src/main/java/org/apache/seatunnel/connectors/seatunnel/hive/sink/HiveSinkWriter.java:[93,4]` code, CI passes normally.



> I build the project locally it's normal, I don't know why the build fails in CI.
> 
> https://github.com/apache/incubator-seatunnel/runs/6810637063?check_suite_focus=true#step:6:24226
> 
> image
> 
> image
> 
> My current process is to remove the `@Overrider` annotation in the `hive/src/main/java/org/apache/seatunnel/connectors/seatunnel/hive/sink/HiveSinkWriter.java:[93,4]` code, CI passes normally.

Please pull your local code again, we had update this `snapshotState` interface.

**Pull request merged**
