### PR TITLE
ci(backend): add commit message check step

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by kezhenxu94** [comment]
Hi. Checking the commit message doesn’t make any sense to me because we are using “Squash and merge”, all the commit messages will be rewrote to the pull request title when merging, checking the unused commit messages increase the contributors’ burden while bring nothing.

**Comment by TyrantLucifer** [comment]
> 

You are correct. However, currently, some committers may not modify the final message when merging code, which means that the information merged into the main branch is the last submission message of the contributor. If standardizing committers' merging behavior is important and needs to be addressed, do you have any suggestions?

**Comment by TyrantLucifer** [comment]
> Hi. Checking the commit message doesn’t make any sense to me because we are using “Squash and merge”, all the commit messages will be rewrote to the pull request title when merging, checking the unused commit messages increase the contributors’ burden while bring nothing.

You are correct. However, currently, some committers may not modify the final message when merging code, which means that the information merged into the main branch is the last submission message of the contributor. If standardizing committers' merging behavior is important and needs to be addressed, do you have any suggestions?

**Comment by kezhenxu94** [comment]
> > Hi. Checking the commit message doesn’t make any sense to me because we are using “Squash and merge”, all the commit messages will be rewrote to the pull request title when merging, checking the unused commit messages increase the contributors’ burden while bring nothing.
> 
> You are correct. However, currently, some committers may not modify the final message when merging code, which means that the information merged into the main branch is the last submission message of the contributor. If standardizing committers' merging behavior is important and needs to be addressed, do you have any suggestions?

The default commit message when merging is the pull request title, so you might want to check PR title instead

**Comment by hailin0** [comment]
> > > Hi. Checking the commit message doesn’t make any sense to me because we are using “Squash and merge”, all the commit messages will be rewrote to the pull request title when merging, checking the unused commit messages increase the contributors’ burden while bring nothing.
> > 
> > 
> > You are correct. However, currently, some committers may not modify the final message when merging code, which means that the information merged into the main branch is the last submission message of the contributor. If standardizing committers' merging behavior is important and needs to be addressed, do you have any suggestions?
> 
> The default commit message when merging is the pull request title, so you might want to check PR title instead

+1

**Pull request closed without merging**
