### PR TITLE
[SeaTunnel#1075] Add stale mechanism to auto mark issues and PRs as stale

### LINKED ISSUE #1075: [Feature][Github] Add stale mechanism to auto mark issues and PRs as stale
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

We should add stale mechanism to auto mark issues and PRs as stale status to control the number, which can also remind us which need to be picked up again.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

Fixes #1075

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by davidzollo — APPROVED** [review]
lgtm

**Comment by zhongjiajie** [comment]
Hi @asdf2014, thanks for your contribution, but it seems this stale config is invalid which you could find in https://github.com/apache/dolphinscheduler/pull/8075#issuecomment-1014062644. I think maybe we could use Github Action Stale https://github.com/actions/stale instead of using Github App https://github.com/apps/stale, cause we have ask the infra team to install Github App, but it is not required if we use https://github.com/actions/stale. cc @CalvinKirs

**Comment by asdf2014** [comment]
Hi @zhongjiajie , you are welcome. Yes, we need create a Jira [ticket](https://issues.apache.org/jira/browse/INFRA-18736) to ASF infra team to enable the Stale bot for SeaTunnel, like other projects did. I memtioned this to @dailidong privately. We are working on it.

**Comment by asdf2014** [comment]
Sure, it's up to you. If you are more familiar with the Github Action version, we can also use it instead, and the effect should be the same.

**Comment by zhongjiajie** [comment]
> 

It's alright, if Jira ticket is already done, we could use Github App too, I do not have a strong opinion here.

**Comment by asdf2014** [comment]
@zhongjiajie Got it, thanks again for your comments :smile:

**Comment by asdf2014** [comment]
@zhongjiajie I just created the [ticket](https://issues.apache.org/jira/browse/INFRA-22748) to ASF Infra team, hope we can get response soon.

**Pull request merged**
