### PR TITLE
[Fix][Spark] fixed first start shell can't run.

### LINKED ISSUE #1744: [Bug] [Spark] First execute seatunnl-start-spark.sh will return command not found.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

When first execute seatunnl-start-spark.sh, SparkStarter execute compress tar file, so return command with same log info. Then shell can execute directly.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
any
```

### Running Command

```shell
./bin/start-seatunnel-spark.sh --config ~/Code/seatunnel-fork/seatunnel-examples/seatunnel-spark-examples/src/main/resources/examples/spark.batch.conf -m spark://localhost:7077 -e cluster
```

### Error Exception

```log
./bin/start-seatunnel-spark.sh --config ~/Code/seatunnel-fork/seatunnel-examples/seatunnel-spark-examples/src/main/resources/examples/spark.batch.conf -m spark://localhost:7077 -e cluster
Execute SeaTunnel Flink Job: 0    [main] INFO  org.apache.seatunnel.utils.CompressionUtils  - Tar directory 'plugins' to file 'plugins.tar.gz'.
12   [main] INFO  org.apache.seatunnel.utils.CompressionUtils  - Creating tar file 'plugins.tar.gz'.
${SPARK_HOME}/bin/spark-submit --class "org.apache.seatunnel.SeatunnelSpark" --name "SeaTunnelGhy" --master "spark://localhost:7077" --deploy-mode "cluster" --files "plugins.tar.gz,/Users/fanjia/Code/seatunnel-fork/seatunnel-examples/seatunnel-spark-examples/src/main/resources/examples/spark.batch.conf" --conf "spark.executor.memory=512m" --conf "spark.master=local" --conf "spark.executor.cores=1" --conf "spark.app.name=SeaTunnelGhy" --conf "spark.executor.instances=2" lib/seatunnel-core-spark.jar --config /Users/fanjia/Code/seatunnel-fork/seatunnel-examples/seatunnel-spark-examples/src/main/resources/examples/spark.batch.conf -m spark://localhost:7077 -e cluster
./bin/start-seatunnel-spark.sh: line 34: 0: command not found
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
This close #1744 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by whb-bigdata** [comment]
Hi, thanks for  fix this bug.And i find a error in your code. 
in seatunnel-core/seatunnel-core-spark/src/main/bin/start-seatunnel-spark.sh
should be  echo "Execute SeaTunnel Spark Job: ${CMD}"，it's not flink

**Comment by Hisoka-X** [comment]
> Hi, thanks for fix this bug.And i find a error in your code. in seatunnel-core/seatunnel-core-spark/src/main/bin/start-seatunnel-spark.sh should be echo "Execute SeaTunnel Spark Job: ${CMD}"，it's not flink

My fault. Thanks for review.

**Comment by ruanwenjun** [comment]
Is there a better way to solve this, if we start with debug, there will still have this bug. How about execute the command at `SparkStarter`.

**Comment by Hisoka-X** [comment]
> Is there a better way to solve this, if we start with debug, there will still have this bug. How about execute the command at `SparkStarter`.

1. Split CMD which Starter return.
2. Remove call Log method.
3. This one.

Maybe 1 is better.

**Comment by ruanwenjun** [comment]
> > Is there a better way to solve this, if we start with debug, there will still have this bug. How about execute the command at `SparkStarter`.
> 
> 1. Split CMD which Starter return.
> 2. Remove call Log method.
> 3. This one.
> 
> Maybe 1 is better.

You mean we still use the SparkStarter to generate the command, but parse the command in the shell?

**Comment by Hisoka-X** [comment]
> > 
> 
> You mean we still use the SparkStarter to generate the command, but parse the command in the shell?

yeap

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
