### PR TITLE
[Doc][Improve]add ClickhouseFile connector doc link on README

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
add ClickhouseFile connector doc link on README

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Good catch, but I suggest we can remove the `Plugins supported by SeaTunnel` from the README.md, this part is too long. We need to make the README more clear. @CalvinKirs @zhongjiajie @wuchunfu WDYT.

**Comment by Hisoka-X** [comment]
> Good catch, but I suggest we can remove the `Plugins supported by SeaTunnel` from the README.md, this part is too long. We need to make the README more clear. @CalvinKirs @zhongjiajie @wuchunfu WDYT.

But this is a good way to user to know which connector SeaTunnel supported, or we should create new doc for introduce connectors.

**Comment by ruanwenjun** [comment]
> 

Maybe we can simply add a link to the website, if user want to know which plugin we supported, he can easily find from the website, listing all the connector here is too long.

**Comment by Hisoka-X** [comment]
> > 
> 
> Maybe we can simply add a link to the website, if user want to know which plugin we supported, he can easily find from the website, listing all the connector here is too long.

Sounds great, I will change it

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Pull request merged**
