### PR TITLE
[Hotfix][ElasticsearchSink]Update the version in the docs.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
The test found that the 6.x version cannot be supported.
image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
@iture123 PTAL

**Comment by lightzhao** [comment]
@iture123 @TyrantLucifer @Hisoka-X PTAL,thanks.

**Review by Hisoka-X — DISMISSED** [review]

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
The owner @iture123 of es connector has the different thoughts of this, later he will left his advice.

**Review by iture123 — CHANGES_REQUESTED** [review]
ElasticsearchRowSerializer make an error annotation,The elasticsearch connector and the class ElasticsearchRowSerializer.java both support ElasticSearch version is >= 2.x and <= 8.x.

**Comment by lightzhao** [comment]
> error annotation,

ok, fix error annotation.

**Comment by lightzhao** [comment]
@TyrantLucifer @iture123 @Hisoka-X PTAL.

**Comment by lightzhao** [comment]
who has time help review, thanks.

**Comment by TyrantLucifer** [comment]
merge dev into your branch

**Comment by lightzhao** [comment]
> merge dev into your branch

done.

**Comment by EricJoy2048** [comment]
@TyrantLucifer  @iture123  @Hisoka-X  PTAL again.

**Review by iture123 — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
