### PR TITLE
fix seatunnel-format-json version

### PR DESCRIPTION
**Pull request by cqutwangyu**
### Purpose of this pull request
fix seatunnel-transforms-v2/pom.xml <artifactId>seatunnel-format-json</artifactId> version

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
SeaTunnelEngineExample

### Check list

* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [x] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by cqutwangyu** [comment]
image

Claas `org.apache.seatunnel.format.json.JsonFormatFactory` of `seatunnel-format-json-2.3.4-SNAPSHOT.jar`
image
Importing dependencies `org.apache.seatunnel.api.table.factory.DeserializationFormatFactory`

But that class has since been removed
https://github.com/apache/seatunnel/pull/5880

**Comment by cqutwangyu** [comment]
@Hisoka-X  please CC

**Review by Hisoka-X — APPROVED** [review]

**Comment by cqutwangyu** [comment]
@Carl-Zhou-CN Version 2.3.4-release also has this problem

**Comment by Carl-Zhou-CN** [comment]
@EricJoy2048  cc, this seems to have an impact on the release

**Review by Carl-Zhou-CN — APPROVED** [review]
+1, Thank you very much for your review of the 2.3.4 release

**Comment by cqutwangyu** [comment]
> +1, Thank you very much for your review of the 2.3.4 release

It's my honour.

**Pull request merged**
