### PR TITLE
update the condition to 1 = 0 about get table operation

### PR DESCRIPTION
**Pull request by zhaomin1423**
## Purpose of this pull request

The data need not to acquire, so the 1 = 0 have more performance.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@ashulin Hi, PTAL,thx

**Review by ashulin — APPROVED** [review]
LGTM, The SQL only need metadata.

**Review by CalvinKirs — APPROVED** [review]

**Comment by zhaomin1423** [comment]
Thanks for your review. @CalvinKirs @ashulin

**Comment by CalvinKirs** [comment]
Hi @zhaomin1423 , thanks for your contribution  🎉 . If you want to contribute but could not find the issue, maybe you could start https://github.com/apache/incubator-seatunnel/issues?q=is%3Aopen+is%3Aissue+label%3A%22volunteer+wanted%22, Looking forward to your next contribution.If you have any questions, dev email exchange or contact me (WeChat: Kris Evil)A private conversation. We'd rather have a public conversation

**Pull request merged**
