### PR TITLE
[Bug][KafkaSource]Failed to parse offset format

### PR DESCRIPTION
**Pull request by lightzhao**
When the kafka source is started in offset mode, when the topicName has a "-", the exception will be resolved, causing the assignment to fail.
example:
start_mode = "specific_offsets"
start_mode.offsets = {
         my-topic-test-0 = 1
}
topicName is my, partition is topic-test-0.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by TaoZex** [comment]
PTAL @Carl-Zhou-CN

**Comment by lightzhao** [comment]
@TaoZex @Carl-Zhou-CN please review, thanks.

**Review by Carl-Zhou-CN — DISMISSED** [review]
+1

**Review by TyrantLucifer — DISMISSED** [review]
LGTM

**Review by TaoZex — DISMISSED** [review]
+1

**Review by Hisoka-X — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
Hi, Please update doc to add this change to change-log

**Review by TaoZex — APPROVED** [review]

**Comment by lightzhao** [comment]
> Hi, Please update doc to add this change to change-log

done, thanks. please merge.

**Review by TyrantLucifer — APPROVED** [review]
LGTM

**Review by Carl-Zhou-CN — APPROVED** [review]
+1

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
