### PR TITLE
[Feature][Redis] Flush data when the time reaches checkpoint.interval

### LINKED ISSUE #8174: [Feature][Redis-Connector] Redis sink support write full data in real time
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Only when the amount of data is greater than batchSize will it be written, resulting in the inability to write data properly during real-time tasks, The relevant code is as follows：
```java
@Override
public void write(SeaTunnelRow element) throws IOException {
    rowKinds.add(element.getRowKind());
    List<String> fields = Arrays.asList(seaTunnelRowType.getFieldNames());
    String key = getKey(element, fields);
    keyBuffer.add(key);
    String value = getValue(element, fields);
    valueBuffer.add(value);
    // This line
    if (keyBuffer.size() >= batchSize) {
        doBatchWrite();
        clearBuffer();
    }
}
```
for example, mysqlcdc->redis, If there are only 3 rows of data in MySQL and batchSize is set to 10, the data will not be written immediately

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lm-ylj**
### Purpose of this pull request

close #8174

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  2. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
  3. Add ci label in [label-scope-conf](https://github.com/apache/seatunnel/blob/dev/.github/workflows/labeler/label-scope-conf.yml)
  4. Add e2e testcase in [seatunnel-e2e](https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/)
  5. Update connector [plugin_config](https://github.com/apache/seatunnel/blob/dev/config/plugin_config)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Thanks @lm-ylj ! Could you add a test case?

**Comment by lm-ylj** [comment]
> Thanks @lm-ylj ! Could you add a test case?

Ok, I will finish this later

**Review by Hisoka-X — APPROVED** [review]
LGTM. Thanks @lm-ylj !

**Review by hailin0 — APPROVED** [review]

**Comment by Hisoka-X** [comment]
Hi @lm-ylj , we already reverted this PR by https://github.com/apache/seatunnel/pull/8278. Because this PR broken our ci. Could you try re-raise a PR?

**Comment by lm-ylj** [comment]
> Hi @lm-ylj , we already reverted this PR by #8278. Because this PR broken our ci. Could you try re-raise a PR?

Sorry, I'll double check this test case

**Pull request merged**
