### PR TITLE
[connector-v2][iceberg sink] add iceberg sink connector

### PR DESCRIPTION
**Pull request by ic4y**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by hailin0** [comment]
Please add documentation & e2e

**Comment by hailin0** [comment]
Repeat with https://github.com/apache/seatunnel/pull/5072

Do you have any communication and discussion?

**Comment by felix-thinkingdata** [comment]
你会继续推进这个 iceberg sink的完成吗？

Will you continue to push for the completion of this iceberg sink?

**Comment by zengqinchris** [comment]
> 你会继续推进这个 iceberg sink的完成吗？
> 
> Will you continue to push for the completion of this iceberg sink?

同问，用了比较久的seatunnel，一直卡在sink iceberg的功能，啥时候可以出来呢？

By the same token, I have been using seatunnel for a long time and have been stuck in the sink iceberg function. When will it be available?

**Comment by ic4y** [comment]
I will refine this pr in the next few days

**Comment by zengqinchris** [comment]
> I will refine this pr in the next few days

大佬，sink iceberg的功能有计划什么时候可以在dev上测试呢？
When is there a plan to test the functionality of sink iceberg on dev?

**Comment by hailin0** [comment]
pr #6265 merged

**Pull request closed without merging**
