### PR TITLE
[Feature][Flink] Add external configuration parameters

### PR DESCRIPTION
**Pull request by zhilinli123**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by ruanwenjun** [comment]
LGTM, please add doc about this.
https://github.com/apache/seatunnel/blob/dev/docs/en/other-engine/flink.md

**Comment by zhilinli123** [comment]
PTAL: @ruanwenjun @TyrantLucifer

**Review by ruanwenjun — DISMISSED** [review]
LGTM

**Comment by zhilinli123** [comment]
There is a problem with some parameter configuration. I am working on it. Do not merge it
  @ruanwenjun @TyrantLucifer

**Comment by TyrantLucifer** [comment]
> There is a problem with some parameter configuration. I am working on it. Do not merge it @ruanwenjun @TyrantLucifer

Waiting CI/CD and offer some screenshots to verify it worked.

**Review by TyrantLucifer — DISMISSED** [review]
Please fix dead links in your docs.

**Comment by zhilinli123** [comment]
PTAL: @TyrantLucifer @ruanwenjun  I added some CI

**Comment by TyrantLucifer** [comment]
> PTAL: @TyrantLucifer @ruanwenjun  I added some CI
> 
> 

Overall LGTM, but the test case that you added I didn't any way to see the parameter worded really. Could you please compiled the project and try verify it in a local flink env and offer the screen shots for it？

**Comment by zhilinli123** [comment]
### Flink Conf

**Comment by zhilinli123** [comment]
#### conf file

```
env {
  # You can set flink configuration here
  execution.parallelism = 2
  job.mode = "STREAMING"
  flink.execution.checkpointing.interval = 5000
  flink.execution.checkpointing.unaligned.enabled = true
  flink.execution.checkpointing.aligned-checkpoint-timeout = 100000
  flink.jobstore.cache-size = 52428801
  flink.state.backend.rocksdb.predefined-options = SPINNING_DISK_OPTIMIZED_HIGH_MEM
}

source {
  # This is a example source plugin **only for test and demonstrate the feature source plugin**
  FakeSource {
    parallelism = 2
    result_table_name = "fake"
    row.num = 16
    schema = {
      fields {
        name = "string"
        age = "int"
      }
    }
  }

  # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
  # please go to https://seatunnel.apache.org/docs/category/source-v2
}

transform {

  # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
  # please go to https://seatunnel.apache.org/docs/category/transform-v2
}

sink {
  Console {
    parallelism = 3
  }

  # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
  # please go to https://seatunnel.apache.org/docs/category/sink-v2
}

```
#### TestFlinkParameter
image
image

#### org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample
image
PTAL: @TyrantLucifer @ruanwenjun @EricJoy2048  I added some screenshots to demonstrate this

**Comment by TyrantLucifer** [comment]
> #### conf file
> ```
> env {
>   # You can set flink configuration here
>   execution.parallelism = 2
>   job.mode = "STREAMING"
>   flink.execution.checkpointing.interval = 5000
>   flink.execution.checkpointing.unaligned.enabled = true
>   flink.execution.checkpointing.aligned-checkpoint-timeout = 100000
>   flink.jobstore.cache-size = 52428801
>   flink.state.backend.rocksdb.predefined-options = SPINNING_DISK_OPTIMIZED_HIGH_MEM
> }
> 
> source {
>   # This is a example source plugin **only for test and demonstrate the feature source plugin**
>   FakeSource {
>     parallelism = 2
>     result_table_name = "fake"
>     row.num = 16
>     schema = {
>       fields {
>         name = "string"
>         age = "int"
>       }
>     }
>   }
> 
>   # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
>   # please go to https://seatunnel.apache.org/docs/category/source-v2
> }
> 
> transform {
> 
>   # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
>   # please go to https://seatunnel.apache.org/docs/category/transform-v2
> }
> 
> sink {
>   Console {
>     parallelism = 3
>   }
> 
>   # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
>   # please go to https://seatunnel.apache.org/docs/category/sink-v2
> }
> ```
> 
> #### TestFlinkParameter
> image image
> 
> #### org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample
> image PTAL: @TyrantLucifer @ruanwenjun @EricJoy2048 I added some screenshots to demonstrate this

I think you should ensure the parameters injected in real flink jobs, not only codes. You should submit a seatunnel on flink engine and make a snapshot to verify it worked.

**Comment by zhilinli123** [comment]
> > #### conf file
> > ```
> > env {
> >   # You can set flink configuration here
> >   execution.parallelism = 2
> >   job.mode = "STREAMING"
> >   flink.execution.checkpointing.interval = 5000
> >   flink.execution.checkpointing.unaligned.enabled = true
> >   flink.execution.checkpointing.aligned-checkpoint-timeout = 100000
> >   flink.jobstore.cache-size = 52428801
> >   flink.state.backend.rocksdb.predefined-options = SPINNING_DISK_OPTIMIZED_HIGH_MEM
> > }
> > 
> > source {
> >   # This is a example source plugin **only for test and demonstrate the feature source plugin**
> >   FakeSource {
> >     parallelism = 2
> >     result_table_name = "fake"
> >     row.num = 16
> >     schema = {
> >       fields {
> >         name = "string"
> >         age = "int"
> >       }
> >     }
> >   }
> > 
> >   # If you would like to get more information about how to configure seatunnel and see full list of source plugins,
> >   # please go to https://seatunnel.apache.org/docs/category/source-v2
> > }
> > 
> > transform {
> > 
> >   # If you would like to get more information about how to configure seatunnel and see full list of transform plugins,
> >   # please go to https://seatunnel.apache.org/docs/category/transform-v2
> > }
> > 
> > sink {
> >   Console {
> >     parallelism = 3
> >   }
> > 
> >   # If you would like to get more information about how to configure seatunnel and see full list of sink plugins,
> >   # please go to https://seatunnel.apache.org/docs/category/sink-v2
> > }
> > ```
> > 
> > 
> > #### TestFlinkParameter
> > image image
> > #### org.apache.seatunnel.example.flink.v2.SeaTunnelApiExample
> > image PTAL: @TyrantLucifer @ruanwenjun @EricJoy2048 I added some screenshots to demonstrate this
> 
> I think you should ensure the parameters injected in real flink jobs, not only codes. You should submit a seatunnel on flink engine and make a snapshot to verify it worked.
image
image
image
image

I provide some screenshots of the flink run web Ui

**Review by EricJoy2048 — COMMENTED** [review]
LGTM

**Review by ruanwenjun — APPROVED** [review]
+1

**Comment by zhilinli123** [comment]
PTAL: @Hisoka-X

**Review by Hisoka-X — APPROVED** [review]
Looking great! Thanks @zhilinli123 .

**Comment by Hisoka-X** [comment]
@TyrantLucifer Could you take a look again?

**Comment by hailin0** [comment]
LGTM

**Pull request merged**
