### PR TITLE
[Doc]: updated link in Seatunnel website

### LINKED ISSUE #2222: [Bug] [Doc] SeaTunnel website have deadLink
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

The `concept/Intro to config file` page in seatunnel website have some link to connector. But it's not work at now. We need fix it.
image
image

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
## Purpose of this pull request

 Fixes #2222
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by CalvinKirs** [comment]
@zhongjiajie Hi, Do we have other way?

**Comment by zhongjiajie** [comment]
Maybe we can directly using content `/category/source` and `/category/source` to our concept. And then add some tricks in our dead link checker, just like https://github.com/apache/incubator-seatunnel/blob/a505d50f6c7151a612e974bba28927d5faac021e/.dlc.json#L19 to skip those specific rule

**Comment by zhongjiajie** [comment]
will make a quick test myself

**Comment by zhongjiajie** [comment]
Hi @PrajwalBorkar I make a quick test and it work correctly. You should:

0. Change sidebar https://github.com/apache/incubator-seatunnel/blob/62ca0759155a5521c2996a0fe12441a264f6a10e/docs/sidebars.js#L184-L196 and make `transform` some as source or sink(you can find in the `sidebar.js` with keyword `type: 'generated-index'` to see how to create it), which supported the category page link https://seatunnel.apache.org/docs/category/source.
1. Make some change in concept file, change `../connector/source` to `/docs/category/source`, `../transform` to `/docs/category/transform`, and `../connector/sink` to `/docs/category/sink`.

**Comment by zhongjiajie** [comment]
> Maybe we can directly using content `/category/source` and `/category/source` to our concept. And then add some tricks in our dead link checker, just like
> 
> https://github.com/apache/incubator-seatunnel/blob/a505d50f6c7151a612e974bba28927d5faac021e/.dlc.json#L19
> 
> to skip those specific rule

The reason CI thinks `/docs/category/*` is not a dead link it is because we added some ignore pattern in dead link checker

**Comment by PrajwalBorkar** [comment]
> Hi @PrajwalBorkar I make a quick test and it work correctly. You should:
> 
> 0. Change sidebar https://github.com/apache/incubator-seatunnel/blob/62ca0759155a5521c2996a0fe12441a264f6a10e/docs/sidebars.js#L184-L196
>     and make `transform` some as source or sink(you can find in the `sidebar.js` with keyword `type: 'generated-index'` to see how to create it), which supported the category page link https://seatunnel.apache.org/docs/category/source.
> 1. Make some change in concept file, change `../connector/source` to `/docs/category/source`, `../transform` to `/docs/category/transform`, and `../connector/sink` to `/docs/category/sink`.

So I have to change `transform` to https://github.com/apache/incubator-seatunnel/blob/62ca0759155a5521c2996a0fe12441a264f6a10e/docs/sidebars.js#L146-L163  .Im not able to understand how to make changes here.

**Comment by zhongjiajie** [comment]
> > Hi @PrajwalBorkar I make a quick test and it work correctly. You should:
> > 
> > 0. Change sidebar https://github.com/apache/incubator-seatunnel/blob/62ca0759155a5521c2996a0fe12441a264f6a10e/docs/sidebars.js#L184-L196
> >    
> >    and make `transform` some as source or sink(you can find in the `sidebar.js` with keyword `type: 'generated-index'` to see how to create it), which supported the category page link https://seatunnel.apache.org/docs/category/source.
> > 1. Make some change in concept file, change `../connector/source` to `/docs/category/source`, `../transform` to `/docs/category/transform`, and `../connector/sink` to `/docs/category/sink`.
> 
> So I have to change `transform` to
> 
> https://github.com/apache/incubator-seatunnel/blob/62ca0759155a5521c2996a0fe12441a264f6a10e/docs/sidebars.js#L146-L163
> 
> .Im not able to understand how to make changes here.

@PrajwalBorkar  do you mind I append a new commit to your branch? If not I will add a new commit to implement it

**Comment by PrajwalBorkar** [comment]
Yeah, you can use my branch to commit.

**Comment by Hisoka-X** [comment]
@PrajwalBorkar Hi, we had update seatunnel website path for transform//source/sink. So you can update link easily, can you go on work for this?

**Comment by PrajwalBorkar** [comment]
I think @zhongjiajie is working on this

**Pull request closed without merging**
