### PR TITLE
[Bug][common] fix possible unrecognized NestedField name

### LINKED ISSUE #4079: [Bug] [common]  fix possible unrecognized NestedField name
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

I think SeaTunnelSchema.java  parseTypeByString method maybe has a bug.
As code like this order, originContent is uppercase. And if here has a ROW type,  all nested field name in ROW type converted to uppercase.
However,  some connector such as apache iceberg  field name may case sensitive.

企业微信截图_16757718881211

### SeaTunnel Version

2.3.0

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wfrong**
fix https://github.com/apache/incubator-seatunnel/issues/4079
fix possible unrecognized NestedField name

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
Please provide the test case snapshot image and verify it in e2e test.

**Review by lightzhao — APPROVED** [review]

**Comment by lightzhao** [comment]
LGTM

**Comment by wfrong** [comment]
In the last time CI tests, updated-modules-integration-test (8, ubuntu-latest) is cancelled without any useful info. I can not  maka it appear agin in local env. Should I trigger  CI tests again ? cc @TyrantLucifer 
企业微信截图_16778327831491

**Comment by hailin0** [comment]
Will you continue to complete this PR?
@wfrong

**Pull request closed without merging**
