### PR TITLE
[Improve][Connector-V2][StarRocks] Delete the Mapper may not be used

### PR DESCRIPTION
**Pull request by 1ceWine**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by TaoZex** [comment]
Please change your title to [Improve][Connector-V2][StarRocks] Delete the Mapper may not be used

**Comment by TyrantLucifer** [comment]
Please fix your code style.

**Comment by TaoZex** [comment]
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/setup.md#install-jetbrains-idea-checkstyle-idea-plugin

You can change your code style through this document.

**Comment by 1ceWine** [comment]
&nbsp;I’LL READ IT， THANKS FOR THE ADVICE.



---Original---
From: ***@***.***&gt;
Date: Mon, Nov 28, 2022 01:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/incubator-seatunnel] [Improve][Connector-V2][StarRocks]Delete the Mapper may not be used (PR #3579)




 
https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/setup.md#install-jetbrains-idea-checkstyle-idea-plugin
 
You can change your code style through this document.

**Review by TaoZex — APPROVED** [review]
LGTM

**Review by Carl-Zhou-CN — APPROVED** [review]
+1

**Review by EricJoy2048 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
