### PR TITLE
[Improve][connector-v2][FileSink] Allow the user to set the row delimiter as an empty string

### PR DESCRIPTION
**Pull request by lightzhao**
If a user's text line is marked with a line delimiter, it is unnecessary to set the line delimiter, so  set the line separator as an empty string

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)

### CODE REVIEW

**Comment by lightzhao** [comment]
@Hisoka-X @TyrantLucifer please review ，thanks.

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Comment by lightzhao** [comment]
@TaoZex please review, thanks.

**Comment by lightzhao** [comment]
@Hisoka-X  please review, thanks.

**Comment by lightzhao** [comment]
@TyrantLucifer PTAL, thanks.

**Comment by lightzhao** [comment]
@TyrantLucifer PTAL, thanks.

**Comment by TyrantLucifer** [comment]
IMO, This can lead to data disruption and lost data, when user sets a empty delimiter, all data will be wrote on one line. How can we read this type file in SeaTunnel? There may be 10 rows of data before writing and only 1 row after reading. cc @EricJoy2048 @CalvinKirs Hey guys, what do you think about it?

**Comment by lightzhao** [comment]
> IMO, This can lead to data disruption and lost data, when user sets a empty delimiter, all data will be wrote on one line. How can we read this type file in SeaTunnel? There may be 10 rows of data before writing and only 1 row after reading. cc @EricJoy2048 @CalvinKirs Hey guys, what do you think about it?

This case is aimed at the fact that the user data already contains a newline symbol, which allows the user to set an empty action.

**Comment by lightzhao** [comment]
@EricJoy2048 @CalvinKirs PTAL.

**Review by CalvinKirs — APPROVED** [review]

**Comment by TaoZex** [comment]
Please incorporate the latest code changes in order to pass CI.

**Review by TyrantLucifer — APPROVED** [review]

**Pull request merged**
