### PR TITLE
[Fix][Transform] Fix sql transform lose source type and options

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
This PR fix sql transform lose source type and options.

### Does this PR introduce _any_ user-facing change?
no

### How was this patch tested?
add new test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @hailin0 @rewerma

**Review by lightzhao — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Review by Carl-Zhou-CN — APPROVED** [review]
+1

**Comment by luhanbin111** [comment]
?修复了什么，我使用mongodb同步mysql时还是会显示没有配置result_table_name
2024-07-17 16:32:40,417 INFO  [o.a.s.e.c.p. ConfigParserUtil  ] [main] - Currently, incorrect configuration of source_table_name and result_table_name options don't affect job running.  In the future we will ban incorrect configurations.
2024-07-17 16:32:40,417 WARN  [o.a.s.e.c.p. ConfigParserUtil  ] [main] - This configuration is not recommended. A source/transform(MongoDB-CDC) is not configured with 'result_table_name' option, but subsequent transform/sink(Sql) is configured with 'source_table_name' option value of 'test'.
2024-07-17 16:32:40,417 INFO  [o.a.s.e.c.p. ConfigParserUtil  ] [main] - Currently, incorrect configuration of source_table_name and result_table_name options don't affect job running.  In the future we will ban incorrect configurations.
2024-07-17 16:32:40,417 WARN  [o.a.s.e.c.p. ConfigParserUtil  ] [main] - This configuration is not recommended.  A source/transform(Sql) is configured with 'result_table_name' option value of 'test1', but subsequent transform/sink(jdbc) is not configured with 'source_table_name' option.

**Comment by liuyhl** [comment]
同问

**Pull request merged**
