### PR TITLE
[Chore] Remove redundant logic of loading jvm options

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
image

**Comment by hailin0** [comment]
@EricJoy2048

**Review by EricJoy2048 — APPROVED** [review]

**Review by ic4y — COMMENTED** [review]
1、Processing the jvm_client_options configuration file in the script, which was previously done by JvmOptionsParser.java. (@MonsterChenzhuo PTAL)
2、Turned off the GC logs, which used to be output to the /tmp/seatunnel-xxxx directory, but not anymore. (Agree, GC information can also be obtained directly from the hazelcast interface)
3、Changed the HeapDump directory from /data/seatunnel/ to /tmp/seatunnel/... (Agree)

**Comment by MonsterChenzhuo** [comment]
> 1、Processing the jvm_client_options configuration file in the script, which was previously done by JvmOptionsParser.java. (@MonsterChenzhuo PTAL) 2、Turned off the GC logs, which used to be output to the /tmp/seatunnel-xxxx directory, but not anymore. (Agree, GC information can also be obtained directly from the hazelcast interface) 3、Changed the HeapDump directory from /data/seatunnel/ to /tmp/seatunnel/... (Agree)

Agree

**Review by ic4y — APPROVED** [review]

**Pull request merged**
