### PR TITLE
[Chore]Update .licenserc.yaml(ignore .svg checker)

### PR DESCRIPTION
**Pull request by CalvinKirs**

### CODE REVIEW

**Review by zhongjiajie — DISMISSED** [review]

**Comment by zhongjiajie** [comment]
should also remove this https://github.com/apache/incubator-seatunnel/blob/dev/.github/workflows/license.yml#L26

**Comment by zhongjiajie** [comment]
> should also remove this https://github.com/apache/incubator-seatunnel/blob/dev/.github/workflows/license.yml#L26

To avoid regression.

**Comment by zhongjiajie** [comment]
I will add more type files in directory `docs`

**Comment by CalvinKirs** [comment]
> I will add more type files in directory `docs`

thanks for your reminder:)

**Review by zhongjiajie — APPROVED** [review]

**Pull request merged**
