### PR TITLE
[Improve][Connector-v2][HiveSink]remove drop partition when abort.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
#4920 
When the commit fails, the hive partition should not be deleted. Deleting the partition will put the underlying data in the trash, so no operations should be performed on the partition, and only the currently written files should be rollback.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liugddx** [comment]
@TyrantLucifer PTAL

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
IMO，when user write new partitions this action is useful，2pc has all the lifecycle，add a parameter to control the action is better，not remove it. Default action is that not change the metadata of hive metastore.

**Comment by lightzhao** [comment]
> IMO，when user write new partitions this action is useful，2pc has all the lifecycle，add a parameter to control the action is better，not remove it. Default action is that not change the metadata of hive metastore.

The partition will be loaded every commit. I don’t understand where abort is useful for the new partition. Now this operation has an impact on metadata and underlying data.

**Comment by ic4y** [comment]
If no modifications are made, it seems this could lead to data loss since not all are new partitions. So, this is a bug currently, is my understanding correct? @TyrantLucifer @lightzhao @EricJoy2048

**Comment by lightzhao** [comment]
> If no modifications are made, it seems this could lead to data loss since not all are new partitions. So, this is a bug currently, is my understanding correct?

yes, data will be lost.

**Comment by EricJoy2048** [comment]
Yes, you can right. LGTM

**Review by EricJoy2048 — DISMISSED** [review]

**Comment by EricJoy2048** [comment]
@TyrantLucifer  PTAL.

**Comment by ic4y** [comment]
@EricJoy2048 @TyrantLucifer PTAL, I've added a parameter for control.

**Review by TyrantLucifer — DISMISSED** [review]
LGTM

**Review by ic4y — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
