### PR TITLE
[hotfix][e2e][influxdb] Fix testcase and move to seatunnel-connector-v2-e2e

### PR DESCRIPTION
**Pull request by hailin0**
## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by hailin0** [comment]
image

**Review by ashulin — DISMISSED** [review]
LGTM

**Comment by hailin0** [comment]
image

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
