### PR TITLE
[Bug] [example] IDEA cannot run the examples directly without Lombok plugin

### PR DESCRIPTION
**Pull request by LingangJiang**
Add a step of Install JetBrains IDEA Lombok Plugin, otherwise the IDEA cannot run the example.

https://github.com/apache/incubator-seatunnel/issues/1840

## Purpose of this pull request
Add a step of Install JetBrains IDEA Lombok Plugin in in the document [Set Up Develop Environment](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/setup.md) to remind people to install the Lombok plugin, just as it reminds people to install Scala plugin. Otherwise, IDEA cannot run the examples successfully.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
Good catch, I would like to remove the lombok dependency, we just used it in two class. @CalvinKirs @BenJFan

**Comment by Hisoka-X** [comment]
> Good catch, I would like to remove the lombok dependency, we just used it in two class. @CalvinKirs @BenJFan

Agree with remove it

**Comment by CalvinKirs** [comment]
> 

The different idea is that we can use it widely in our projects, it makes our code cleaner, I don't think it's a burden for developers.

**Comment by legendtkl** [comment]
Agreed with @CalvinKirs . With lombok, we can save much time not to do the trival but necessary work.

**Comment by kezhenxu94** [comment]
> The different idea is that we can use it widely in our projects, it makes our code cleaner, I don't think it's a burden for developers.

I'm +1. Installing a plugin is a one-off work, just like you install Scala plugin and all other plugins that you love...

Java has many historical reasons that it has to be verbose, but Lombok is a life saver for both code authors and reviewers, authors don't need to write annoying `getters/setters/toString/hashcode/equals/try-catch/etc.` codes, reviewers can save more time and mind not to review these boilerplate codes.

**Comment by ruanwenjun** [comment]
OK,  I actually like lombok too. If no other concern, I will merge this PR.

**Review by ruanwenjun — APPROVED** [review]

**Review by CalvinKirs — APPROVED** [review]

**Comment by CalvinKirs** [comment]
Thanks, looking forward to your next contribution

**Pull request merged**
