### PR TITLE
[Bug][seatunnel-flink-starter]Fix NPE when starting from checkpoint.

### PR DESCRIPTION
**Pull request by lightzhao**
NPE will appear when Flink is set to start from the checkpoint point.
image
image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@Hisoka-X @TyrantLucifer PTAL, thanks.

**Comment by TyrantLucifer** [comment]
cc @ashulin PTAL.

**Comment by lightzhao** [comment]
@ashulin PTAL, thanks.

**Comment by lightzhao** [comment]
@EricJoy2048 @TyrantLucifer @Hisoka-X @ashulin PTAL.

**Review by Hisoka-X — APPROVED** [review]

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
