### PR TITLE
[Bug][Connector-v2][KafkaSink]Fix the permission problem caused by client.id.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request
The configured "client. id" should be used, otherwise it will cause permission problems, as shown in the following screenshot.
image

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by lightzhao** [comment]
@ruanwenjun @Hisoka-X @TyrantLucifer PTAL.

**Comment by Hisoka-X** [comment]
Can you provide some document or screenshot to prove your change are right？

**Comment by lightzhao** [comment]
> Can you provide some document or screenshot to prove your change are right？

This screenshot shows the transaction permission exception. "commitInfo. getKafkaProperties()" gets the kafka property in the configuration. Using client.id in the configuration will not cause permission problems. I have tested this.
image

**Review by Hisoka-X — APPROVED** [review]

**Comment by lightzhao** [comment]
@ruanwenjun @TyrantLucifer PTAL.

**Comment by lightzhao** [comment]
@EricJoy2048 @ruanwenjun @ashulin @TaoZex PTAL.

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
