### PR TITLE
[Feature][Connector-V2] add Aliyun SLS connector #3733

### PR DESCRIPTION
**Pull request by XenosK**
### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by XenosK** [comment]
This Pr For Sls（Aliyun Log Service） Source Connector

**Comment by Hisoka-X** [comment]
Thanks

Please update：

1. add ci label
https://github.com/apache/seatunnel/blob/cc5949988b7a851c49d594389fd3b96dbe0f9508/.github/workflows/labeler/label-scope-conf.yml#L250

2. add docs（zh/en）

reference
https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/

3. add e2e testcase

reference
https://github.com/apache/seatunnel/tree/dev/seatunnel-e2e/seatunnel-connector-v2-e2e/

4. update `plugin-mapping.properties`

https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties


5. add maven dependency into this module
https://github.com/apache/seatunnel/blob/cc5949988b7a851c49d594389fd3b96dbe0f9508/seatunnel-dist/pom.xml#L546

**Comment by XenosK** [comment]
1、2、4、5 already done，next ,  add e2e testcase

**Comment by XenosK** [comment]
I have successfully run the test case locally, but need a personal account to run it

**Comment by Hisoka-X** [comment]
> I have successfully run the test case locally, but need a personal account to run it

Commit the code and disable the test case, then provide a screenshot of the successful test.

**Comment by XenosK** [comment]
sls_testcase

**Comment by XenosK** [comment]
> > I have successfully run the test case locally, but need a personal account to run it
> 
> Commit the code and disable the test case, then provide a screenshot of the successful test.

**Comment by XenosK** [comment]
> > I have successfully run the test case locally, but need a personal account to run it
> 
> Commit the code and disable the test case, then provide a screenshot of the successful test.

**Comment by XenosK** [comment]
> > I have successfully run the test case locally, but need a personal account to run it
> 
> Commit the code and disable the test case, then provide a screenshot of the successful test.

testcase_sls

**Comment by XenosK** [comment]
cc @Hisoka-X A screenshot of the successful test and Is it as indicated in the screenshot to disable the test case

**Comment by Hisoka-X** [comment]
Please fix ci.

**Comment by XenosK** [comment]
> Please fix ci.

Fixed

**Comment by Hisoka-X** [comment]
Please update https://github.com/apache/seatunnel/blob/dev/config/plugin_config

**Comment by XenosK** [comment]
> Please update https://github.com/apache/seatunnel/blob/dev/config/plugin_config

done,  Do we need to run ci again ?

**Review by Hisoka-X — APPROVED** [review]
LGTM if ci passes

**Comment by Hisoka-X** [comment]
Thanks @XenosK !

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
