### PR TITLE
[Feature][Zeta][REST-API] Add REST API Get all completed jobs informa…

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Purpose of this pull request
close:#4145

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
图片

**Comment by MonsterChenzhuo** [comment]
@EricJoy2048 @liugddx @hailin0 PTAL, thanks.

**Comment by liugddx** [comment]
Can we get the statistics of the job? The `amount of data`  etc.

**Comment by MonsterChenzhuo** [comment]
图片

**Comment by MonsterChenzhuo** [comment]
图片
I added more task information

**Comment by liugddx** [comment]
> 图片 I added more task information

The structure of the job is `job->pipeline->taskGroup->task`, when a job has multiple pipelines, the user may want to divide the pipelines for statistics,Can we count according to the nested structure of job->pipelines->taskGroup? 

`{
"jobId":"",
"pipelines":[
{
"pipelineId":"",
"sourcet":[
],
"Sink":[]
}
]
}`

@EricJoy2048 @hailin0 @ic4y @Hisoka-X any suggestion?

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
add UT/IT test case

**Comment by MonsterChenzhuo** [comment]
> add UT/IT test case

seatunnel-e2e/seatunnel-engine-e2e/connector-seatunnel-e2e-base/src/test/java/org/apache/seatunnel/engine/e2e/RestApiIT.java There are corresponding additions below.

**Comment by liugddx** [comment]
> 

@MonsterChenzhuo Can it be output according to this structure?

**Comment by MonsterChenzhuo** [comment]
> 

Oh, okay.

**Comment by MonsterChenzhuo** [comment]
> > 
> 
> @MonsterChenzhuo Can it be output according to this structure?
Oh, okay.

**Pull request closed without merging**
