### PR TITLE
[Improve][JdbcSink]Improve jdbc write performance.

### PR DESCRIPTION
**Pull request by lightzhao**
## Purpose of this pull request

There is no need to serialize when writing, an extra copy is added, and there is actually no task effect.
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TaoZex** [comment]
I don't think it's necessary to change the code. CC @ic4y

**Comment by laglangyue** [comment]
well,why SeaTunnelRow can be null？

> I don't think it's necessary to change the code. CC @ic4y

+1

**Comment by ic4y** [comment]
I remember that SeaTunnelRow objects may be reused on spark or flink engines. So if we get an object and don't write it out immediately but accumulate batches, we need to make a deep copy of the object, otherwise the object may be tampered with.

**Comment by ic4y** [comment]
I added a deep copy just because the data output by the sink was wrong. Therefore, it is not recommended to modify it, the risk is very high, and a complete test is required

**Comment by ic4y** [comment]
@lightzhao I will close this pr, of course you can reopen it if you think this modification is necessary and add a complete test.

**Comment by lightzhao** [comment]
> I will close this pr, of course you can reopen it if you think this modification is necessary and add a complete test.

I tested it completely under the flink engine and there is no problem.

**Comment by ic4y** [comment]
> > I will close this pr, of course you can reopen it if you think this modification is necessary and add a complete test.
> 
> I tested it completely under the flink engine and there is no problem.

Also need to test spark and zeta engine.

**Pull request closed without merging**
