### PR TITLE
[hotfix][ci] Fix license check error, due to `commons-codec` version diff

### PR DESCRIPTION
**Pull request by ruanwenjun**
## Purpose of this pull request

I find all the ci of the latest PR is failed, due to the license check failed.

This is due to the `THIRD-PARTY.txt.tmp` is diff with `LICENSE`

The current license.py cannot deal with below case, and will just discard below case.
```
(Apache License, Version 2.0) (The Apache Software License, Version 2.0) Apache Commons Codec (commons-codec:commons-codec:1.10 - http://commons.apache.org/proper/commons-codec/)
```

This PR is just wanted to make the ci passed.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@CalvinKirs @asdf2014 PTAL.

**Review by asdf2014 — CHANGES_REQUESTED** [review]
Thanks @ruanwenjun , however we shouldn't change the script, I believe this `licenseMerge` option of maven plugin is better way, please refer to https://github.com/apache/incubator-seatunnel/pull/1408 , thanks

**Comment by asdf2014** [comment]
> This is due to the THIRD-PARTY.txt.tmp is diff with LICENSE

This is not the root cause, which is the `sortArtifactByName` option of maven plugin should be disabled. Because when it has been enabled, the content of `THIRD-PARTY.txt` seems not right, and it has been solved by https://github.com/apache/incubator-seatunnel/pull/1387

**Comment by asdf2014** [comment]
As you can see from above image, the log is missing the `commons-pool:commons-pool:1.6`, it caused by the maven plugin with the `sortArtifactByName` option is enabled. And it has been solved by https://github.com/apache/incubator-seatunnel/pull/1387 .

By the way, because this change cannot fix the root cause, so it won't add the `commons-pool:commons-pool:1.6` license back, which is not the right way.

- this pr doesn't add it back

image

- the https://github.com/apache/incubator-seatunnel/pull/1387 pr dose add it back

image

Last, I wouldn't recommend add too many map instance in script, since it is equal to add `licenseMerge` option of maven plugin, which is more ease to use.

Anyway, thanks for your idea.

**Comment by asdf2014** [comment]
As you can see from above image, the log was missing the `commons-pool:commons-pool:1.6`, it caused by the maven plugin with the `sortArtifactByName` option was enabled. And it has been solved by https://github.com/apache/incubator-seatunnel/pull/1387 .

By the way, because this change cannot fix the root cause, so it won't add the `commons-pool:commons-pool:1.6` license back, which is not the right way I think.

- this pr doesn't add it back:
  image
- the https://github.com/apache/incubator-seatunnel/pull/1387 pr dose add it back:
  image

Besides, I wouldn't recommend add too many map instances in script, since it is equal to add `licenseMerge` option of maven plugin, which is more ease to use.

Anyway, thanks for your idea :smile:

**Comment by asdf2014** [comment]
As you can see from above image, the log was missing the `commons-pool:commons-pool:1.6`, it caused by the maven plugin with the `sortArtifactByName` option was enabled. And it has been solved by https://github.com/apache/incubator-seatunnel/pull/1387 .

By the way, because this change cannot fix the root cause, so it won't add the `commons-pool:commons-pool:1.6` license back, which is not the right way I think.

- this pr doesn't add it back:
  image
- the https://github.com/apache/incubator-seatunnel/pull/1387 pr dose add it back:
  image

Besides, I wouldn't recommend add too many map instances in script, since it is equal to add `licenseMerge` option of maven plugin by https://github.com/apache/incubator-seatunnel/pull/1408 , which is more ease to use.

Anyway, thanks for your idea :smile:

**Comment by asdf2014** [comment]
As you can see from above image, the log was missing the `commons-pool:commons-pool:1.6`, it caused by the maven plugin with the `sortArtifactByName` option was enabled. And it has been solved by https://github.com/apache/incubator-seatunnel/pull/1387 .

By the way, because this change cannot fix the root cause, so it won't add the `commons-pool:commons-pool:1.6` license back, which is not the right way I think.

- this pr doesn't add it back:
  image
- the https://github.com/apache/incubator-seatunnel/pull/1387 pr dose add it back:
  image

Besides, I wouldn't recommend add too many map instances in script, since it is equal to add `licenseMerge` option of maven plugin by https://github.com/apache/incubator-seatunnel/pull/1408 , which is more ease to use.

Anyway, thanks for your idea :smile:

**Comment by ruanwenjun** [comment]
@asdf2014 Ok, it would be great if #1387 already fix this. I will close this PR.

**Pull request closed without merging**
