### PR TITLE
[Improve][docs] Add doc zh-CN seatunnel for flink deployment.md instal…

### PR DESCRIPTION
**Pull request by tangaot**
[Improve][docs] Add doc zh-CN seatunnel for flink deployment.md installation.md quick-start.md

## Purpose of this pull request

This pull request adds Chinese (zh-CN) documentation about seatunnel quick-start, installation and deployment on Flink.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by ruanwenjun** [comment]
@tangaot Thanks for your patch, but I remember we will not maintain Chinese doc anymore, so is this PR acceptable? @CalvinKirs  My opinion is to close this PR.

**Comment by zhongjiajie** [comment]
I agree with you @ruanwenjun , we will have Chinese, but only with some black magic transform from English docs. we already have an issue with it https://github.com/apache/incubator-seatunnel/issues/1437

**Comment by CalvinKirs** [comment]
> @tangaot Thanks for your patch, but I remember we will not maintain Chinese doc anymore, so is this PR acceptable? @CalvinKirs My opinion is to close this PR.

Let's discuss this in an email, I can't find a corresponding discussion

**Comment by ruanwenjun** [comment]
> > @tangaot Thanks for your patch, but I remember we will not maintain Chinese doc anymore, so is this PR acceptable? @CalvinKirs My opinion is to close this PR.
> 
> Let's discuss this in an email, I can't find a corresponding discussion

I started a discussion at [this thread ](https://lists.apache.org/thread/j1vo1yccqp79bv69bzokbqq3n58zytql), this PR needs to be discussed before we can deal with.

**Comment by ruanwenjun** [comment]
After discuss in this [mail thread ](https://lists.apache.org/thread/j1vo1yccqp79bv69bzokbqq3n58zytql), we find it's better to use tools to generate the Chinese doc, and now we will not receive the PR about Chinese doc. Still thanks for your working, I will close this PR.

**Pull request closed without merging**
