### PR TITLE
[SeaTunnel#1218] rewrite spark start script with java

### LINKED ISSUE #1218: [Feature][core] rewrite most components of seatunnel start script with java
### Search before asking

- [X] I had searched in the [feature](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

It's difficult to write shell in right way, in `start-seatunnel-spark.sh` we can seem it is too difficult to extract  'env' conf to concat the final spark-submit command. so I want to rewrite most components of seatunnel start script with java.

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by yx91490**
## Purpose of this pull request

close #1218 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by wuchunfu** [comment]
@yx91490 Please resolve the conflicting files, thanks

**Comment by wuchunfu** [comment]
@yx91490 Some operations are placed in the code, will it reduce the flexibility, for example, you need to add a parameter to directly modify the shell script, instead of modifying the java code

**Comment by yx91490** [comment]
> @yx91490 Some operations are placed in the code, will it reduce the flexibility, for example, you need to add a parameter to directly modify the shell script, instead of modifying the java code

can you explain what kind of parameter you should frequently modify the script? but whatever, I don't think it's a good practice.

**Comment by wuchunfu** [comment]
> > @yx91490 Some operations are placed in the code, will it reduce the flexibility, for example, you need to add a parameter to directly modify the shell script, instead of modifying the java code
> 
> can you explain what kind of parameter you should frequently modify the script? but whatever, I don't think it's a good practice.

But anyway I feel that it is not a good practice to hard-code the command in the code

**Comment by yx91490** [comment]
> > > @yx91490 Some operations are placed in the code, will it reduce the flexibility, for example, you need to add a parameter to directly modify the shell script, instead of modifying the java code
> > 
> > 
> > can you explain what kind of parameter you should frequently modify the script? but whatever, I don't think it's a good practice.
> 
> But anyway I feel that it is not a good practice to hard-code the command in the code

I don't think write in java is a kind of 'hard code', you can reference spark-submit script, which is also very simple. I think if your code was good enough, you don't need frequently modify it to achive your goal.

**Comment by ruanwenjun** [comment]
Agree with make the script simple, use java to start job is ok, the previous script exist some magic transform.

**Review by CalvinKirs — APPROVED** [review]
LGTM ptal @ruanwenjun @BenJFan

**Review by ruanwenjun — APPROVED** [review]
LGTM

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Pull request merged**
