### PR TITLE
[Feature][flink-connector-jdbc] JdbcSink plugin supports batch mode by implementing FlinkBatchSink interface

### PR DESCRIPTION
**Pull request by kalencaya**
## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by Hisoka-X** [comment]
Has it been tested? The same code will report CNF in my environment.

Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil
	at org.apache.seatunnel.flink.sink.JdbcSink.outputBatch(JdbcSink.java:132)
	at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:77)
	at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:107)
	at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65)
	at org.apache.seatunnel.example.flink.LocalFlinkExample.main(LocalFlinkExample.java:32)
Caused by: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.jdbc.utils.JdbcTypeUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 5 more

**Comment by Hisoka-X** [comment]
> 



> Has it been tested? The same code will report CNF in my environment.
> 
> Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil at org.apache.seatunnel.flink.sink.JdbcSink.outputBatch(JdbcSink.java:132) at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:77) at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:107) at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65) at org.apache.seatunnel.example.flink.LocalFlinkExample.main(LocalFlinkExample.java:32) Caused by: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil ... 5 more Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.jdbc.utils.JdbcTypeUtil at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:419) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ... 5 more

maybe some jar had different version both include.

**Comment by kalencaya** [comment]
> 

I had tested it by `mvn clean package -DskipTests -Dfast` command firstly and submit a seatunnel flink job to local standalone flink cluster.

**Comment by kalencaya** [comment]
> > 
> 
> > Has it been tested? The same code will report CNF in my environment.
> > Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil at org.apache.seatunnel.flink.sink.JdbcSink.outputBatch(JdbcSink.java:132) at org.apache.seatunnel.flink.batch.FlinkBatchExecution.start(FlinkBatchExecution.java:77) at org.apache.seatunnel.Seatunnel.entryPoint(Seatunnel.java:107) at org.apache.seatunnel.Seatunnel.run(Seatunnel.java:65) at org.apache.seatunnel.example.flink.LocalFlinkExample.main(LocalFlinkExample.java:32) Caused by: java.lang.NoClassDefFoundError: org/apache/flink/connector/jdbc/utils/JdbcTypeUtil ... 5 more Caused by: java.lang.ClassNotFoundException: org.apache.flink.connector.jdbc.utils.JdbcTypeUtil at java.net.URLClassLoader.findClass(URLClassLoader.java:387) at java.lang.ClassLoader.loadClass(ClassLoader.java:419) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ... 5 more
> 
> maybe some jar had different version both include.

yeah, maybe you are right.
I would check my local environment again.

**Review by Hisoka-X — DISMISSED** [review]

**Comment by Hisoka-X** [comment]
@CalvinKirs LGTM

**Review by CalvinKirs — APPROVED** [review]
LGTM

**Pull request merged**
