### PR TITLE
[Improve] Move get schema logic from Config to ReadonlyConfig

### PR DESCRIPTION
**Pull request by Hisoka-X**
### Purpose of this pull request
This PR main do these thing.
1. Move get shema logic from Config to ReadonlyConfig, `CatalogTableUtil` will covert Config to ReadonlyConfig, the use it to read schema.
2. Fix the ReadonlyConfig dosen't keep the order of user config. To achieve it, I rewrite the logic of properties to map to replace jackson.
3. Add `flatten` parameter in `ConfigUtil` as a option to avoid flattening config key. (In schema config, flatten config key makes parsing the schema tricky)
4. Change `CatalogTableUtil::getCatalogTablesFromConfig` parameter type from `Config` to `ReadonlyConfig`. (In most of time, we invoke it with TableFactoryContext, so we can get ReadonlyConfig directly).

### Does this PR introduce _any_ user-facing change?
Yes or no? I rewrite all logic of get schema from config, the expected behavior should remain the same as before, but this is a refactoring of user-facing parts of the code.

### How was this patch tested?
add new test.

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  5. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  6. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by Hisoka-X** [comment]
cc @ic4y @ruanwenjun @hailin0

**Comment by hailin0** [comment]
How to test sort of keys

**Comment by Hisoka-X** [comment]
> How to test sort of keys

In fact the new test `treeMapFunctionTest` in [ConfigUtilTest.java](https://github.com/apache/seatunnel/pull/5534/files#diff-872196dddb6712cf7d233da33a3e3cc56880c2f26fdb5dba642f85b41b704838) can prove it, but it's not easy to notice, so I modify it, to recheck the order before and after invoke `treemap`.

**Review by hailin0 — APPROVED** [review]

**Review by ic4y — APPROVED** [review]

**Review by ruanwenjun — APPROVED** [review]
+1

**Pull request merged**
