### PR TITLE
[Engine] [ConfigFile] Add Config for Slot Service and Checkpoint

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
1. Add Config for Slot Service and Checkponit
2. Code cleanup

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by hailin0 — DISMISSED** [review]
LGTM

**Review by CalvinKirs — DISMISSED** [review]
LGTM
IT timeout:(

**Review by ashulin — COMMENTED** [review]
It may not be reasonable to move the `engine-server`'s config to `engine-common`.
My opinion is that passing an unparsed config to the server is parsed by the respective components. Of course, we should provide a common parsing method;

**Comment by Hisoka-X** [comment]
@ashulin @EricJoy2048 @CalvinKirs @hailin0 PTAL

**Review by CalvinKirs — APPROVED** [review]

**Review by TyrantLucifer — APPROVED** [review]
+1

**Pull request merged**
