### PR TITLE
[Bug][seatunnel-connector-flink-KafkaSink] fix not being able to send data to Kafka.

### PR DESCRIPTION
**Pull request by realdengziqi**
## Purpose of this pull request

fix not being able to send data to Kafka.
This problem should be caused by an outdated API. After I changed it to executeInsert, Seatunnel worked fine.
Here is my application config. You can use this script to test.
```
env {
  # You can set flink configuration here
  execution.parallelism = 1
  #execution.checkpoint.interval = 10000
  #execution.checkpoint.data-uri = "hdfs://hadoop102:9092/checkpoint"
}


source {
        KafkaTableStream {
                consumer.bootstrap.servers = "hadoop102:9092"
                consumer.group.id = "seatunnel-test"
                topics = test_csv
                result_table_name = test123
                format.type = csv
                schema = "[{\"field\":\"name\",\"type\":\"string\"},{\"field\":\"age\",\"type\":\"string\"}]"
                format.field-delimiter = ";"
                format.allow-comments = "true"
                format.ignore-parse-errors = "true"
        }
}


transform {
        sql{
                source_table_name = test123
                sql = "select name,age from test123"

        }
}

sink {
   KafkaTable {

         producer.bootstrap.servers = "hadoop102:9092"
         topics = test_sink
   }
}

```

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — DISMISSED** [review]
LGTM

**Comment by Hisoka-X** [comment]
In #1593 , @tobezhou33 say this method will create two job in one process, this will make data sink twice. Please check this.

**Comment by tobezhou33** [comment]
i have used table.excuteinsert to do it ,but i find it submit two jobs. because excuteinsert will execEnv.executeAsync() to submit a job named 'insert-into_',  and if use old planner ,it will send two same msg to sink.
image


i think tableenv.excute and StreamExecutionEnvironment().execute() only can excute once.  

the kafkatable.java is used jsonFormatDescriptor. maybe we can use datatestream api FlinkKafkaProducer and JsonRowSerializationSchema .

**Comment by realdengziqi** [comment]
@CalvinKirs  @BenJFan @tobezhou33 Thanks for your help, after trying it, I confirmed that `executeInsert` does cause two flink jobs to be submitted. So, I followed tobezhou33's advice and used datastream, FlinkKafkaProducer and JsonRowSerializationSchema to solve this problem. I tested it on my own cluster and it works fine. new commits at [9ea79fd](https://github.com/apache/incubator-seatunnel/commit/9ea79fdb027d6584369cbebf8cf92f470a7d995f)

**Comment by realdengziqi** [comment]
@CalvinKirs @BenJFan @tobezhou33 I modified the code to let it pass checkstyle. and it has been compiled locally.

**Review by Hisoka-X — DISMISSED** [review]
LGTM, please resolve conflict

**Comment by realdengziqi** [comment]
@BenJFan thanks. I have resolved the conflict and force push again

**Review by CalvinKirs — APPROVED** [review]

**Pull request merged**
