### PR TITLE
[Improve] Update version to 2.1.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by Hisoka-X**
## Purpose of this pull request
Update version to 2.1.1-SNAPSHOT.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/development/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by CalvinKirs — APPROVED** [review]

**Comment by ruanwenjun** [comment]
@CalvinKirs @BenJFan Maybe it's better to use [`${revision}`](https://maven.apache.org/maven-ci-friendly.html) to manage the project version. Once we need to change the version, we just need to change the parent pom.
I have test on my laptop, it can work.

**Comment by CalvinKirs** [comment]
> @CalvinKirs @BenJFan Maybe it's better to use [`${revision}`](https://maven.apache.org/maven-ci-friendly.html) to manage the project version. Once we need to change the version, we just need to change the parent pom. I have test on my laptop, it can work.

In fact, usually we will automatically generate the development version of the next version, just because we have been developing on dev.

In addition, there are some problems when using the release plug-in in this way, and the corresponding version cannot be read for modification. Can you try it?

**Comment by ruanwenjun** [comment]
> > @CalvinKirs @BenJFan Maybe it's better to use [`${revision}`](https://maven.apache.org/maven-ci-friendly.html) to manage the project version. Once we need to change the version, we just need to change the parent pom. I have test on my laptop, it can work.
> 
> In fact, usually we will automatically generate the development version of the next version, just because we have been developing on dev.
> 
> In addition, there are some problems when using the release plug-in in this way, and the corresponding version cannot be read for modification. Can you try it?

Ok, we can use release plugin to generate the version and modify the version in all pom. So we don't need to use revision.

I have tested with `release:prepare` it seems it can work well.

**Comment by CalvinKirs** [comment]
> > > @CalvinKirs @BenJFan Maybe it's better to use [`${revision}`](https://maven.apache.org/maven-ci-friendly.html) to manage the project version. Once we need to change the version, we just need to change the parent pom. I have test on my laptop, it can work.
> > 
> > 
> > In fact, usually we will automatically generate the development version of the next version, just because we have been developing on dev.
> > In addition, there are some problems when using the release plug-in in this way, and the corresponding version cannot be read for modification. Can you try it?
> 
> Ok, we can use release plugin to generate the version and modify the version in all pom. So we don't need to use revision.
> 
> I have tested with `release:prepare` it seems it can work well.

did you try it ``` ./mvnw release:prepare -Prelease, -DautoVersionSubmodules=true -DpushChanges=false```

**Comment by ruanwenjun** [comment]
> 

Yes, after execute `./mvnw release:prepare -Prelease, -DautoVersionSubmodules=true -DpushChanges=false `, will genetate two files in `seatunnel-dist/target`
```
apache-seatunnel-incubating-2.1.1-bin.tar.gz
apache-seatunnel-incubating-2.1.1-src.tar.gz
```

**Pull request merged**
