### PR TITLE
[connector-v2] add amazondynamicdb source split

### PR DESCRIPTION
**Pull request by john8628**
## Purpose of this pull request
#5250 

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by john8628** [comment]
@liugddx PTAL

**Comment by zhilinli123** [comment]
Good Job, Can you modify the connector document? Please refer to it for details
reference：https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md ，https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md?plain=1

**Comment by liugddx** [comment]
Please resolve code conflicts.

**Comment by john8628** [comment]
> Good Job, Can you modify the connector document? Please refer to it for details reference：https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md ，https://github.com/apache/seatunnel/blob/dev/docs/en/connector-v2/source/Mysql.md?plain=1


yean , i had modifed the doc, and help to review ;

**Comment by hailin0** [comment]
Please resolve code conflicts.

**Comment by hailin0** [comment]
conflict fixed

**Comment by hailin0** [comment]
Waiting for ci to succeed

**Comment by john8628** [comment]
sorry for the late reply, and thank you  for your work;

**Review by hailin0 — APPROVED** [review]
LGTM

**Review by liugddx — APPROVED** [review]
LGTM

**Pull request merged**
