### PR TITLE
[Hotfix][Connector-V2][Mongodbcdc] Fix mongodb cdc e2e instability

### PR DESCRIPTION
**Pull request by MonsterChenzhuo**
## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by MonsterChenzhuo** [comment]
@hailin0 PTAL，thanks.

**Comment by MonsterChenzhuo** [comment]
@hailin0 PTAL，thanks.

**Review by hailin0 — DISMISSED** [review]

**Comment by TyrantLucifer** [comment]
Could you please explain the meaning of this change? I see it only changed the url of mysql and the port mapping

**Comment by MonsterChenzhuo** [comment]
> Could you please explain the meaning of this change? I see it only changed the url of mysql and the port mapping

While debugging locally, I discovered that the 'Option' functionality occasionally throws a type conversion exception, prompting me to modify it to 'SingleChoiceOption'. This adjustment was driven by the observation from our E2E test contents, specifically the error message, "org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in mongodb.MongodbCDCIT iterable lengths differ, expected: <8> but was: <0> within 1 minute." 

I suspect that this type conversion exception might be causing an issue with the execution state, resulting in a failure to retrieve any data from our MySQL queries. To minimize the potential problem scope, I have made modifications to the related MySQL components in an attempt to narrow down possible issues.


I've undertaken work in three primary areas:

1. Rectified the type conversion exception.
2. Enhanced logging for container operations and MySQL data queries to facilitate future issue debugging.
图片
3. Avoided port conflicts and removed superfluous content to optimize the system.

**Review by Hisoka-X — APPROVED** [review]

**Review by TaoZex — APPROVED** [review]

**Review by hailin0 — APPROVED** [review]

**Pull request merged**
