### PR TITLE
[Feature][Connectors] Add connector-spark-iceberg source

### LINKED ISSUE #792: [Feature][Plugin] Support spark batch source from apache iceberg
### Search before asking

- [X] I had searched in the [feature](https://github.com/InterestingLab/seatunnel/issues?q=is%3Aissue+label%3A%22Feature%22) and found no similar feature requirement.

### Description

Support spark batch source from apache iceberg

### Usage Scenario

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by eye-gu**
this closes #792

### CODE REVIEW

**Comment by CalvinKirs** [comment]
you can refer this :https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md

**Comment by eye-gu** [comment]
> you can refer this :https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md

Thank you for teaching me about license. I have edited the relevant files according to the instructions.

**Comment by eye-gu** [comment]
@CalvinKirs Ci passed. Can you review the code?

**Comment by CalvinKirs** [comment]
@wuchunfu Hi. PTAL thx

**Comment by wuchunfu** [comment]
@ououtt Please add documentation to https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/spark/configuration/source-plugins , Thanks

**Comment by eye-gu** [comment]
> @ououtt Please add documentation to https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/spark/configuration/source-plugins , Thanks

done.

**Comment by wuchunfu** [comment]
@ououtt Please add the `common-options` option again, thank you

**Comment by eye-gu** [comment]
> @ououtt Please add the `common-options` option again, thank you

Thanks for reminding. Completed.

**Comment by eye-gu** [comment]
CodeQL / Analyze  false. What's the reason and how should I fix it?

**Review by wuchunfu — APPROVED** [review]
LGTM

**Comment by wuchunfu** [comment]
Well done, looking forward to your next contribution

**Comment by eye-gu** [comment]
@wuchunfu Thank you for your guidance. Maybe I can continue to do the sink spark plugin of iceberg

**Pull request merged**
