### PR TITLE
[Doc] Improve Console Sink document

### PR DESCRIPTION
**Pull request by zhilinli123**
subTask:https://github.com/apache/seatunnel/issues/4572

### CODE REVIEW

**Comment by zhilinli123** [comment]
ci run thanks @liugddx @ic4y

**Comment by zhilinli123** [comment]
@liugddx  ci Run thks

**Comment by zhilinli123** [comment]
PTAL @liugddx @EricJoy2048

**Review by liugddx — APPROVED** [review]

**Comment by zhilinli123** [comment]
PTAL: @EricJoy2048

**Review by EricJoy2048 — APPROVED** [review]

**Pull request merged**
