### PR TITLE
[Improve][e2e][Flink] Execute extra commands on task manager container

### PR DESCRIPTION
**Pull request by TyrantLucifer**
## Purpose of this pull request

Execute extra commands on task manager container

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by EricJoy2048** [comment]
@ashulin  PTAL

**Review by hailin0 — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]
LGTM

**Review by TaoZex — APPROVED** [review]
LGTM

**Review by EricJoy2048 — APPROVED** [review]
LGTM

**Pull request merged**
