### PR TITLE
[Improve] [Connector-V2] Remove scheduler in JDBC sink #4736

### LINKED ISSUE #4736: [Bug] [Connector-V2] Remove scheduler in JDBC sink
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

At now, we add scheduler in jdbc sink #2009 , this is not an acceptable solution, we need to remove the corresponding code, because sometimes the thread pool created in the sink cannot be recycled normally.

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
-
```

### Running Command

```shell
-
```

### Error Exception

```log
-
```

### Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by liugddx**
close #4736 

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by liugddx** [comment]
PTAL @ic4y

**Comment by ic4y** [comment]
The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.

**Comment by liugddx** [comment]
> The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.

This pr is for the jdbc connector, I will fix other connectors in another pr.

**Comment by ic4y** [comment]
> > The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.
> 
> This pr is for the jdbc connector, I will fix other connectors in another pr.

OceanBase, Snowflake, and Vertica are all using the JDBC connector.

**Comment by liugddx** [comment]
> > > The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.
> > 
> > 
> > This pr is for the jdbc connector, I will fix other connectors in another pr.
> 
> OceanBase, Snowflake, and Vertica are all using the JDBC connector.

Understood

**Comment by zhilinli123** [comment]
> > > The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.
> > 
> > 
> > This pr is for the jdbc connector, I will fix other connectors in another pr.
> 
> OceanBase, Snowflake, and Vertica are all using the JDBC connector.

+  Postgres cc @liugddx

**Comment by liugddx** [comment]
> > > > The relevant parameters in OceanBase.md, Snowflake.md, and Vertica.md documents also need to be removed.
> > > 
> > > 
> > > This pr is for the jdbc connector, I will fix other connectors in another pr.
> > 
> > 
> > OceanBase, Snowflake, and Vertica are all using the JDBC connector.
> 
> * Postgres cc @liugddx

Copy that

**Comment by ic4y** [comment]
Could this cause some JDBC e2e tests to fail?

**Review by ic4y — APPROVED** [review]

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
