### PR TITLE
[SeaTunnel][Dependency] Bump druid from 0.22.0 to 0.22.1

### PR DESCRIPTION
**Pull request by asdf2014**
## Purpose of this pull request

This PR bumps druid from 0.22.0 to 0.22.1, which is the latest version of Apache Druid.

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in you PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/developement/NewLicenseGuide.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Comment by davidzollo** [comment]
I noticed that this PR also update the log4j2 version from 2.8.2 to 2.15.0 and the netty version from 4.1.63 to 4.1.68

**Comment by davidzollo** [comment]
I want to know whether SeaTunnel can run normally in your local environment when you did these changes?

**Comment by asdf2014** [comment]
Hi @dailidong, thanks for your comment. Yes, it's normal. Maybe we should add some Integration Test in follow-up PRs to ensure everything is working well. What do you think

**Comment by davidzollo** [comment]
> Hi @dailidong, thanks for your comment. Yes, it's normal. Maybe we should add some Integration Test in follow-up PRs to ensure everything is working well. What do you think

good suggestion

**Review by davidzollo — APPROVED** [review]
+1
LGTM

**Comment by CalvinKirs** [comment]
> +1 LGTM
Hi, I'm not in favor of merging this PR, (at least not for now), have you paid attention to the relevant context?

**Pull request merged**
