### PR TITLE
[Improve][e2e]copy jars of plugin-lib for e2e

### PR DESCRIPTION
**Pull request by laglangyue**
## Purpose of this pull request

[Improve][e2e]copy jars of plugin-lib for e2e
add the method , and subclass for e2e just need to copy lib-jar to e2e/target/lib

## Check list

* [x] Code changed are covered with tests, or it does not need tests for reason:
* [x] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [x] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs

### CODE REVIEW

**Review by TyrantLucifer — COMMENTED** [review]
This involves the core process code, which I need to merge after testing it locally.

**Comment by TyrantLucifer** [comment]
> This involves the core process code, which I need to merge after testing it locally.

I think this is useless for e2e. The jar package that the plugin depends on should not be included in the e2e module, and the external dependency jars added need to be put into the specified directory by the developer, which greatly limits the packaging of the whole project. I think it is better for developers to create a docker image that contains jdbc drivers or other jar packages, so that it can be decoupled from the whole project and developers only need to pay attention to the e2e tests of their own development connectors. What do you think about it? @CalvinKirs @EricJoy2048 @hailin0 @Hisoka-X

**Comment by laglangyue** [comment]
if this we must make spark image contains the driver jar，and the lib must be spark jars.&nbsp;
we copy it to seatunnel plugins lib，for dm，I will run command: curl -o to local path，and copy it to spark container.&nbsp;
I con`t curl it in container，because the user is root.



---Original---
From: ***@***.***&gt;
Date: Mon, Sep 5, 2022 00:05 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [apache/incubator-seatunnel] [Improve][e2e]copy jars ofplugin-lib for e2e (PR #2640)




  
This involves the core process code, which I need to merge after testing it locally.
  
I think this is useless for e2e. The jar package that the plugin depends on should not be included in the e2e module, and the external dependency jars added need to be put into the specified directory by the developer, which greatly limits the packaging of the whole project. I think it is better for developers to create a docker image that contains jdbc drivers or other jar packages, so that it can be decoupled from the whole project and developers only need to pay attention to the e2e tests of their own development connectors. What do you think about it? @CalvinKirs @EricJoy2048 @hailin0 @Hisoka-X

**Comment by Hisoka-X** [comment]
I think we can copy from remote path, this way maybe better.

**Comment by laglangyue** [comment]
> I think we can copy from remote path, this way maybe better.

I has tried it, but the Spark Container is Root, I run the command 'curl -o xxx' in container, but I don't has permission to write

**Comment by Hisoka-X** [comment]
> > I think we can copy from remote path, this way maybe better.
> 
> I has tried it, but the Spark Container is Root, I run the command 'curl -o xxx' in container, but I don't has permission to write

Download the corresponding jar package through the Java code, and then copy it into the container like copying the seatunnel binary package when the container is initialized. How about this?

**Pull request closed without merging**
