### PR TITLE
[Rename]Changed seatunnel-engine to seatunnel-zeta

### PR DESCRIPTION
**Pull request by Sachin-2206**
@hailin0 
Good evening sir,

## Contribution In #3857
I fix issue https://github.com/apache/incubator-seatunnel/issues/3857

## Purpose of this pull request

I rename the seatunnel-engine to seatunnel-zeta as per your request and issue.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/incubator-seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/incubator-seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/incubator-seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/incubator-seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/incubator-seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/incubator-seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by TyrantLucifer** [comment]
waiting #3798 merged cc @hailin0

**Review by TyrantLucifer — CHANGES_REQUESTED** [review]
Please revert any changes that are not related to PR requirements

**Comment by hailin0** [comment]
> Please revert any changes that are not related to PR requirements

+1

@Sachin-2206 check files change
https://github.com/apache/incubator-seatunnel/pull/3888/files

**Comment by Sachin-2206** [comment]
@TyrantLucifer I think sir whn I changed package name seatunnel-engine to seatunnel-zeta . The java will unable to get old name as its package name same till now . If we change its package name , it will be alright

**Comment by Sachin-2206** [comment]
@TyrantLucifer Sir I will again try but now I will not change the import classes name, may be after that it will not return any issue. Give me some more time , I will done it by Monday. Thank you.

**Pull request closed without merging**
