### PR TITLE
[HotFix][e2e][jdbc] Fix not remove docker image after test finish on jdbc suite

### LINKED ISSUE #5585: [Bug][e2e][jdbc] Fix not remove docker image after test finish on jdbc suite
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/seatunnel/issues?q=is%3Aissue+label%3A%22bug%22) and found no similar issues.

### What happened

For reduce no space left on device error, #5568 has try to remove database images. But I found it didn't work.
`tearDown` is not annotated with `@AfterAll`, so `tearDown` will never execute after test.

https://github.com/apache/seatunnel/blob/41173357f847f7bc72119b3e0ebd5019f94a4c68/seatunnel-e2e/seatunnel-connector-v2-e2e/connector-jdbc-e2e/connector-jdbc-e2e-common/src/test/java/org/apache/seatunnel/connectors/seatunnel/jdbc/AbstractJdbcIT.java#L238-L243

### SeaTunnel Version

dev

### SeaTunnel Config

```conf
empty
```

### Running Command

```shell
empty
```

### Error Exception

```log
empty
```

### Zeta or Flink or Spark Version

_No response_

### Java or Scala Version

_No response_

### Screenshots

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by CheneyYin**
### Purpose of this pull request
- Fix: #5585 

### Check list

* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [x] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by CheneyYin** [comment]
@Hisoka-X @liugddx PTAL

**Review by liugddx — APPROVED** [review]
LGTM

**Comment by Hisoka-X** [comment]
I think it will be invoked in `TestCaseInvocationContextProvider::107`
image

**Comment by CheneyYin** [comment]
> I think it will be invoked in `TestCaseInvocationContextProvider::107` image

The `AfterTestExecutionCallback` just works on `TestContainer`, and `AbstractJdbcIT` didn't inherit `TestContainer`.

https://github.com/apache/seatunnel/blob/f5ed47795d4f5ea12088dc6f789ac9c00468b1ac/seatunnel-e2e/seatunnel-e2e-common/src/test/java/org/apache/seatunnel/e2e/common/junit/TestCaseInvocationContextProvider.java#L78-L83

teardown

**Comment by Hisoka-X** [comment]
Thanks @CheneyYin , you are right!

**Review by Hisoka-X — APPROVED** [review]

**Pull request merged**
