### PR TITLE
[Fix][Zeta] Resolve out-of-heap memory overflow

### PR DESCRIPTION
**Pull request by chaorongzhi**
## Purpose of this pull request

 I will run about 15 batch synchronization tasks per minute. When I add MaxMetaspaceSize = 2g in jvm_options, OOM will appear after about 1.5 hours of running. 
 I used Arthas to check and analyze dump image files. I found that the class loader is created again every time a batch task is submitted. After the batch task is completed, the class loader is not uninstalled, resulting in the rapid expansion of the metaSpace area and finally oom. So I added a cache to the classloader.

## Check list

* [ ] Code changed are covered with tests, or it does not need tests for reason:
* [ ] If any new Jar binary package adding in your PR, please add License Notice according
  [New License Guide](https://github.com/apache/seatunnel/blob/dev/docs/en/contribution/new-license.md)
* [ ] If necessary, please update the documentation to describe the new feature. https://github.com/apache/seatunnel/tree/dev/docs
* [ ] If you are contributing the connector code, please check that the following files are updated:
  1. Update change log that in connector document. For more details you can refer to [connector-v2](https://github.com/apache/seatunnel/tree/dev/docs/en/connector-v2)
  2. Update [plugin-mapping.properties](https://github.com/apache/seatunnel/blob/dev/plugin-mapping.properties) and add new connector information in it
  3. Update the pom file of [seatunnel-dist](https://github.com/apache/seatunnel/blob/dev/seatunnel-dist/pom.xml)
* [ ] Update the [`release-note`](https://github.com/apache/seatunnel/blob/dev/release-note.md).

### CODE REVIEW

**Comment by wu-a-ge** [comment]
Good Job!  My current processing is to remove ClassLoaderFirstChild

**Comment by Hisoka-X** [comment]
Good catch, but I think we should figure out why class loader not release after job finished. This is the reason of metaspace OOM. Is some thread not finished?

**Comment by hailin0** [comment]
> Good catch, but I think we should figure out why class loader not release after job finished. This is the reason of metaspace OOM. Is some thread not finished?

+1
Reuse classloader  will cause class conflicts and memory usage will continue to grow

**Comment by gguo** [comment]
@chaorongzhi I saw the issue had been closed by you. Has it been fixed now? 
Thanks, 
Gil

**Comment by shrikhaparul** [comment]
Ya this issue is also not fixed in the new 2.3.4 version as well....will it be resolved in new upcoming versions?

**Pull request closed without merging**
